// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Khách hàng, nhà cung cấp, nhân viên
/// </summary>
public partial class AccountObject
{
    /// <summary>
    /// PK Đối tượng
    /// </summary>
    public Guid AccountObjectId { get; set; }

    /// <summary>
    /// Mã đối tượng
    /// </summary>
    public string AccountObjectCode { get; set; }

    /// <summary>
    /// Tên đối tượng
    /// </summary>
    public string AccountObjectName { get; set; }

    /// <summary>
    /// Giới tính
    /// </summary>
    public int? Gender { get; set; }

    /// <summary>
    /// Ngày sinh
    /// </summary>
    public DateTime? BirthDate { get; set; }

    /// <summary>
    /// Nơi sinh
    /// </summary>
    public string BirthPlace { get; set; }

    /// <summary>
    /// Lương thỏa thuận
    /// </summary>
    public decimal? AgreementSalary { get; set; }

    /// <summary>
    /// Hệ số lương
    /// </summary>
    public decimal? SalaryCoefficient { get; set; }

    /// <summary>
    /// Số người phụ thuộc
    /// </summary>
    public int? NumberOfDependent { get; set; }

    /// <summary>
    /// Lương đóng bảo hiểm
    /// </summary>
    public decimal? InsuranceSalary { get; set; }

    /// <summary>
    /// Tài khoản ngân hàng (Là số TK cá nhân nếu là nhân viên)
    /// </summary>
    public string BankAccount { get; set; }

    /// <summary>
    /// Tên ngân hàng
    /// </summary>
    public string BankName { get; set; }

    /// <summary>
    /// Địa chỉ của đối tượng
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// Lưu MISACodeID của nhóm KH, NCC được chọn, cách nhau bởi dấu ;
    /// </summary>
    public string AccountObjectGroupList { get; set; }

    /// <summary>
    /// Lưu AccountObjectGroupCode của các nhóm KH, NCC được chọn, cách nhau bởi dấu ;
    /// </summary>
    public string AccountObjectGroupListCode { get; set; }

    /// <summary>
    /// Mã số thuế
    /// </summary>
    public string CompanyTaxCode { get; set; }

    /// <summary>
    /// Số điện thoại cố định
    /// </summary>
    public string Tel { get; set; }

    /// <summary>
    /// Số điện thoại di động
    /// </summary>
    public string Mobile { get; set; }

    /// <summary>
    /// Fax
    /// </summary>
    public string Fax { get; set; }

    /// <summary>
    /// Địa chỉ Email của tổ chức
    /// </summary>
    public string EmailAddress { get; set; }

    /// <summary>
    /// Website
    /// </summary>
    public string Website { get; set; }

    /// <summary>
    /// Điều khoản thanh toán
    /// </summary>
    public Guid? PaymentTermId { get; set; }

    /// <summary>
    /// Số nợ tối đa
    /// </summary>
    public decimal? MaximizeDebtAmount { get; set; }

    /// <summary>
    /// Hạn nợ ( Số ngày)
    /// </summary>
    public int? DueTime { get; set; }

    /// <summary>
    /// Số CMTND của người liên hệ
    /// </summary>
    public string IdentificationNumber { get; set; }

    /// <summary>
    /// Ngày cấp CMTND người liên hệ
    /// </summary>
    public DateTime? IssueDate { get; set; }

    /// <summary>
    /// Nơi cấp CMTND người liên hệ
    /// </summary>
    public string IssueBy { get; set; }

    /// <summary>
    /// Quốc gia
    /// </summary>
    public string Country { get; set; }

    /// <summary>
    /// Tỉnh/ Thành phố
    /// </summary>
    public string ProvinceOrCity { get; set; }

    /// <summary>
    /// Quận/ Huyện
    /// </summary>
    public string District { get; set; }

    /// <summary>
    /// Phường/Xã
    /// </summary>
    public string WardOrCommune { get; set; }

    /// <summary>
    /// Xưng hô
    /// </summary>
    public string Prefix { get; set; }

    /// <summary>
    /// Tên người liên hệ
    /// </summary>
    public string ContactName { get; set; }

    /// <summary>
    /// Chức vụ người liên hệ (Nếu đối tượng là nhân viên thì đây chính là chức vụ mặc định của nhân viên đó)
    /// </summary>
    public string ContactTitle { get; set; }

    /// <summary>
    /// Số điện thoại di động của người liên hệ
    /// </summary>
    public string ContactMobile { get; set; }

    /// <summary>
    /// Số điện thoại di động khác của người liên hệ
    /// </summary>
    public string OtherContactMobile { get; set; }

    /// <summary>
    /// Điện thoại cố định người liên hệ
    /// </summary>
    public string ContactFixedTel { get; set; }

    /// <summary>
    /// Email người liên hệ
    /// </summary>
    public string ContactEmail { get; set; }

    /// <summary>
    /// Địa chỉ người liên hệ
    /// </summary>
    public string ContactAddress { get; set; }

    /// <summary>
    /// Là nhà cung cấp
    /// </summary>
    public bool? IsVendor { get; set; }

    /// <summary>
    /// Là khách hàng
    /// </summary>
    public bool? IsCustomer { get; set; }

    /// <summary>
    /// Là cán bộ nhân viên
    /// </summary>
    public bool? IsEmployee { get; set; }

    /// <summary>
    /// 0 = là tổ chức; 1 = Là cá nhân
    /// </summary>
    public int? AccountObjectType { get; set; }

    /// <summary>
    /// Ngừng theo dõi
    /// </summary>
    public bool? Inactive { get; set; }

    /// <summary>
    /// Đơn vị của nhân viên
    /// </summary>
    public Guid? OrganizationUnitId { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public decimal? ReceiptableDebtAmount { get; set; }

    public string ShippingAddress { get; set; }

    public string AccountObjectGroupListName { get; set; }

    public Guid? EmployeeId { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Chi nhánh tài khoản ngân hàng)
    /// </summary>
    public string BankBranchName { get; set; }

    /// <summary>
    /// Tỉnh/Thành phố nơi mở tài khoản ngân hàng
    /// </summary>
    public string BankProvinceOrCity { get; set; }

    public string LegalRepresentative { get; set; }

    public string EinvoiceContactName { get; set; }

    public string EinvoiceContactEmail { get; set; }

    public string EinvoiceContactAddress { get; set; }

    public string EinvoiceContactMobile { get; set; }

    public int? ExternalAccountObjectType { get; set; }

    public int? EmployeeType { get; set; }

    public virtual ICollection<AccountObjectBankAccount> AccountObjectBankAccounts { get; set; } = new List<AccountObjectBankAccount>();

    public virtual ICollection<AccountObjectShippingAddress> AccountObjectShippingAddresses { get; set; } = new List<AccountObjectShippingAddress>();

    public virtual ICollection<Badeposit> BadepositAccountObjects { get; set; } = new List<Badeposit>();

    public virtual ICollection<BadepositDetail> BadepositDetails { get; set; } = new List<BadepositDetail>();

    public virtual ICollection<Badeposit> BadepositEmployees { get; set; } = new List<Badeposit>();

    public virtual ICollection<BawithDraw> BawithDrawAccountObjects { get; set; } = new List<BawithDraw>();

    public virtual ICollection<BawithDrawDetailSalary> BawithDrawDetailSalaries { get; set; } = new List<BawithDrawDetailSalary>();

    public virtual ICollection<BawithDrawDetail> BawithDrawDetails { get; set; } = new List<BawithDrawDetail>();

    public virtual ICollection<BawithDraw> BawithDrawEmployees { get; set; } = new List<BawithDraw>();

    public virtual ICollection<BawithdrawDetailTax> BawithdrawDetailTaxes { get; set; } = new List<BawithdrawDetailTax>();

    public virtual OrganizationUnit Branch { get; set; }

    public virtual ICollection<Capayment> CapaymentAccountObjects { get; set; } = new List<Capayment>();

    public virtual ICollection<CapaymentDetailSalary> CapaymentDetailSalaries { get; set; } = new List<CapaymentDetailSalary>();

    public virtual ICollection<CapaymentDetailTax> CapaymentDetailTaxes { get; set; } = new List<CapaymentDetailTax>();

    public virtual ICollection<CapaymentDetail> CapaymentDetails { get; set; } = new List<CapaymentDetail>();

    public virtual ICollection<Capayment> CapaymentEmployees { get; set; } = new List<Capayment>();

    public virtual ICollection<Careceipt> CareceiptAccountObjects { get; set; } = new List<Careceipt>();

    public virtual ICollection<CareceiptDetail> CareceiptDetails { get; set; } = new List<CareceiptDetail>();

    public virtual ICollection<Careceipt> CareceiptEmployees { get; set; } = new List<Careceipt>();

    public virtual ICollection<Contract> ContractAccountObjects { get; set; } = new List<Contract>();

    public virtual ICollection<ContractDetailRevenue> ContractDetailRevenues { get; set; } = new List<ContractDetailRevenue>();

    public virtual ICollection<Contract> ContractEmployees { get; set; } = new List<Contract>();

    public virtual ICollection<DebtAgreement> DebtAgreements { get; set; } = new List<DebtAgreement>();

    public virtual ICollection<DebtListDetail> DebtListDetails { get; set; } = new List<DebtListDetail>();

    public virtual AccountObject Employee { get; set; }

    public virtual ICollection<FaadjustmentDetailPost> FaadjustmentDetailPosts { get; set; } = new List<FaadjustmentDetailPost>();

    public virtual ICollection<FadecrementDetailPost> FadecrementDetailPosts { get; set; } = new List<FadecrementDetailPost>();

    public virtual ICollection<FadepreciationDetailPost> FadepreciationDetailPostCreditAccountObjects { get; set; } = new List<FadepreciationDetailPost>();

    public virtual ICollection<FadepreciationDetailPost> FadepreciationDetailPostDebitAccountObjects { get; set; } = new List<FadepreciationDetailPost>();

    public virtual ICollection<FixedAsset> FixedAssets { get; set; } = new List<FixedAsset>();

    public virtual ICollection<Glvoucher> GlvoucherAccountObjects { get; set; } = new List<Glvoucher>();

    public virtual ICollection<GlvoucherCrossEntryDetail> GlvoucherCrossEntryDetails { get; set; } = new List<GlvoucherCrossEntryDetail>();

    public virtual ICollection<GlvoucherDetail> GlvoucherDetailAccountObjects { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<GlvoucherDetail> GlvoucherDetailCreditAccountObjects { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<GlvoucherDetail> GlvoucherDetailEmployees { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<GlvoucherDetailForeignExchange> GlvoucherDetailForeignExchanges { get; set; } = new List<GlvoucherDetailForeignExchange>();

    public virtual ICollection<GlvoucherDetailTax> GlvoucherDetailTaxes { get; set; } = new List<GlvoucherDetailTax>();

    public virtual ICollection<Glvoucher> GlvoucherEmployees { get; set; } = new List<Glvoucher>();

    public virtual ICollection<GlvoucherListDetail> GlvoucherListDetails { get; set; } = new List<GlvoucherListDetail>();

    public virtual ICollection<IninventoryBook> IninventoryBooks { get; set; } = new List<IninventoryBook>();

    public virtual ICollection<IninvoiceHubOutward> IninvoiceHubOutwardAccountObjects { get; set; } = new List<IninvoiceHubOutward>();

    public virtual ICollection<IninvoiceHubOutwardDetail> IninvoiceHubOutwardDetails { get; set; } = new List<IninvoiceHubOutwardDetail>();

    public virtual ICollection<IninvoiceHubOutward> IninvoiceHubOutwardEmployees { get; set; } = new List<IninvoiceHubOutward>();

    public virtual ICollection<IninvoiceHubOutward> IninvoiceHubOutwardTransporters { get; set; } = new List<IninvoiceHubOutward>();

    public virtual ICollection<IninvoiceHubTransfer> IninvoiceHubTransfers { get; set; } = new List<IninvoiceHubTransfer>();

    public virtual ICollection<Ininward> IninwardAccountObjects { get; set; } = new List<Ininward>();

    public virtual ICollection<IninwardDetail> IninwardDetails { get; set; } = new List<IninwardDetail>();

    public virtual ICollection<Ininward> IninwardEmployees { get; set; } = new List<Ininward>();

    public virtual ICollection<Inoutward> InoutwardAccountObjects { get; set; } = new List<Inoutward>();

    public virtual ICollection<InoutwardDetail> InoutwardDetails { get; set; } = new List<InoutwardDetail>();

    public virtual ICollection<Inoutward> InoutwardEmployees { get; set; } = new List<Inoutward>();

    public virtual ICollection<Inoutward> InoutwardTransporters { get; set; } = new List<Inoutward>();

    public virtual ICollection<Intransfer> Intransfers { get; set; } = new List<Intransfer>();

    public virtual ICollection<AccountObject> InverseEmployee { get; set; } = new List<AccountObject>();

    public virtual ICollection<Loanagreement> LoanagreementAccountObjects { get; set; } = new List<Loanagreement>();

    public virtual ICollection<Loanagreement> LoanagreementVendors { get; set; } = new List<Loanagreement>();

    public virtual ICollection<OpeningAccountEntry> OpeningAccountEntries { get; set; } = new List<OpeningAccountEntry>();

    public virtual ICollection<OpeningAccountEntryDetailInvoice> OpeningAccountEntryDetailInvoices { get; set; } = new List<OpeningAccountEntryDetailInvoice>();

    public virtual ICollection<OpeningAccountEntryDetail> OpeningAccountEntryDetails { get; set; } = new List<OpeningAccountEntryDetail>();

    public virtual ICollection<OpeningInventoryEntry> OpeningInventoryEntries { get; set; } = new List<OpeningInventoryEntry>();

    public virtual OrganizationUnit OrganizationUnit { get; set; }

    public virtual ICollection<PasalaryExpenseAllocationDetail> PasalaryExpenseAllocationDetails { get; set; } = new List<PasalaryExpenseAllocationDetail>();

    public virtual ICollection<PasalaryExpenseDetail> PasalaryExpenseDetailCreditAccountObjects { get; set; } = new List<PasalaryExpenseDetail>();

    public virtual ICollection<PasalaryExpenseDetail> PasalaryExpenseDetailDebitAccountObjects { get; set; } = new List<PasalaryExpenseDetail>();

    public virtual ICollection<PasalarySheetDetail> PasalarySheetDetails { get; set; } = new List<PasalarySheetDetail>();

    public virtual ICollection<PatimeSheetDetail> PatimeSheetDetails { get; set; } = new List<PatimeSheetDetail>();

    public virtual ICollection<PatimeSheetSummaryDetail> PatimeSheetSummaryDetails { get; set; } = new List<PatimeSheetSummaryDetail>();

    public virtual ICollection<PavoucherDeduction> PavoucherDeductions { get; set; } = new List<PavoucherDeduction>();

    public virtual PaymentTerm PaymentTerm { get; set; }

    public virtual ICollection<Pucontract> PucontractAccountObjects { get; set; } = new List<Pucontract>();

    public virtual ICollection<Pucontract> PucontractEmployees { get; set; } = new List<Pucontract>();

    public virtual ICollection<Pudiscount> Pudiscounts { get; set; } = new List<Pudiscount>();

    public virtual ICollection<Puinvoice> PuinvoiceAccountObjects { get; set; } = new List<Puinvoice>();

    public virtual ICollection<Puinvoice> PuinvoiceEmployees { get; set; } = new List<Puinvoice>();

    public virtual ICollection<PulastedUnitPrice> PulastedUnitPrices { get; set; } = new List<PulastedUnitPrice>();

    public virtual ICollection<Puorder> PuorderAccountObjects { get; set; } = new List<Puorder>();

    public virtual ICollection<Puorder> PuorderEmployees { get; set; } = new List<Puorder>();

    public virtual ICollection<Pureturn> Pureturns { get; set; } = new List<Pureturn>();

    public virtual ICollection<Puservice> PuserviceAccountObjects { get; set; } = new List<Puservice>();

    public virtual ICollection<PuserviceDetail> PuserviceDetailAccountObjects { get; set; } = new List<PuserviceDetail>();

    public virtual ICollection<PuserviceDetail> PuserviceDetailTaxAccountObjects { get; set; } = new List<PuserviceDetail>();

    public virtual ICollection<Puservice> PuserviceEmployees { get; set; } = new List<Puservice>();

    public virtual ICollection<Puvoucher> PuvoucherAccountObjects { get; set; } = new List<Puvoucher>();

    public virtual ICollection<Puvoucher> PuvoucherEmployees { get; set; } = new List<Puvoucher>();

    public virtual ICollection<Sadiscount> SadiscountAccountObjects { get; set; } = new List<Sadiscount>();

    public virtual ICollection<Sadiscount> SadiscountEmployees { get; set; } = new List<Sadiscount>();

    public virtual ICollection<Sadiscount> SadiscountSuppliers { get; set; } = new List<Sadiscount>();

    public virtual ICollection<Sainvoice> SainvoiceAccountObjects { get; set; } = new List<Sainvoice>();

    public virtual ICollection<Sainvoice> SainvoiceEmployees { get; set; } = new List<Sainvoice>();

    public virtual ICollection<SainvoiceHub> SainvoiceHubAccountObjects { get; set; } = new List<SainvoiceHub>();

    public virtual ICollection<SainvoiceHub> SainvoiceHubEmployees { get; set; } = new List<SainvoiceHub>();

    public virtual ICollection<SainvoicePetroleum> SainvoicePetroleumAccountObjects { get; set; } = new List<SainvoicePetroleum>();

    public virtual ICollection<SainvoicePetroleum> SainvoicePetroleumEmployees { get; set; } = new List<SainvoicePetroleum>();

    public virtual ICollection<Saorder> SaorderAccountObjects { get; set; } = new List<Saorder>();

    public virtual ICollection<Saorder> SaorderEmployees { get; set; } = new List<Saorder>();

    public virtual ICollection<SapolicySaleCustomer> SapolicySaleCustomers { get; set; } = new List<SapolicySaleCustomer>();

    public virtual ICollection<Saquote> Saquotes { get; set; } = new List<Saquote>();

    public virtual ICollection<Sareturn> SareturnAccountObjects { get; set; } = new List<Sareturn>();

    public virtual ICollection<Sareturn> SareturnEmployees { get; set; } = new List<Sareturn>();

    public virtual ICollection<Sareturn> SareturnSuppliers { get; set; } = new List<Sareturn>();

    public virtual ICollection<SasaleGroupDetail> SasaleGroupDetails { get; set; } = new List<SasaleGroupDetail>();

    public virtual ICollection<Savoucher> SavoucherAccountObjects { get; set; } = new List<Savoucher>();

    public virtual ICollection<Savoucher> SavoucherEmployees { get; set; } = new List<Savoucher>();

    public virtual ICollection<Savoucher> SavoucherSuppliers { get; set; } = new List<Savoucher>();

    public virtual ICollection<SuallocationDetailPost> SuallocationDetailPostCreditAccountObjects { get; set; } = new List<SuallocationDetailPost>();

    public virtual ICollection<SuallocationDetailPost> SuallocationDetailPostDebitAccountObjects { get; set; } = new List<SuallocationDetailPost>();
}