// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Danh mục tài khoản kết chuyển
/// </summary>
public partial class AccountTransfer
{
    /// <summary>
    /// PK Tài khoản kết chuyển
    /// </summary>
    public Guid AccountTransferId { get; set; }

    /// <summary>
    /// Mã kết chuyển
    /// </summary>
    public string AccountTransferCode { get; set; } = null!;

    /// <summary>
    /// Thứ tự kết chuyển
    /// </summary>
    public int? TransferOrder { get; set; }

    /// <summary>
    /// Từ Tài khoản
    /// </summary>
    public string? FromAccount { get; set; }

    /// <summary>
    /// Đến Tài khoản
    /// </summary>
    public string? ToAccount { get; set; }

    /// <summary>
    /// Bên kết chuyển: 0: Nợ, 1: Có, 2: Hai bên
    /// </summary>
    public int? TransferSide { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Ngừng theo dõi
    /// </summary>
    public bool Inactive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    /// <summary>
    /// 0: Kết chuyển chi phí sản xuất; 1: kết chuyển xác định KQKD
    /// </summary>
    public int SetupType { get; set; }

    public virtual Account? ToAccountNavigation { get; set; }
}