// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class AgreementLastestInfo
{
    public string ApplicationCode { get; set; }

    public int? Version { get; set; }

    public DateTime? CheckUpdateDate { get; set; }

    public DateTime? PublishDate { get; set; }

    public string AttachmentContent { get; set; }

    public string ModifiedContent { get; set; }

    public Guid AgreementId { get; set; }

    public string AgreementLanguage { get; set; }

    /// <summary>
    /// Loại giấy phép: 0: giá trị cũ; 1: loại giấy phép thuê bao hàng năm; 2: Loại giấy phép vĩnh viễn
    /// </summary>
    public int? LicenseType { get; set; }
}