// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class AmistaxOrg
{
    public Guid Id { get; set; }

    public Guid? SmeorganizationUnitId { get; set; }

    public string? SmeorganizationUnitCode { get; set; }

    public string? SmeorganizationUnitName { get; set; }

    public string? SmeorganizationUnitTaxCode { get; set; }

    public string? AmisorganizationUnitId { get; set; }

    public string? AmisorganizationUnitCode { get; set; }

    public string? AmisorganizationUnitName { get; set; }

    public string? AmisorganizationUnitTaxCode { get; set; }

    public string? Address { get; set; }

    public string? FullName { get; set; }

    public string? Phone { get; set; }
}