// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class AmistaxAllOrg
{
    public string Id { get; set; } = null!;

    public string? ListOrg { get; set; }
}