// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Danh mục Tài khoản ngân hàng
/// </summary>
public partial class BankAccount
{
    /// <summary>
    /// PK Tài khoản ngân hàng
    /// </summary>
    public Guid BankAccountId { get; set; }

    /// <summary>
    /// Số tài khoản ngân hàng
    /// </summary>
    public string BankAccountNumber { get; set; }

    /// <summary>
    /// Ngân hàng
    /// </summary>
    public Guid? BankId { get; set; }

    /// <summary>
    /// Nơi mở: ví dụ Ngân hàng VCB chi nhánh 01
    /// </summary>
    public string BankName { get; set; }

    /// <summary>
    /// Địa chỉ nơi mở
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Ngừng theo dõi
    /// </summary>
    public bool Inactive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// Chủ tài khoản
    /// </summary>
    public string AccountHolder { get; set; }

    public string ProvinceOrCity { get; set; }

    public int? DefaultVoucherType { get; set; }

    public virtual ICollection<Badeposit> Badeposits { get; set; } = new List<Badeposit>();

    public virtual ICollection<BainternalTransfer> BainternalTransferFromBankAccounts { get; set; } = new List<BainternalTransfer>();

    public virtual ICollection<BainternalTransfer> BainternalTransferToBankAccounts { get; set; } = new List<BainternalTransfer>();

    public virtual Bank Bank { get; set; }

    public virtual ICollection<Bareconcile> Bareconciles { get; set; } = new List<Bareconcile>();

    public virtual ICollection<BawithDraw> BawithDraws { get; set; } = new List<BawithDraw>();

    public virtual OrganizationUnit Branch { get; set; }

    public virtual ICollection<CapaymentDetail> CapaymentDetails { get; set; } = new List<CapaymentDetail>();

    public virtual ICollection<CareceiptDetail> CareceiptDetails { get; set; } = new List<CareceiptDetail>();

    public virtual ICollection<EbtransferInfo> EbtransferInfos { get; set; } = new List<EbtransferInfo>();

    public virtual ICollection<GlvoucherDetailForeignExchange> GlvoucherDetailForeignExchanges { get; set; } = new List<GlvoucherDetailForeignExchange>();

    public virtual ICollection<GlvoucherDetail> GlvoucherDetails { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<Loanagreement> LoanagreementBankAccounts { get; set; } = new List<Loanagreement>();

    public virtual ICollection<Loanagreement> LoanagreementPayBankAccounts { get; set; } = new List<Loanagreement>();

    public virtual ICollection<OpeningAccountEntry> OpeningAccountEntries { get; set; } = new List<OpeningAccountEntry>();

    public virtual ICollection<OrganizationUnit> OrganizationUnits { get; set; } = new List<OrganizationUnit>();

    public virtual ICollection<PudiscountDetail> PudiscountDetails { get; set; } = new List<PudiscountDetail>();

    public virtual ICollection<PureturnDetail> PureturnDetails { get; set; } = new List<PureturnDetail>();

    public virtual ICollection<Puservice> Puservices { get; set; } = new List<Puservice>();

    public virtual ICollection<Puvoucher> Puvouchers { get; set; } = new List<Puvoucher>();

    public virtual ICollection<SadiscountDetail> SadiscountDetails { get; set; } = new List<SadiscountDetail>();

    public virtual ICollection<SareturnDetail> SareturnDetails { get; set; } = new List<SareturnDetail>();

    public virtual ICollection<Savoucher> Savouchers { get; set; } = new List<Savoucher>();
}