// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng chi tiết các khoản thuế của chứng từ Séc/ Ủy nhiệm chi
/// </summary>
public partial class BawithdrawDetailTax
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Tài khoản thuế
    /// </summary>
    public string? Vataccount { get; set; }

    /// <summary>
    /// Thuế quy đổi (Luôn lưu giá trị theo đồng tiền hạch toán)
    /// </summary>
    public decimal Vatamount { get; set; }

    /// <summary>
    /// Thuế suất
    /// </summary>
    public decimal? Vatrate { get; set; }

    /// <summary>
    /// Giá trị HHDV chưa thuế
    /// </summary>
    public decimal TurnoverAmount { get; set; }

    /// <summary>
    /// Ngày hóa đơn
    /// </summary>
    public DateTime? InvDate { get; set; }

    /// <summary>
    /// Ký hiệu hóa đơn
    /// </summary>
    public string? InvSeries { get; set; }

    /// <summary>
    /// Số hóa đơn
    /// </summary>
    public string? InvNo { get; set; }

    /// <summary>
    /// Mẫu số hóa đơn
    /// </summary>
    public string? InvTemplateNo { get; set; }

    /// <summary>
    /// Mã nhóm HHDV mua vào
    /// </summary>
    public Guid? PurchasePurposeId { get; set; }

    /// <summary>
    /// FK: ID Nhà cung cấp
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Mã số thuế
    /// </summary>
    public string? AccountObjectTaxCode { get; set; }

    /// <summary>
    /// Đối tượng
    /// </summary>
    public string? AccountObjectName { get; set; }

    /// <summary>
    /// Địa chỉ
    /// </summary>
    public string? AccountObjectAddress { get; set; }

    /// <summary>
    /// Thứ tự sắp xếp
    /// </summary>
    public int SortOrder { get; set; }

    public short? Sign { get; set; }

    public Guid? InvestmentProjectId { get; set; }

    public decimal? VatrateOther { get; set; }

    public virtual AccountObject? AccountObject { get; set; }

    public virtual InvestmentProject? InvestmentProject { get; set; }

    public virtual PurchasePurpose? PurchasePurpose { get; set; }

    public virtual BawithDraw Ref { get; set; } = null!;

    public virtual Account? VataccountNavigation { get; set; }
}