// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Nhóm mục thu/ Nhóm mục chi
/// </summary>
public partial class BudgetItem
{
    /// <summary>
    /// FK của bảng
    /// </summary>
    public Guid BudgetItemId { get; set; }

    /// <summary>
    /// Là mục chi cha
    /// </summary>
    public bool IsParent { get; set; }

    /// <summary>
    /// Mục chi cha
    /// </summary>
    public Guid? ParentId { get; set; }

    public string MisacodeId { get; set; }

    /// <summary>
    /// Cấp bậc
    /// </summary>
    public int? Grade { get; set; }

    /// <summary>
    /// Mã mục chi
    /// </summary>
    public string BudgetItemCode { get; set; }

    /// <summary>
    /// Tên mục chi
    /// </summary>
    public string BudgetItemName { get; set; }

    /// <summary>
    /// 0: Mục thu; 1: Mục chi
    /// </summary>
    public int? BudgetItemType { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Ngừng theo dõi
    /// </summary>
    public bool Inactive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    /// <summary>
    /// Cột dùng để sort trên báo cáo. Không sử dụng trên giao diện.
    /// </summary>
    public string SortMisacodeId { get; set; }

    public bool IsSystem { get; set; }

    public bool IsRecurrent { get; set; }

    public virtual ICollection<BadepositDetail> BadepositDetails { get; set; } = new List<BadepositDetail>();

    public virtual ICollection<BawithDrawDetail> BawithDrawDetails { get; set; } = new List<BawithDrawDetail>();

    public virtual ICollection<CapaymentDetail> CapaymentDetails { get; set; } = new List<CapaymentDetail>();

    public virtual ICollection<CareceiptDetail> CareceiptDetails { get; set; } = new List<CareceiptDetail>();

    public virtual ICollection<GlvoucherDetail> GlvoucherDetails { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<Loanagreement> Loanagreements { get; set; } = new List<Loanagreement>();

    public virtual ICollection<SadiscountDetail> SadiscountDetails { get; set; } = new List<SadiscountDetail>();

    public virtual ICollection<SareturnDetail> SareturnDetails { get; set; } = new List<SareturnDetail>();

    public virtual ICollection<SavoucherDetail> SavoucherDetails { get; set; } = new List<SavoucherDetail>();
}