// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class BusinessTypeHiddenOption
{
    public Guid OptionVisibleBusinessId { get; set; }

    public string OptionVisibleBusiness { get; set; }

    public string ColumnHidden { get; set; }

    public int? TypeHidden { get; set; }

    public string LayoutHidden { get; set; }

    public int? RefType { get; set; }

    public int? VoucherType { get; set; }

    public string SubSystemCode { get; set; }

    public string TableName { get; set; }

    public string DictionaryType { get; set; }

    public string ReportId { get; set; }

    public string ParentId { get; set; }
}