// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng chi tiết tab thuế của chứng từ chi thông thường
/// </summary>
public partial class CapaymentDetailTax
{
    /// <summary>
    /// Khóa chính của bảng Detail
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// Khóa chính của bảng Master
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Tài khoản thuế GTGT
    /// </summary>
    public string Vataccount { get; set; }

    /// <summary>
    /// Tiền thuế GTGT
    /// </summary>
    public decimal Vatamount { get; set; }

    /// <summary>
    /// % Thuế GTGT
    /// </summary>
    public decimal? Vatrate { get; set; }

    /// <summary>
    /// Giá trị HHDV chưa thuế
    /// </summary>
    public decimal TurnoverAmount { get; set; }

    /// <summary>
    /// Ngày hóa đơn
    /// </summary>
    public DateTime? InvDate { get; set; }

    /// <summary>
    /// Ký hiệu hóa đơn
    /// </summary>
    public string InvSeries { get; set; }

    /// <summary>
    /// Số hóa đơn
    /// </summary>
    public string InvNo { get; set; }

    /// <summary>
    /// Mẫu số hóa đơn
    /// </summary>
    public string InvTemplateNo { get; set; }

    /// <summary>
    /// Nhóm HHDV mua vào
    /// </summary>
    public Guid? PurchasePurposeId { get; set; }

    /// <summary>
    /// Đối tượng
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Đối tượng
    /// </summary>
    public string AccountObjectName { get; set; }

    /// <summary>
    /// Địa chỉ
    /// </summary>
    public string AccountObjectAddress { get; set; }

    /// <summary>
    /// Mã số thuế
    /// </summary>
    public string AccountObjectTaxCode { get; set; }

    /// <summary>
    /// Thứ tự sắp xếp
    /// </summary>
    public int? SortOrder { get; set; }

    public short? Sign { get; set; }

    public Guid? InvestmentProjectId { get; set; }

    public decimal? VatrateOther { get; set; }

    public virtual AccountObject AccountObject { get; set; }

    public virtual InvestmentProject InvestmentProject { get; set; }

    public virtual PurchasePurpose PurchasePurpose { get; set; }

    public virtual Capayment Ref { get; set; }

    public virtual Account VataccountNavigation { get; set; }
}