// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ComparisonReport
{
    /// <summary>
    /// ID báo cáo
    /// </summary>
    public string ReportId { get; set; } = null!;

    /// <summary>
    /// Thứ tự hiển thị của các báo cáo trong nhóm
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// ID của nhóm báo cáo
    /// </summary>
    public int? GroupId { get; set; }

    public string? GroupName { get; set; }
}