// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class CompanySearch
{
    public string CompanyTaxCode { get; set; } = null!;

    public string? CompanyStatus { get; set; }

    public DateTime? CompanyStatusTime { get; set; }

    public bool? IsShow { get; set; }

    public Guid? RefId { get; set; }

    public int? RefType { get; set; }

    public Guid? UserId { get; set; }
}