// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ConfigChangePostAccount
{
    public string TableName { get; set; }

    public string ColumnName { get; set; }

    public int ConvertDataType { get; set; }

    public string SourceColumnName { get; set; }

    public string MaterTableName { get; set; }

    public string MasterColumnName { get; set; }

    public string DateColumnName { get; set; }

    public string TableDescription { get; set; }

    public string ColumnDescription { get; set; }
}