// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ConfigTabVisibleByUser
{
    public Guid ConfigTabId { get; set; }

    /// <summary>
    /// ID của người dùng
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Mã tab được cấu hình
    /// </summary>
    public string SubSystemCode { get; set; } = null!;

    /// <summary>
    /// Phân hệ của tab được cấu hình
    /// </summary>
    public string? ParentSubSystemCode { get; set; }

    /// <summary>
    /// Trạng thái ẩn hiển
    /// </summary>
    public bool? Visible { get; set; }
}