// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng hợp đồng
/// </summary>
public partial class Contract
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid ContractId { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// True: Là dự án; Flase: Là hợp đồng
    /// </summary>
    public bool IsProject { get; set; }

    /// <summary>
    /// Cho biết Hợp đồng thuộc dự án nào
    /// </summary>
    public Guid? ProjectId { get; set; }

    /// <summary>
    /// Số hợp đồng bán/mua
    /// </summary>
    public string ContractCode { get; set; }

    /// <summary>
    /// Ngày ký (*)
    /// </summary>
    public DateTime? SignDate { get; set; }

    /// <summary>
    /// Trích yếu hợp đồng bán/mua
    /// </summary>
    public string ContractSubject { get; set; }

    /// <summary>
    /// Loại tiền
    /// </summary>
    public string CurrencyId { get; set; }

    /// <summary>
    /// Tỷ giá
    /// </summary>
    public decimal? ExchangeRate { get; set; }

    /// <summary>
    /// Giá trị hợp đồng/dự án
    /// </summary>
    public decimal ContractAmountOc { get; set; }

    /// <summary>
    /// Giá trị hợp đồng/dự án Quy đổi
    /// </summary>
    public decimal ContractAmount { get; set; }

    /// <summary>
    /// Giá trị thanh lý
    /// </summary>
    public decimal CloseAmountOc { get; set; }

    /// <summary>
    /// Giá trị thanh lý Quy đổi
    /// </summary>
    public decimal CloseAmount { get; set; }

    /// <summary>
    /// Hạn thanh toán
    /// </summary>
    public DateTime? PaymentDate { get; set; }

    /// <summary>
    /// Hạn giao hàng
    /// </summary>
    public DateTime? DeliveryDate { get; set; }

    /// <summary>
    /// Là hợp đồng phát sinh trước khi sử dụng phần mềm
    /// </summary>
    public bool IsArisedBeforeUseSoftware { get; set; }

    /// <summary>
    /// Số đã chi
    /// </summary>
    public decimal ExpenseAmountFinance { get; set; }

    /// <summary>
    /// Số đã thu
    /// </summary>
    public decimal ReceiptAmountOcfinance { get; set; }

    /// <summary>
    /// Số đã thu Quy đổi
    /// </summary>
    public decimal ReceiptAmountFinance { get; set; }

    /// <summary>
    /// Giá trị đã xuất hóa đơn
    /// </summary>
    public decimal InvoiceAmountOcfinance { get; set; }

    /// <summary>
    /// Giá trị đã xuất hóa đơn Quy đổi
    /// </summary>
    public decimal InvoiceAmountFinance { get; set; }

    /// <summary>
    /// ID  là khách hàng (cá nhân hay tổ chức) trong hợp đồng bán
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Địa chỉ khách hàng
    /// </summary>
    public string AccountObjectAddress { get; set; }

    /// <summary>
    /// Người liên hệ của khách hàng
    /// </summary>
    public string AccountObjectContactName { get; set; }

    /// <summary>
    /// Đơn vị thực hiện
    /// </summary>
    public Guid? OrganizationUnitId { get; set; }

    /// <summary>
    /// Người thực hiện
    /// </summary>
    public Guid? EmployeeId { get; set; }

    /// <summary>
    /// Tình trạng hợp đồng bán/mua
    /// </summary>
    public int? ContractStatusId { get; set; }

    /// <summary>
    /// Ngày thanh lý/Hủy bỏ
    /// </summary>
    public DateTime? CloseDate { get; set; }

    /// <summary>
    /// Lý do thanh lý, hủy bỏ
    /// </summary>
    public string CloseReason { get; set; }

    /// <summary>
    /// Tình trạng ghi nhận doanh số. 0=Chưa ghi doanh số: 1=Đã ghi doanh số
    /// </summary>
    public int? RevenueStatus { get; set; }

    /// <summary>
    /// Điều khoản khác
    /// </summary>
    public string OtherTerms { get; set; }

    /// <summary>
    /// Check tính giá thành
    /// </summary>
    public bool IsCalculatedCost { get; set; }

    /// <summary>
    /// Đã xuất hóa đơn
    /// </summary>
    public bool IsInvoiced { get; set; }

    /// <summary>
    /// Ngày ghi nhận doanh số
    /// </summary>
    public DateTime? RevenueDate { get; set; }

    /// <summary>
    /// Dự kiến chi
    /// </summary>
    public decimal TotalExpenseExpectAmount { get; set; }

    /// <summary>
    /// Thực chi
    /// </summary>
    public decimal TotalExpensedAmount { get; set; }

    /// <summary>
    /// Số còn phải chi=Dự kiến chi-thực chi
    /// </summary>
    public decimal BalanceExpenseAmountFinance { get; set; }

    /// <summary>
    /// Thực thu
    /// </summary>
    public decimal TotalReceiptedAmount { get; set; }

    /// <summary>
    /// Số còn phải thu
    /// </summary>
    public decimal BalanceReceiptAmountFinance { get; set; }

    /// <summary>
    /// Dự kiến lãi lỗ
    /// </summary>
    public decimal ProfitAndLossExpectAmountFinance { get; set; }

    /// <summary>
    /// Người tạo
    /// </summary>
    public string CreatedBy { get; set; }

    /// <summary>
    /// Ngày tạo
    /// </summary>
    public DateTime? CreatedDate { get; set; }

    /// <summary>
    /// Người sửa cuối
    /// </summary>
    public string ModifiedBy { get; set; }

    /// <summary>
    /// Ngày sửa cuối
    /// </summary>
    public DateTime? ModifiedDate { get; set; }

    /// <summary>
    /// Loai chung tu
    /// </summary>
    public int RefType { get; set; }

    public Guid? SaorderId { get; set; }

    public bool? IsParent { get; set; }

    /// <summary>
    /// Tổng giá trị đã xuất hóa đơn Sổ Tài Chính
    /// </summary>
    public decimal TotalInvoiceAmountFinance { get; set; }

    /// <summary>
    /// Tổng giá trị đã xuất hóa đơn Sổ Quản Trị
    /// </summary>
    public decimal TotalInvoiceAmountManagement { get; set; }

    public decimal? AccumSaleAmountFinance { get; set; }

    public decimal? AccumCostAmountFinance { get; set; }

    public decimal? AccumOtherAmountFinance { get; set; }

    public decimal ExpenseAmountManagement { get; set; }

    public decimal ReceiptAmountOcmanagement { get; set; }

    public decimal ReceiptAmountManagement { get; set; }

    public decimal InvoiceAmountOcmanagement { get; set; }

    public decimal InvoiceAmountManagement { get; set; }

    public decimal AccumSaleAmountManagement { get; set; }

    public decimal AccumCostAmountManagement { get; set; }

    public decimal AccumOtherAmountManagement { get; set; }

    public decimal TotalInvoiceAmountOcfinance { get; set; }

    public decimal TotalInvoiceAmountOcmanagement { get; set; }

    public decimal BalanceReceiptAmountManagement { get; set; }

    public decimal BalanceExpenseAmountManagement { get; set; }

    public decimal ProfitAndLossExpectAmountManagement { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    public string CustomField5 { get; set; }

    public string CustomField6 { get; set; }

    public string CustomField7 { get; set; }

    public string CustomField8 { get; set; }

    public string CustomField9 { get; set; }

    public string CustomField10 { get; set; }

    public string AccountObjectName { get; set; }

    public DateTime? CompleteDeliveryDate { get; set; }

    public virtual AccountObject AccountObject { get; set; }

    public virtual ICollection<BadepositDetail> BadepositDetails { get; set; } = new List<BadepositDetail>();

    public virtual ICollection<BainternalTransferDetail> BainternalTransferDetails { get; set; } = new List<BainternalTransferDetail>();

    public virtual ICollection<BawithDrawDetail> BawithDrawDetails { get; set; } = new List<BawithDrawDetail>();

    public virtual OrganizationUnit Branch { get; set; }

    public virtual ICollection<CapaymentDetail> CapaymentDetails { get; set; } = new List<CapaymentDetail>();

    public virtual ICollection<CareceiptDetail> CareceiptDetails { get; set; } = new List<CareceiptDetail>();

    public virtual ICollection<ContractAttachment> ContractAttachments { get; set; } = new List<ContractAttachment>();

    public virtual ICollection<ContractDetailContact> ContractDetailContacts { get; set; } = new List<ContractDetailContact>();

    public virtual ICollection<ContractDetailExpense> ContractDetailExpenses { get; set; } = new List<ContractDetailExpense>();

    public virtual ICollection<ContractDetailInventoryItem> ContractDetailInventoryItems { get; set; } = new List<ContractDetailInventoryItem>();

    public virtual ICollection<ContractDetailPayment> ContractDetailPayments { get; set; } = new List<ContractDetailPayment>();

    public virtual ICollection<ContractDetailRevenue> ContractDetailRevenues { get; set; } = new List<ContractDetailRevenue>();

    public virtual AccountObject Employee { get; set; }

    public virtual ICollection<FaadjustmentDetailPost> FaadjustmentDetailPosts { get; set; } = new List<FaadjustmentDetailPost>();

    public virtual ICollection<FadecrementDetailPost> FadecrementDetailPosts { get; set; } = new List<FadecrementDetailPost>();

    public virtual ICollection<FadepreciationDetailPost> FadepreciationDetailPosts { get; set; } = new List<FadepreciationDetailPost>();

    public virtual ICollection<FatransferDetail> FatransferDetails { get; set; } = new List<FatransferDetail>();

    public virtual ICollection<GlvoucherDetail> GlvoucherDetails { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<IninvoiceHubOutwardDetail> IninvoiceHubOutwardDetails { get; set; } = new List<IninvoiceHubOutwardDetail>();

    public virtual ICollection<IninvoiceHubTransferDetail> IninvoiceHubTransferDetails { get; set; } = new List<IninvoiceHubTransferDetail>();

    public virtual ICollection<IninwardDetail> IninwardDetails { get; set; } = new List<IninwardDetail>();

    public virtual ICollection<InoutwardDetail> InoutwardDetails { get; set; } = new List<InoutwardDetail>();

    public virtual ICollection<InproductionOrderProduct> InproductionOrderProducts { get; set; } = new List<InproductionOrderProduct>();

    public virtual ICollection<IntransferDetail> IntransferDetails { get; set; } = new List<IntransferDetail>();

    public virtual ICollection<JcacceptedDetail> JcacceptedDetails { get; set; } = new List<JcacceptedDetail>();

    public virtual ICollection<JccostAllocationDetail> JccostAllocationDetails { get; set; } = new List<JccostAllocationDetail>();

    public virtual ICollection<JcexpenseTranferDetail> JcexpenseTranferDetails { get; set; } = new List<JcexpenseTranferDetail>();

    public virtual ICollection<Jcopn> Jcopns { get; set; } = new List<Jcopn>();

    public virtual ICollection<JcperiodDetail> JcperiodDetails { get; set; } = new List<JcperiodDetail>();

    public virtual ICollection<Loanagreement> Loanagreements { get; set; } = new List<Loanagreement>();

    public virtual ICollection<OpeningAccountEntryDetail> OpeningAccountEntryDetails { get; set; } = new List<OpeningAccountEntryDetail>();

    public virtual OrganizationUnit OrganizationUnit { get; set; }

    public virtual ICollection<PasalaryExpenseDetail> PasalaryExpenseDetails { get; set; } = new List<PasalaryExpenseDetail>();

    public virtual ICollection<PudiscountDetail> PudiscountDetails { get; set; } = new List<PudiscountDetail>();

    public virtual ICollection<PuinvoiceDetail> PuinvoiceDetails { get; set; } = new List<PuinvoiceDetail>();

    public virtual ICollection<PuorderDetail> PuorderDetails { get; set; } = new List<PuorderDetail>();

    public virtual ICollection<PureturnDetail> PureturnDetails { get; set; } = new List<PureturnDetail>();

    public virtual ICollection<PuserviceDetail> PuserviceDetails { get; set; } = new List<PuserviceDetail>();

    public virtual ICollection<PuvoucherDetail> PuvoucherDetails { get; set; } = new List<PuvoucherDetail>();

    public virtual ICollection<SadiscountDetail> SadiscountDetails { get; set; } = new List<SadiscountDetail>();

    public virtual Saorder Saorder { get; set; }

    public virtual ICollection<SaorderDetail> SaorderDetails { get; set; } = new List<SaorderDetail>();

    public virtual ICollection<SaquoteDetail> SaquoteDetails { get; set; } = new List<SaquoteDetail>();

    public virtual ICollection<SareturnDetail> SareturnDetails { get; set; } = new List<SareturnDetail>();

    public virtual ICollection<SavoucherDetail> SavoucherDetails { get; set; } = new List<SavoucherDetail>();

    public virtual ICollection<SuallocationDetailPost> SuallocationDetailPosts { get; set; } = new List<SuallocationDetailPost>();

    public virtual ICollection<SutransferDetail> SutransferDetails { get; set; } = new List<SutransferDetail>();
}