// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class DbphysicalError
{
    public long? Error { get; set; }

    public long? Level { get; set; }

    public long? State { get; set; }

    public string? MessageText { get; set; }

    public string? RepairLevel { get; set; }

    public long? Status { get; set; }

    public long? DbId { get; set; }

    public long? DbFragId { get; set; }

    public long? ObjectId { get; set; }

    public long? IndexId { get; set; }

    public long? PartitionId { get; set; }

    public long? AllocUnitId { get; set; }

    public long? RidDbId { get; set; }

    public long? RidPruId { get; set; }

    public long? File { get; set; }

    public long? Page { get; set; }

    public long? Slot { get; set; }

    public long? RefDbId { get; set; }

    public long? RefPruId { get; set; }

    public long? RefFile { get; set; }

    public long? RefPage { get; set; }

    public long? RefSlot { get; set; }

    public long? Allocation { get; set; }

    public DateTime? CreatedDate { get; set; }
}