// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class DeadlockInvoice
{
    public Guid? RefId { get; set; }

    public string? TransactionId { get; set; }

    public int? PublishStatus { get; set; }

    public int? SendEmailStatus { get; set; }

    public string? Receiver { get; set; }

    public string? ReceiverEmail { get; set; }

    public string? CompanyTaxCode { get; set; }

    public string? InvSeries { get; set; }

    public string? InvNo { get; set; }

    public DateTime? InvDate { get; set; }

    public int? InvoiceSytem { get; set; }

    public DateTime? ModifiedDate { get; set; }
}