// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EbbeneficiaryAccount
{
    /// <summary>
    /// ID tài khoản
    /// </summary>
    public Guid AccountId { get; set; }

    /// <summary>
    /// Mã ngân hàng kết nối
    /// </summary>
    public string EbankCode { get; set; }

    /// <summary>
    /// Số tài khoản thụ hưởng
    /// </summary>
    public string AccountNo { get; set; }

    /// <summary>
    /// Tên chủ khoản thụ hưởng
    /// </summary>
    public string AccountName { get; set; }

    /// <summary>
    /// Mã số ngân hàng thụ hưởng
    /// </summary>
    public string BankNo { get; set; }

    /// <summary>
    /// Mã số chi nhánh ngân hàng thụ hưởng
    /// </summary>
    public string BranchNo { get; set; }
}