// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Ebrole
{
    public Guid EbroleId { get; set; }

    public string EbroleName { get; set; }

    public int? RefType { get; set; }

    public Guid? BranchId { get; set; }

    public int? SortOrder { get; set; }

    public string Batype { get; set; }

    public Guid? BankAccountId { get; set; }

    public bool? AutoCreateVoucher { get; set; }

    public bool? InActive { get; set; }

    public string AndOrValue { get; set; }

    public string ConditionConfig { get; set; }

    public string VoucherType { get; set; }

    public int? ReasonTypeId { get; set; }

    public Guid? AccountObjectId { get; set; }

    public string AccountObjectName { get; set; }

    public string JournalMemo { get; set; }

    public Guid? FromBankAccountId { get; set; }

    public Guid? ToBankAccountId { get; set; }

    public string DebitAccount { get; set; }

    public string CreditAccount { get; set; }

    public string Description { get; set; }

    public Guid? ExpenseItemId { get; set; }

    public Guid? JobId { get; set; }

    public Guid? ProjectWorkId { get; set; }

    public Guid? LoanagreementId { get; set; }

    public Guid? OrganizationUnitId { get; set; }

    public Guid? BudgetItemId { get; set; }

    public Guid? PucontractId { get; set; }

    public Guid? ContractId { get; set; }

    public Guid? PuorderId { get; set; }

    public Guid? SaorderId { get; set; }

    public Guid? ListItemId { get; set; }

    public int? DisplayOnBook { get; set; }

    public bool? IsCreatedVoucher { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public Guid? CreatedAtBranchId { get; set; }

    public DateTime? ApplyDate { get; set; }
}