// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EbtransactionReference
{
    public Guid ReferenceId { get; set; }

    public Guid RefId { get; set; }

    public Guid TransactionId { get; set; }

    public int? DisplayOnBook { get; set; }

    public bool IsMappingFromReconcile { get; set; }

    public Guid? RefDetailId { get; set; }

    public virtual EbhistoryTransaction Transaction { get; set; }
}