// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EbuserRegister
{
    public string BankCode { get; set; } = null!;

    public string TaxCode { get; set; } = null!;

    public string? CompanyName { get; set; }

    public string? ProvinceName { get; set; }

    public string? Address { get; set; }

    public string? Name { get; set; }

    public string? Position { get; set; }

    public string? PhoneNumber { get; set; }

    public string? Email { get; set; }
}