// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EinvoiceHubPendingPublish
{
    public int PartnerAppId { get; set; }

    public Guid RefId { get; set; }

    public int RefType { get; set; }
}