// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EinvoiceSummaryDetail
{
    public Guid RefDetailId { get; set; }

    public Guid RefId { get; set; }

    public string TransactionId { get; set; } = null!;

    /// <summary>
    /// Tiền thanh toán quy đổi
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Tiền thanh toán
    /// </summary>
    public decimal AmountOc { get; set; }

    /// <summary>
    /// Thành tiền chưa thuế quy đổi
    /// </summary>
    public decimal AmountWithoutVat { get; set; }

    /// <summary>
    /// Thành tiền chưa thuế
    /// </summary>
    public decimal AmountWithoutVatoc { get; set; }

    /// <summary>
    /// Địa chỉ người mua
    /// </summary>
    public string? BuyerAddress { get; set; }

    /// <summary>
    /// Mã khách hàng
    /// </summary>
    public string? BuyerCode { get; set; }

    /// <summary>
    /// Tên người mua
    /// </summary>
    public string? BuyerLegalName { get; set; }

    /// <summary>
    /// MST người mua
    /// </summary>
    public string? BuyerTaxCode { get; set; }

    public Guid? VoucherRefId { get; set; }

    public int? VoucherRefType { get; set; }

    /// <summary>
    /// Ngày hóa đơn hóa đơn
    /// </summary>
    public DateTime? InvDate { get; set; }

    /// <summary>
    /// Số hóa đơn
    /// </summary>
    public string? InvNo { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string? InvoiceNote { get; set; }

    /// <summary>
    /// Ký hiệu hóa đơn
    /// </summary>
    public string? InvSeries { get; set; }

    /// <summary>
    /// Trạng thái: 0-mới; 1-hủy; 2-điều chỉnh; 3-thay thế; 4-giải trình; 5-sai sót
    /// </summary>
    public int InvStatus { get; set; }

    /// <summary>
    /// Mẫu số hóa đơn
    /// </summary>
    public string? InvTemplateNo { get; set; }

    /// <summary>
    /// Mã hàng
    /// </summary>
    public string? ItemCode { get; set; }

    /// <summary>
    /// Tên hàng
    /// </summary>
    public string? ItemName { get; set; }

    /// <summary>
    /// Số hóa đơn gốc
    /// </summary>
    public string? OrgInvNo { get; set; }

    /// <summary>
    /// Loại hóa đơn bị thay thế/điều chỉnh (1: Hóa đơn 123; 3: Hóa đơn 51)
    /// </summary>
    public int? OrgInvoiceType { get; set; }

    /// <summary>
    /// Ký hiệu hóa đơn gốc
    /// </summary>
    public string? OrgInvSeries { get; set; }

    /// <summary>
    /// Mẫu số hóa đơn gốc
    /// </summary>
    public string? OrgInvTemplateNo { get; set; }

    /// <summary>
    /// Kỳ điều chỉnh
    /// </summary>
    public string? OrgPeriod { get; set; }

    /// <summary>
    /// Loại kỳ điều chỉnh
    /// </summary>
    public string? OrgPeriodType { get; set; }

    /// <summary>
    /// Số lượng
    /// </summary>
    public decimal? Quantity { get; set; }

    /// <summary>
    /// Số thứ tự
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// Ngày thông báo rà soát
    /// </summary>
    public DateTime? TaxRefDate { get; set; }

    /// <summary>
    /// Số thông báo rà soát của thuế
    /// </summary>
    public string? TaxRefNo { get; set; }

    /// <summary>
    /// Đơn vị tính
    /// </summary>
    public string? UnitName { get; set; }

    /// <summary>
    /// Tiền thuế quy đổi
    /// </summary>
    public decimal? Vatamount { get; set; }

    /// <summary>
    /// Tiền thuế
    /// </summary>
    public decimal VatamountOc { get; set; }

    /// <summary>
    /// Thuế suất
    /// </summary>
    public string? VatrateName { get; set; }

    public DateTime? OrgPeriodDate { get; set; }

    public Guid? UnitId { get; set; }

    public decimal? Vatrate { get; set; }

    public Guid? InventoryItemId { get; set; }

    public int? RowCustomStatus { get; set; }

    public decimal? FeeAmount { get; set; }

    public decimal? FeeAmountOc { get; set; }

    public decimal? ExchangeRate { get; set; }

    public virtual EinvoiceSummary Ref { get; set; } = null!;
}