// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EinvoiceReplacement
{
    public Guid EinvoiceReplacementId { get; set; }

    public Guid ReplaceInvRefId { get; set; }

    public int ReplaceInvRefType { get; set; }

    public Guid? OrgInvRefId { get; set; }

    public int? OrgInvRefType { get; set; }

    public string OrgInvNo { get; set; } = null!;

    public DateTime OrgInvDate { get; set; }

    public string OrgInvTemplateNo { get; set; } = null!;

    public string OrgInvSeries { get; set; } = null!;
}