// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EmailGroup
{
    public Guid EmailGroupId { get; set; }

    public string EmailGroupName { get; set; } = null!;

    public string? Note { get; set; }

    public virtual ICollection<EmailReference> EmailReferences { get; set; } = new List<EmailReference>();
}