// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EmailBook
{
    public Guid BookId { get; set; }

    public string BookName { get; set; }

    public string Email { get; set; }

    public string Tel { get; set; }

    public string CompanyName { get; set; }

    public string DepartmentName { get; set; }

    public string Note { get; set; }

    public virtual ICollection<EmailReference> EmailReferences { get; set; } = new List<EmailReference>();
}