// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class EmailReference
{
    public Guid ReferenceId { get; set; }

    public Guid EmailGroupId { get; set; }

    public Guid BookId { get; set; }

    public int SortOrder { get; set; }

    public virtual EmailBook Book { get; set; } = null!;

    public virtual EmailGroup EmailGroup { get; set; } = null!;
}