// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ExplorebarVisible
{
    public string KeyGroup { get; set; } = null!;

    public bool Visible { get; set; }

    public int OrderNumber { get; set; }

    public Guid UserId { get; set; }
}