// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng detail Hạch toán của Đánh giá lại TSCD
/// </summary>
public partial class FaadjustmentDetailPost
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// RefID của master
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Tài khoản nợ
    /// </summary>
    public string DebitAccount { get; set; }

    /// <summary>
    /// Tài khoản có
    /// </summary>
    public string CreditAccount { get; set; }

    /// <summary>
    /// Số tiền
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Đối tượng
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Khoản mục chi phí
    /// </summary>
    public Guid? ExpenseItemId { get; set; }

    /// <summary>
    /// Đơn vị
    /// </summary>
    public Guid? OrganizationUnitId { get; set; }

    /// <summary>
    /// Đối tượng THCP
    /// </summary>
    public Guid? JobId { get; set; }

    /// <summary>
    /// Công trình/vụ việc
    /// </summary>
    public Guid? ProjectWorkId { get; set; }

    /// <summary>
    /// Đơn đặt hàng
    /// </summary>
    public Guid? OrderId { get; set; }

    /// <summary>
    /// Hợp đồng
    /// </summary>
    public Guid? ContractId { get; set; }

    /// <summary>
    /// Chi phí không hợp lý
    /// </summary>
    public bool UnResonableCost { get; set; }

    /// <summary>
    /// Mã thống kê
    /// </summary>
    public Guid? ListItemId { get; set; }

    /// <summary>
    /// thứ tự sắp xếp
    /// </summary>
    public int SortOrder { get; set; }

    public virtual AccountObject AccountObject { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Account CreditAccountNavigation { get; set; }

    public virtual Account DebitAccountNavigation { get; set; }

    public virtual ExpenseItem ExpenseItem { get; set; }

    public virtual Job Job { get; set; }

    public virtual ListItem ListItem { get; set; }

    public virtual Saorder Order { get; set; }

    public virtual OrganizationUnit OrganizationUnit { get; set; }

    public virtual ProjectWork ProjectWork { get; set; }

    public virtual Faadjustment Ref { get; set; }
}