// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu trữ chi tiết các khoản còn lại Sau đánh giá lại TSCĐ
/// </summary>
public partial class FaadjustmentDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã tài sản
    /// </summary>
    public Guid FixedAssetId { get; set; }

    /// <summary>
    /// Đơn vị sử dụng
    /// </summary>
    public Guid OrganizationUnitId { get; set; }

    /// <summary>
    /// Giá trị còn lại trước điều chỉnh
    /// </summary>
    public decimal CurrentRemainingAmount { get; set; }

    /// <summary>
    /// Giá trị còn lại SAU điều chỉnh
    /// </summary>
    public decimal NewRemainingAmount { get; set; }

    /// <summary>
    /// Chênh lệch giá trị còn lại
    /// </summary>
    public decimal DiffRemainingAmount { get; set; }

    /// <summary>
    /// Thời gian sử dụng hiện tại
    /// </summary>
    public decimal CurrentLifeTime { get; set; }

    /// <summary>
    /// Thời gian sử dụng mới
    /// </summary>
    public decimal NewLifeTime { get; set; }

    /// <summary>
    /// Giá trị hao mòn lỹ kế TRUOC điều chỉnh
    /// </summary>
    public decimal CurrentAccumDepreciationAmount { get; set; }

    /// <summary>
    /// Giá trị hao mòn lỹ kế SAU điều chỉnh
    /// </summary>
    public decimal NewAccumDepreciationAmount { get; set; }

    /// <summary>
    /// Chênh lệch Hao mòn lũy kế
    /// </summary>
    public decimal DiffAccumDepreciationAmount { get; set; }

    /// <summary>
    /// TK chi phí
    /// </summary>
    public string? CostAccount { get; set; }

    /// <summary>
    /// Giá trị tính khấu hao TRƯỚC điều chỉnh
    /// </summary>
    public decimal CurrentDepreciationAmount { get; set; }

    /// <summary>
    /// Giá trị tính khấu hao SAU điều chỉnh
    /// </summary>
    public decimal NewDepreciationAmount { get; set; }

    /// <summary>
    /// Chênh lệch Giá trị tính khấu hao
    /// </summary>
    public decimal DiffDepreciationAmount { get; set; }

    /// <summary>
    /// TK đánh giá lại
    /// </summary>
    public string? AdjustmentAccount { get; set; }

    /// <summary>
    /// Giá trị tính khấu hao THÁNG Sau điều chỉnh
    /// </summary>
    public decimal NewMonthlyDepreciationAmount { get; set; }

    /// <summary>
    /// Giá trị tính khấu hao THÁNG Sau điều chỉnh theo luật thuế TNDN
    /// </summary>
    public decimal NewMonthlyDepreciationAmountByIncomeTax { get; set; }

    /// <summary>
    /// Thứ tự
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Chênh lệch thời gian sử dụng
    /// </summary>
    public decimal DiffLifeTime { get; set; }

    /// <summary>
    /// Chênh lệch giá trị tính khấu hao THÁNG Sau điều chỉnh
    /// </summary>
    public decimal DiffMonthlyDepreciationAmount { get; set; }

    public virtual Account? AdjustmentAccountNavigation { get; set; }

    public virtual Account? CostAccountNavigation { get; set; }

    public virtual FixedAsset FixedAsset { get; set; } = null!;

    public virtual OrganizationUnit OrganizationUnit { get; set; } = null!;

    public virtual Faadjustment Ref { get; set; } = null!;
}