// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết các thành viên tham gia kiểm kê
/// </summary>
public partial class FaauditMemberDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// RefID của Master
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Họ và tên
    /// </summary>
    public string? AccountObjectName { get; set; }

    /// <summary>
    /// Chức vụ
    /// </summary>
    public string? Position { get; set; }

    /// <summary>
    /// Đại diện
    /// </summary>
    public string? Representative { get; set; }

    /// <summary>
    /// Số thứ tự dòng
    /// </summary>
    public int SortOrder { get; set; }

    public virtual Faaudit Ref { get; set; } = null!;
}