// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết
/// </summary>
public partial class FachangeFinancialLeasingToOwnerDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// TK Nợ
    /// </summary>
    public string DebitAccount { get; set; }

    /// <summary>
    /// TK Có
    /// </summary>
    public string CreditAccount { get; set; }

    /// <summary>
    /// Số tiền
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Mã thống kê
    /// </summary>
    public Guid? ListItemId { get; set; }

    /// <summary>
    /// Số thứ tự dòng
    /// </summary>
    public int SortOrder { get; set; }

    public virtual Account CreditAccountNavigation { get; set; }

    public virtual Account DebitAccountNavigation { get; set; }

    public virtual FachangeFinancialLeasingToOwner Ref { get; set; }
}