// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class FadepreciationDetailPost
{
    public Guid RefDetailId { get; set; }

    public Guid RefId { get; set; }

    public string? Description { get; set; }

    public string? DebitAccount { get; set; }

    public string? CreditAccount { get; set; }

    public decimal Amount { get; set; }

    public Guid? DebitAccountObjectId { get; set; }

    public Guid? CreditAccountObjectId { get; set; }

    public Guid? ExpenseItemId { get; set; }

    public Guid? OrganizationUnitId { get; set; }

    public Guid? JobId { get; set; }

    public Guid? ProjectWorkId { get; set; }

    public Guid? OrderId { get; set; }

    public Guid? ContractId { get; set; }

    public bool UnResonableCost { get; set; }

    public Guid? ListItemId { get; set; }

    public int SortOrder { get; set; }

    public virtual Contract? Contract { get; set; }

    public virtual Account? CreditAccountNavigation { get; set; }

    public virtual AccountObject? CreditAccountObject { get; set; }

    public virtual Account? DebitAccountNavigation { get; set; }

    public virtual AccountObject? DebitAccountObject { get; set; }

    public virtual ExpenseItem? ExpenseItem { get; set; }

    public virtual Job? Job { get; set; }

    public virtual ListItem? ListItem { get; set; }

    public virtual Saorder? Order { get; set; }

    public virtual OrganizationUnit? OrganizationUnit { get; set; }

    public virtual ProjectWork? ProjectWork { get; set; }

    public virtual Fadepreciation Ref { get; set; } = null!;
}