// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Master Chứng từ ghi giảm TSCD
/// </summary>
public partial class Fadecrement
{
    /// <summary>
    /// PK phiếu ghi tăng, ghi giảm TSCĐ
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Loại chứng từ
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime? RefDate { get; set; }

    /// <summary>
    /// Ngày hoạch toán
    /// </summary>
    public DateTime? PostedDate { get; set; }

    /// <summary>
    /// Số chứng từ
    /// </summary>
    public string RefNo { get; set; } = null!;

    /// <summary>
    /// Lý do giảm
    /// </summary>
    public string? JournalMemo { get; set; }

    /// <summary>
    /// Giá trị còn lại
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// Ghi vào sổ tài chính
    /// </summary>
    public bool IsPostedFinance { get; set; }

    /// <summary>
    /// 0: Ghi giảm trên sổ Tài chính; 1: Ghi giảm trên sổ quản trị
    /// </summary>
    public int DisplayOnBook { get; set; }

    /// <summary>
    /// Phiên bản sửa
    /// </summary>
    public byte[]? EditVersion { get; set; }

    /// <summary>
    /// Số thứ tự nhập chứng từ
    /// </summary>
    public int RefOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    /// <summary>
    /// Ghi vào sổ quản trị
    /// </summary>
    public bool IsPostedManagement { get; set; }

    public virtual OrganizationUnit? Branch { get; set; }

    public virtual ICollection<FadecrementDetailPost> FadecrementDetailPosts { get; set; } = new List<FadecrementDetailPost>();

    public virtual ICollection<FadecrementDetail> FadecrementDetails { get; set; } = new List<FadecrementDetail>();
}