// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng chi tiết phân bổ khấu hao tscđ
/// </summary>
public partial class FadepreciationDetailAllocation
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Tài sản CĐ
    /// </summary>
    public Guid FixedAssetId { get; set; }

    /// <summary>
    /// Đơn vị sử dụng
    /// </summary>
    public Guid OrganizationUnitId { get; set; }

    /// <summary>
    /// Giá trị khấu hao tháng
    /// </summary>
    public decimal MonthlyDepreciationAmount { get; set; }

    /// <summary>
    /// Đối tượng phân bổ
    /// </summary>
    public Guid? AllocationObjectId { get; set; }

    /// <summary>
    /// TK chi phí
    /// </summary>
    public string? CostAccount { get; set; }

    /// <summary>
    /// Tỷ lệ %
    /// </summary>
    public decimal AllocationRate { get; set; }

    /// <summary>
    /// Chi phí phân bổ
    /// </summary>
    public decimal AllocationAmount { get; set; }

    public int SortOrder { get; set; }

    public Guid? ExpenseItemId { get; set; }

    public Guid? ListItemId { get; set; }

    public virtual Account? CostAccountNavigation { get; set; }

    public virtual ExpenseItem? ExpenseItem { get; set; }

    public virtual FixedAsset FixedAsset { get; set; } = null!;

    public virtual ListItem? ListItem { get; set; }

    public virtual OrganizationUnit OrganizationUnit { get; set; } = null!;

    public virtual Fadepreciation Ref { get; set; } = null!;
}