// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Frb03opndetailByActivity
{
    public string AccountNumber { get; set; }

    public bool? IsDebitBalance { get; set; }

    public decimal BussinessAmount { get; set; }

    public decimal InvestmentAmount { get; set; }

    public decimal FinancialAmount { get; set; }

    public bool IsPostToManagementBook { get; set; }

    public Guid BranchId { get; set; }
}