// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Frb09dnsnreportDetail
{
    public Guid ReportDetailId { get; set; }

    public Guid RefId { get; set; }

    public int? ItemIndex { get; set; }

    public Guid ItemId { get; set; }

    public string? ItemCode { get; set; }

    public string? ItemName { get; set; }

    public string? ItemNameEnglish { get; set; }

    public string? ItemNameChinese { get; set; }

    public string? ItemNameKorean { get; set; }

    public string? Part { get; set; }

    public int? PartInTab { get; set; }

    public int? FormulaType { get; set; }

    public string? Description { get; set; }

    public bool? Hidden { get; set; }

    public bool? IsBold { get; set; }

    public bool? IsItalic { get; set; }

    public string? Formula { get; set; }

    public decimal? ManagementToolSoftwareClosingAmount { get; set; }

    public decimal? BuildingEasementOpeningAmount { get; set; }

    public decimal? MachineIssueRightIncrementAmount { get; set; }

    public decimal? TransportLicenceDecrementAmount { get; set; }

    /// <summary>
    /// thứ tự sắp xếp 
    /// </summary>
    public int? SortOrder { get; set; }

    public virtual FrreportList Ref { get; set; } = null!;
}