// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu trữ việc chọn hoạt động cho các chứng từ (báo cáo B03)
/// </summary>
public partial class Frb03reportDetailActivity
{
    /// <summary>
    /// RefDetailID của chứng từ gốc
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// Hoạt động. 0=Hoạt động kinh doanh; 1= Hoạt động đầu tư; 2= Hoạt động tài chính
    /// </summary>
    public int? ActivityId { get; set; }

    public bool IsPostToManagementBook { get; set; }
}