// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Frb09dnsntemplate
{
    public Guid ItemId { get; set; }

    public int? ItemIndex { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public string ItemNameEnglish { get; set; }

    public string ItemNameChinese { get; set; }

    public string ItemNameKorean { get; set; }

    /// <summary>
    /// Thuộc phần
    /// </summary>
    public string Part { get; set; }

    /// <summary>
    /// Tab
    /// </summary>
    public int? PartInTab { get; set; }

    public bool? IsBold { get; set; }

    public bool? IsItalic { get; set; }

    /// <summary>
    /// Không in
    /// </summary>
    public bool? Hidden { get; set; }

    /// <summary>
    /// Loại chỉ tiêu: 0-Chi tiết, 1- Tổng hợp, 2- Tiêu đề, 3- Chú thích
    /// </summary>
    public int? FormulaType { get; set; }

    /// <summary>
    /// Thiết lập công thức cho các cột
    /// </summary>
    public string Formula { get; set; }

    /// <summary>
    /// Nội dung
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Đầu năm
    /// </summary>
    public string BuildingEasementOpening { get; set; }

    /// <summary>
    /// Cuối năm
    /// </summary>
    public string ManagementToolSoftwareClosing { get; set; }

    /// <summary>
    /// Số phải nộp trong năm
    /// </summary>
    public string MachineIssueRightIncrement { get; set; }

    /// <summary>
    /// Số đã thực nộp trong năm
    /// </summary>
    public string TransportLicenceDecrement { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }
}