// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Frf01reportDetail
{
    public Guid ReportDetailId { get; set; }

    public Guid RefId { get; set; }

    public string? AccountNumber { get; set; }

    public int? AccountCategoryKind { get; set; }

    public string? AccountName { get; set; }

    public bool IsParent { get; set; }

    public Guid? ParentId { get; set; }

    public int? Grade { get; set; }

    public int? SortOrder { get; set; }

    public decimal? OpeningDebitAmount { get; set; }

    public decimal? OpeningCreditAmount { get; set; }

    public decimal? DebitAmount { get; set; }

    public decimal? CreditAmount { get; set; }

    public decimal? ClosingDebitAmount { get; set; }

    public decimal? ClosingCreditAmount { get; set; }

    public int? AccountKind { get; set; }

    public Guid? AccountId { get; set; }

    public string? AccountNameEnglish { get; set; }

    public string? AccountNameChinese { get; set; }

    public string? AccountNameKorean { get; set; }

    public virtual FrreportList Ref { get; set; } = null!;
}