// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class FromeinvoiceDetail
{
    public Guid RefDetailId { get; set; }

    public Guid? RefId { get; set; }

    public string Description { get; set; }

    public string UnitName { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal UnitPriceAfterTax { get; set; }

    public decimal AmountOc { get; set; }

    public decimal Amount { get; set; }

    public decimal DiscountRate { get; set; }

    public decimal DiscountAmountOc { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal? Vatrate { get; set; }

    public decimal VatamountOc { get; set; }

    public decimal Vatamount { get; set; }

    public int SortOrder { get; set; }

    public string InventoryItemCode { get; set; }

    public bool IsPromotion { get; set; }

    public decimal AmountAfterTax { get; set; }

    public string LotNo { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string TransactionId { get; set; }

    public decimal? DeductionsTaxAmount { get; set; }

    public decimal? DeductionsTaxAmountOc { get; set; }

    public decimal? Vatrate406 { get; set; }

    public decimal? VatrateOther { get; set; }

    public bool IsTradeDiscount { get; set; }

    public string EngineNumber { get; set; }

    public string ChassisNumber { get; set; }

    public virtual Fromeinvoice Transaction { get; set; }
}