// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class HelthCompany
{
    public string? ItemId { get; set; }

    public string? ItemName { get; set; }

    public string? Meaningful { get; set; }

    public string? EvaluationGuide { get; set; }
}