// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class HistoryVoucher
{
    public Guid? OutwardRefDetailId { get; set; }

    public bool? IsPostToManagementBook { get; set; }

    public decimal? MainOutwardQuantity { get; set; }

    public decimal? OutwardAmount { get; set; }

    public Guid? InventoryItemId { get; set; }

    public Guid? StockId { get; set; }
}