// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ImportDictionary
{
    public Guid ImportDictionaryId { get; set; }

    public string? ColumnId { get; set; }

    public string ColumnName { get; set; } = null!;

    public string ColumnNameExcel { get; set; } = null!;

    public DateTime? CreatedDate { get; set; }
}