// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ImportCollection
{
    /// <summary>
    /// Khóa chính
    /// </summary>
    public Guid KeyId { get; set; }

    /// <summary>
    /// Key để phân biệt nhập khẩu nghiệp vụ nào
    /// </summary>
    public string KeyCode { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Tên bảng Master cần nhập khẩu
    /// </summary>
    public string MasterTableName { get; set; }

    /// <summary>
    /// Tên bảng Detail cần nhập khẩu
    /// </summary>
    public string DetailTableName { get; set; }

    /// <summary>
    /// Tên file mẫu
    /// </summary>
    public string TemplateFileName { get; set; }

    public virtual ICollection<ImportCollectionConfig> ImportCollectionConfigs { get; set; } = new List<ImportCollectionConfig>();
}