// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class IninwardOutwardList
{
    public Guid RefId { get; set; }

    public DateTime? RefDate { get; set; }

    public DateTime? CabarefDate { get; set; }

    public DateTime? CarefDate { get; set; }

    public DateTime? PostedDate { get; set; }

    public DateTime? CabapostedDate { get; set; }

    public DateTime? CapostedDate { get; set; }

    public int? RefType { get; set; }

    public string InvTemplateNo { get; set; }

    public string RefNoFinance { get; set; }

    public string InvSeries { get; set; }

    public string RefNoManagement { get; set; }

    public string CabarefNoManagement { get; set; }

    public string CarefNoFinance { get; set; }

    public string InvNo { get; set; }

    public string CabarefNoFinance { get; set; }

    public string CarefNoManagement { get; set; }

    public bool? IsPostedFinance { get; set; }

    public bool? IsPostedManagement { get; set; }

    public int? IncludeInvoice { get; set; }

    public Guid? SainvoiceRefId { get; set; }

    public Guid? PuinvoiceRefId { get; set; }

    public Guid? AccountObjectId { get; set; }

    public string OrderNo { get; set; }

    public string AccountObjectName { get; set; }

    public DateTime? OrderDate { get; set; }

    public string AccountObjectAddress { get; set; }

    public string ContactName { get; set; }

    public string ReceiverAddress { get; set; }

    public Guid? SareturnRefId { get; set; }

    public string AccountObjectBankAccount { get; set; }

    public int? UnitPriceMethod { get; set; }

    public string AccountObjectBankName { get; set; }

    public string OutDocumentIncluded { get; set; }

    public string AccountObjectContactName { get; set; }

    public string Payer { get; set; }

    public string IdentificationNumber { get; set; }

    public string PayerAddress { get; set; }

    public Guid? TransporterId { get; set; }

    public DateTime? IssueDate { get; set; }

    public string PayReason { get; set; }

    public string TransporterName { get; set; }

    public string CadocumentIncluded { get; set; }

    public string ContractCode { get; set; }

    public string IssueBy { get; set; }

    public bool? IsInvoiceExported { get; set; }

    public string Receiver { get; set; }

    public string Transport { get; set; }

    public Guid? FromStockId { get; set; }

    public string JournalMemo { get; set; }

    public Guid? ToStockId { get; set; }

    public string DocumentIncluded { get; set; }

    public Guid? EmployeeId { get; set; }

    public Guid? BranchId { get; set; }

    public string CabajournalMemo { get; set; }

    public string CabadocumentIncluded { get; set; }

    public Guid? BankAccountId { get; set; }

    public string BankName { get; set; }

    public Guid? PaymentTermId { get; set; }

    public int? DueTime { get; set; }

    public DateTime? PaymentDate { get; set; }

    public int? RevenueStatus { get; set; }

    public string CurrencyId { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? TotalAmountOc { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? TotalImportTaxAmountOc { get; set; }

    public decimal? TotalImportTaxAmount { get; set; }

    public decimal? TotalVatamountOc { get; set; }

    public decimal? TotalVatamount { get; set; }

    public decimal? TotalDiscountAmountOc { get; set; }

    public decimal? TotalDiscountAmount { get; set; }

    public decimal? TotalFreightAmount { get; set; }

    public decimal? TotalInwardAmount { get; set; }

    public decimal? TotalSpecialConsumeTaxAmountOc { get; set; }

    public decimal? TotalSpecialConsumeTaxAmount { get; set; }

    public decimal? TotalCustomBeforeAmount { get; set; }

    public int? DisplayOnBook { get; set; }

    public bool? IsPaid { get; set; }

    public bool? IsPostedCashBookFinance { get; set; }

    public bool? IsPostedCashBookManagement { get; set; }

    public DateTime? CashBookPostedDate { get; set; }

    public bool? IsPostedInventoryBookFinance { get; set; }

    public bool? IsPostedInventoryBookManagement { get; set; }

    public DateTime? InventoryPostedDate { get; set; }

    public int? RefOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    public string CustomField5 { get; set; }

    public string CustomField6 { get; set; }

    public string CustomField7 { get; set; }

    public string CustomField8 { get; set; }

    public string CustomField9 { get; set; }

    public string CustomField10 { get; set; }

    public int? Intype { get; set; }

    public string ListTableName { get; set; }

    public string RefTypeName { get; set; }

    public string RevenueStatusName { get; set; }

    public string CajournalMemo { get; set; }

    public decimal? TotalAmountFinance { get; set; }

    public decimal? TotalAmountManagement { get; set; }

    public decimal? CabaamountOc { get; set; }

    public decimal? Cabaamount { get; set; }

    public Guid? OutwardDependentRefId { get; set; }

    public Guid? AssemblyRefId { get; set; }

    public DateTime? InrefOrder { get; set; }

    public bool? IsSaleWithOutward { get; set; }

    /// <summary>
    /// Đã lập bán trả lại năm trước
    /// </summary>
    public bool IsCreatedSareturnLastYear { get; set; }

    public string RefIdmshop { get; set; }

    public string RefNoMshop { get; set; }

    public int InvoiceSystem { get; set; }

    public string InvoiceCode { get; set; }

    public bool IsProcessInvoiceError { get; set; }

    public string BranchImportName { get; set; }

    public string BranchImportMst { get; set; }

    public string FromStockAddress { get; set; }

    public string ToStockAddress { get; set; }
}