// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng master Lệnh sản xuất
/// </summary>
public partial class InproductionOrder
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã chi nhánh
    /// </summary>
    public Guid BranchId { get; set; }

    /// <summary>
    /// 212 = Lệnh sản xuất
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Số lệnh sản xuất
    /// </summary>
    public string RefNo { get; set; }

    /// <summary>
    /// Từ ngày
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// 0 = Chưa thực hiện; 1 = Đang thực hiện; 2 = Tạm dừng; 3 = Hoàn thành; 4 = Đã hủy bỏ
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// Phiên bản sửa chứng từ
    /// </summary>
    public byte[] EditVersion { get; set; }

    /// <summary>
    /// Số thứ tự nhập chứng từ
    /// </summary>
    public int RefOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsInwardDone { get; set; }

    public bool IsOutwardDone { get; set; }

    public string Description { get; set; }

    public virtual ICollection<IninvoiceHubOutwardDetail> IninvoiceHubOutwardDetails { get; set; } = new List<IninvoiceHubOutwardDetail>();

    public virtual ICollection<IninwardDetail> IninwardDetails { get; set; } = new List<IninwardDetail>();

    public virtual ICollection<InoutwardDetail> InoutwardDetails { get; set; } = new List<InoutwardDetail>();

    public virtual ICollection<InproductionOrderProduct> InproductionOrderProducts { get; set; } = new List<InproductionOrderProduct>();

    public virtual ICollection<PuorderDetail> PuorderDetails { get; set; } = new List<PuorderDetail>();

    public virtual ICollection<PureturnDetail> PureturnDetails { get; set; } = new List<PureturnDetail>();

    public virtual ICollection<PuvoucherDetail> PuvoucherDetails { get; set; } = new List<PuvoucherDetail>();
}