// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng master chứng từ chuyển kho
/// </summary>
public partial class Intransfer
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// ID của chi nhánh.
    /// </summary>
    public Guid BranchId { get; set; }

    /// <summary>
    /// Xác định chứng từ được ghi vào sổ nào (0=Sổ tài chinh;1=Sổ quản trị;2=Cả hai)
    /// </summary>
    public int DisplayOnBook { get; set; }

    /// <summary>
    /// 230 = Xuất kho kiêm vận chuyển nội bộ; 231 = Xuất kho gửi bán đại lý; 232 = Xuất chuyển kho nội bộ
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// Ngày hạch toán
    /// </summary>
    public DateTime PostedDate { get; set; }

    /// <summary>
    /// Số chứng từ Sổ tài chính
    /// </summary>
    public string? RefNoFinance { get; set; }

    /// <summary>
    /// Số chứng từ Sổ quản trị
    /// </summary>
    public string? RefNoManagement { get; set; }

    /// <summary>
    /// Mẫu số
    /// </summary>
    public string? InvTemplateNo { get; set; }

    /// <summary>
    /// Ký hiệu
    /// </summary>
    public string? InvSeries { get; set; }

    /// <summary>
    /// Xuất kho gửi bán đại lý/Xuất kho kiêm vận chuyển nội bộ
    /// </summary>
    public string? InvNo { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ Sổ tài chính
    /// </summary>
    public bool IsPostedFinance { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ Sổ quản trị
    /// </summary>
    public bool IsPostedManagement { get; set; }

    /// <summary>
    /// Hợp đồng kinh tế/Lệnh điều động
    /// </summary>
    public string? ContractCode { get; set; }

    /// <summary>
    /// Ngày hợp đồng/Điều động
    /// </summary>
    public DateTime? ContractDate { get; set; }

    /// <summary>
    /// Hợp đồng/Lệnh điều động của
    /// </summary>
    public string? ContractOwner { get; set; }

    /// <summary>
    /// Với đại lý/Về việc
    /// </summary>
    public string? JournalMemo { get; set; }

    /// <summary>
    /// Mã số thuế
    /// </summary>
    public string? CompanyTaxCode { get; set; }

    /// <summary>
    /// Mã Người vận chuyển
    /// </summary>
    public Guid? TransporterId { get; set; }

    /// <summary>
    /// Tên người vận chuyển
    /// </summary>
    public string? TransporterName { get; set; }

    /// <summary>
    /// Hợp đồng vận chuyển
    /// </summary>
    public string? TransportContractCode { get; set; }

    /// <summary>
    /// Phương tiện vận chuyển
    /// </summary>
    public string? Transport { get; set; }

    /// <summary>
    /// Tổng thành tiền Sổ tài chính
    /// </summary>
    public decimal TotalAmountFinance { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ thủ kho (Sổ tài chính)
    /// </summary>
    public bool? IsPostedInventoryBookFinance { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ thủ kho (Sổ quản trị)
    /// </summary>
    public bool? IsPostedInventoryBookManagement { get; set; }

    /// <summary>
    /// Ngày ghi sổ kho
    /// </summary>
    public DateTime? InventoryPostedDate { get; set; }

    /// <summary>
    /// Phiên bản sửa chứng từ
    /// </summary>
    public byte[]? EditVersion { get; set; }

    /// <summary>
    /// Số thứ tự nhập chứng từ
    /// </summary>
    public int RefOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? CustomField1 { get; set; }

    public string? CustomField2 { get; set; }

    public string? CustomField3 { get; set; }

    public string? CustomField4 { get; set; }

    public string? CustomField5 { get; set; }

    public string? CustomField6 { get; set; }

    public string? CustomField7 { get; set; }

    public string? CustomField8 { get; set; }

    public string? CustomField9 { get; set; }

    public string? CustomField10 { get; set; }

    /// <summary>
    /// Tổng thành tiền Sổ quản trị
    /// </summary>
    public decimal TotalAmountManagement { get; set; }

    public DateTime InrefOrder { get; set; }

    public Guid? AccountObjectId { get; set; }

    public bool? IsBranchIssued { get; set; }

    public string? AccountObjectName { get; set; }

    public bool IsAttachList { get; set; }

    public string? ListNo { get; set; }

    public DateTime? ListDate { get; set; }

    public string? CommonInventoryName { get; set; }

    public bool IsInvoiceReplace { get; set; }

    public string? RefIdmshop { get; set; }

    public string? RefNoMshop { get; set; }

    public bool? IsGetForInvoice { get; set; }

    public int InvoiceSystem { get; set; }

    public string? InvoiceCode { get; set; }

    public bool IsProcessInvoiceError { get; set; }

    public virtual OrganizationUnit Branch { get; set; } = null!;

    public virtual ICollection<IntransferDetail> IntransferDetails { get; set; } = new List<IntransferDetail>();

    public virtual AccountObject? Transporter { get; set; }
}