// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InventoryItemLogUnPost
{
    public Guid LogId { get; set; }

    /// <summary>
    /// Tên máy tính đăng nhập
    /// </summary>
    public string ComputerName { get; set; } = null!;

    /// <summary>
    /// Địa chỉ IP máy tính đăng nhập
    /// </summary>
    public string ComputerIp { get; set; } = null!;

    /// <summary>
    /// Tên đăng nhập
    /// </summary>
    public string LoginName { get; set; } = null!;

    /// <summary>
    /// Ngày hạch toán
    /// </summary>
    public DateTime PostedDate { get; set; }

    /// <summary>
    /// Thời gian xảy ra  bỏ ghi sổ hoặc ghi sổ
    /// </summary>
    public DateTime DatetimeAction { get; set; }

    /// <summary>
    /// =1: Bỏ ghi sổ ; = 2: Ghi sổ 
    /// </summary>
    public int ActionTypeId { get; set; }

    /// <summary>
    /// Phân hệ
    /// </summary>
    public string? ApplicationPartAlias { get; set; }

    /// <summary>
    /// Tham chiếu
    /// </summary>
    public string? Reference { get; set; }

    /// <summary>
    /// Mã chứng từ
    /// </summary>
    public Guid? RefId { get; set; }

    /// <summary>
    /// Loại chứng từ
    /// </summary>
    public int? RefType { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime? RefDate { get; set; }

    /// <summary>
    /// Thời gian ghi chứng từ
    /// </summary>
    public DateTime? InrefOrder { get; set; }

    /// <summary>
    /// UserID thực hiện
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Mã chi nhánh
    /// </summary>
    public Guid BranchId { get; set; }

    public string? ReferenceManagement { get; set; }

    /// <summary>
    /// =1: làm việc trên sổ quản trị;
    /// =0 : làm việc trên sổ tài chinh;
    /// 
    /// </summary>
    public bool IsWorkingWithManagementBook { get; set; }

    /// <summary>
    /// Mã dòng vật tư trong chứng từ tương ứng trong table Detail
    /// </summary>
    public Guid? RefDetailId { get; set; }

    /// <summary>
    /// Mã vật tư
    /// </summary>
    public Guid? InventoryItemId { get; set; }

    /// <summary>
    /// Số chứng từ
    /// </summary>
    public string? RefNo { get; set; }
}