// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu đơn vị chuyển đổi
/// </summary>
public partial class InventoryItemUnitConvert
{
    /// <summary>
    /// PK Vật tư
    /// </summary>
    public Guid InventoryItemUnitConvertId { get; set; }

    /// <summary>
    /// FK Vật tư
    /// </summary>
    public Guid InventoryItemId { get; set; }

    /// <summary>
    /// Số thứ tự
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Đơn vị chuyển đổi
    /// </summary>
    public Guid UnitId { get; set; }

    /// <summary>
    /// Tỷ lệ chuyển đổi về đơn vị chính
    /// </summary>
    public decimal ConvertRate { get; set; }

    /// <summary>
    /// Phép tính chuyển đổi
    /// </summary>
    public string ExchangeRateOperator { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Đơn giá bán 1
    /// </summary>
    public decimal SalePrice1 { get; set; }

    /// <summary>
    /// Đơn giá bán 2
    /// </summary>
    public decimal SalePrice2 { get; set; }

    /// <summary>
    /// Đơn giá bán 3
    /// </summary>
    public decimal SalePrice3 { get; set; }

    /// <summary>
    /// Giá bán cố định
    /// </summary>
    public decimal FixedSalePrice { get; set; }

    public virtual InventoryItem InventoryItem { get; set; }

    public virtual Unit Unit { get; set; }
}