// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Sổ chi tiết vật tư (không cần dùng InventoryBalance)
/// </summary>
public partial class InventoryLedger
{
    /// <summary>
    /// PK - Sổ chi tiết vật tư
    /// </summary>
    public int InventoryLedgerId { get; set; }

    /// <summary>
    /// RefID của chứng từ gốc
    /// </summary>
    public Guid? RefId { get; set; }

    /// <summary>
    /// RefDetailID của chúng từ gốc
    /// </summary>
    public Guid? RefDetailId { get; set; }

    /// <summary>
    /// Loại chứng từ
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Số chứng từ Sổ tài chính
    /// </summary>
    public string RefNo { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// Ngày hạch toán
    /// </summary>
    public DateTime PostedDate { get; set; }

    /// <summary>
    /// TK Nợ
    /// </summary>
    public string AccountNumber { get; set; }

    /// <summary>
    /// TK Có
    /// </summary>
    public string CorrespondingAccountNumber { get; set; }

    /// <summary>
    /// Kho
    /// </summary>
    public Guid? StockId { get; set; }

    /// <summary>
    /// Vật tư
    /// </summary>
    public Guid? InventoryItemId { get; set; }

    /// <summary>
    /// ĐVT
    /// </summary>
    public Guid? UnitId { get; set; }

    /// <summary>
    /// Đơn giá (Sổ tài chính)
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Số lượng nhập kho
    /// </summary>
    public decimal? InwardQuantity { get; set; }

    /// <summary>
    /// Số lượng xuất kho
    /// </summary>
    public decimal? OutwardQuantity { get; set; }

    /// <summary>
    /// Giá trị nhập kho (Sổ tài chính)
    /// </summary>
    public decimal InwardAmount { get; set; }

    /// <summary>
    /// Giá trị xuât kho (Sổ tài chính)
    /// </summary>
    public decimal OutwardAmount { get; set; }

    /// <summary>
    /// Số lượng tồn trên chứng từ nhập kho (dùng cho phương pháp NTXT và đích danh)
    /// </summary>
    public decimal InwardQuantityBalance { get; set; }

    /// <summary>
    /// Giá trị tồn trên chứng từ nhập kho (dùng cho phương pháp NTXT và đích danh) (Sổ tài chính)
    /// </summary>
    public decimal InwardAmountBalance { get; set; }

    /// <summary>
    /// Diễn giải master
    /// </summary>
    public string JournalMemo { get; set; }

    /// <summary>
    /// Diễn giải detail
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Ngày hết hạn
    /// </summary>
    public DateTime? ExpiryDate { get; set; }

    /// <summary>
    /// Số lô
    /// </summary>
    public string LotNo { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// ĐVT
    /// </summary>
    public Guid? MainUnitId { get; set; }

    /// <summary>
    /// Đơn giá
    /// </summary>
    public decimal MainUnitPrice { get; set; }

    /// <summary>
    /// Số lượng nhập kho
    /// </summary>
    public decimal MainInwardQuantity { get; set; }

    /// <summary>
    /// Số lượng xuất kho
    /// </summary>
    public decimal MainOutwardQuantity { get; set; }

    /// <summary>
    /// Tỷ lệ chuyển đổi ra đơn vị chính
    /// </summary>
    public decimal MainConvertRate { get; set; }

    /// <summary>
    /// Toán tử quy đổi *=nhân;/=chia
    /// </summary>
    public string ExchangeRateOperator { get; set; }

    /// <summary>
    /// 1=Là hàng khuyến mại;0=không phải là hàng khuyến mại
    /// </summary>
    public bool IsPromotion { get; set; }

    /// <summary>
    /// Trạng thái ghi vào vào sổ quản trị
    /// </summary>
    public bool IsPostToManagementBook { get; set; }

    /// <summary>
    /// Dùng để sắp xếp các chứng từ nào insert vào trước sau chứng từ nào Insert vào sau
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// Thứ tự của chứng từ
    /// </summary>
    public int? RefOrder { get; set; }

    /// <summary>
    /// Số chứng từ nhập đối trừ (Áp dụng cho PP đích danh)
    /// </summary>
    public Guid? ConfrontingRefId { get; set; }

    /// <summary>
    /// Số chứng từ nhập đối trừ (Áp dụng cho PP đích danh)
    /// </summary>
    public Guid? ConfrontingRefDetailId { get; set; }

    /// <summary>
    /// Ko cập nhật giá xuất (Áp dụng cho bán đại lý, mua trả lại, giảm giá, điều chỉnh giảm GT, ...)
    /// </summary>
    public bool IsUnUpdateOutwardPrice { get; set; }

    /// <summary>
    /// Mã kho
    /// </summary>
    public string StockCode { get; set; }

    /// <summary>
    /// Tên kho
    /// </summary>
    public string StockName { get; set; }

    /// <summary>
    /// Mã vật tư, hàng hóa
    /// </summary>
    public string InventoryItemCode { get; set; }

    /// <summary>
    /// Tên vật tư, hàng hóa
    /// </summary>
    public string InventoryItemName { get; set; }

    /// <summary>
    /// Tên tài khoản
    /// </summary>
    public string AccountName { get; set; }

    /// <summary>
    /// ID Đơn hàng
    /// </summary>
    public Guid? OrderId { get; set; }

    /// <summary>
    /// Mã thống kê
    /// </summary>
    public Guid? ListItemId { get; set; }

    /// <summary>
    /// ID đơn vị
    /// </summary>
    public Guid? OrganizationUnitId { get; set; }

    /// <summary>
    /// Hợp đồng
    /// </summary>
    public Guid? ContractId { get; set; }

    /// <summary>
    /// Mã hợp đồng
    /// </summary>
    public string ContractCode { get; set; }

    /// <summary>
    /// Tên hợp đồng
    /// </summary>
    public string ContractName { get; set; }

    /// <summary>
    /// Công trình/Dự án
    /// </summary>
    public Guid? ProjectWorkId { get; set; }

    /// <summary>
    /// Công việc
    /// </summary>
    public Guid? JobId { get; set; }

    /// <summary>
    /// Khoản mục chi phí
    /// </summary>
    public Guid? ExpenseItemId { get; set; }

    /// <summary>
    /// Nhân viên
    /// </summary>
    public Guid? EmployeeId { get; set; }

    /// <summary>
    /// Mã nhân viên
    /// </summary>
    public string EmployeeCode { get; set; }

    /// <summary>
    /// Tên nhân viên
    /// </summary>
    public string EmployeeName { get; set; }

    /// <summary>
    /// Người nhận tiền/Người chi tiền
    /// </summary>
    public string ContactName { get; set; }

    /// <summary>
    /// Đối tượng hạch toán kế toán
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Mã đối tượng
    /// </summary>
    public string AccountObjectCode { get; set; }

    /// <summary>
    /// Tên đối tượng
    /// </summary>
    public string AccountObjectName { get; set; }

    /// <summary>
    /// Địa chỉ
    /// </summary>
    public string AccountObjectAddress { get; set; }

    /// <summary>
    /// RefID của lệnh sản xuất
    /// </summary>
    public Guid? ProductionOrderRefId { get; set; }

    /// <summary>
    /// Có cần cập nhật dữ liệu từ các bảng dư thừa sang không, 0: không, 1: có. Sau khi cập nhật xong thì thiết lập thông tin này về =0
    /// </summary>
    public bool? IsUpdateRedundant { get; set; }

    /// <summary>
    /// Tên đối tượng ( lấy từ danh mục)
    /// </summary>
    public string AccountObjectNameDi { get; set; }

    public string RefTypeName { get; set; }

    public int UnUpdateOutwardPriceType { get; set; }

    public int InOutWardType { get; set; }

    public int? UnitPriceMethod { get; set; }

    public Guid? OutwardRefId { get; set; }

    public Guid? OutwardRefDetailId { get; set; }

    public Guid? AssemblyRefId { get; set; }

    public Guid? ProductionId { get; set; }

    public DateTime InrefOrder { get; set; }

    public string CurrencyId { get; set; }

    public decimal ExchangeRate { get; set; }

    public bool? IsInward { get; set; }

    public int? InventoryResaleTypeId { get; set; }

    public string RefNoFinance { get; set; }

    public string RefNoManagement { get; set; }

    public Guid? PucontractId { get; set; }

    public string PucontractCode { get; set; }

    public string PucontractName { get; set; }

    /// <summary>
    /// Tổng lũy kế số lượng nhập kho theo ĐV tính chính , tính đến thời gian hạch toán của phiếu nhập,  tính cả dòng hiện tại
    /// </summary>
    public decimal? FifoaccumInwardQuantityMainUnitAfterRow { get; set; }

    /// <summary>
    /// Tổng lũy kế số lượng xuất kho theo ĐV tính chính , tính đến trước thời gian hạch toán của phiếu xuất (  không tính  dòng hiện tại)
    /// </summary>
    public decimal? FifoaccumOutwardQuantityMainUnitAfterRow { get; set; }

    /// <summary>
    /// InventoryLedgerID của dòng nhập kho đầu tiên phân bổ cho một phiếu xuất
    /// </summary>
    public int? FifoinventoryLedgerIdfirstInwardForAllocate { get; set; }

    /// <summary>
    /// Tổng nhập lũy kế amount sau row nhập hiện tại tại ( so sánh theo thời gian hạch toán)
    /// </summary>
    public decimal? FifoaccumInwardAmountMainUnitAfterRow { get; set; }

    /// <summary>
    /// Tổng xuất lũy kế amount  sau row xuất hiện tại tại ( so sánh theo thời gian hạch toán)
    /// </summary>
    public decimal? FifoaccumOutwardAmountMainUnitAfterRow { get; set; }

    public DateTime? FifoaccumLastUpdate { get; set; }

    public Guid? LoanagreementId { get; set; }
}