// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InventoryItemCategorySpecialTaxDetail
{
    public string InventoryCategorySpecialTaxCode { get; set; }

    public string InventoryCategorySpecialTaxName { get; set; }

    public string Unit { get; set; }

    public decimal TaxRate { get; set; }

    public DateTime? Fromdate { get; set; }

    public DateTime? Todate { get; set; }
}