// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InventoryItemPriceFifotransfer
{
    public Guid InventoryItemFifotransferId { get; set; }

    public Guid CalculateId { get; set; }

    public int InventoryLedgerId { get; set; }

    public decimal MainUnitPrice { get; set; }

    public Guid RefDetailId { get; set; }

    public bool IsInward { get; set; }

    public DateTime? DatetimeInsert { get; set; }

    public decimal Amount { get; set; }
}