// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InventoryLogAction
{
    public Guid IdLog { get; set; }

    public string? LogContent { get; set; }

    public DateTime? DateLog { get; set; }
}