// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InventoryItemPriceFifoassembly
{
    public Guid InventoryItemFifoassemblyId { get; set; }

    public Guid CalculateId { get; set; }

    public int InventoryLedgerIdproduct { get; set; }

    public decimal MainUnitPrice { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal AmountProduct { get; set; }

    public Guid AssemblyRefId { get; set; }

    public DateTime DatetimeInsert { get; set; }
}