// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InvestmentProject
{
    public Guid InvestmentProjectId { get; set; }

    public string InvestmentProjectCode { get; set; }

    public string InvestmentProjectName { get; set; }

    public string MakingAddress { get; set; }

    public string OwnerTaxCode { get; set; }

    public string OwnerName { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public decimal? InvestmentAmount { get; set; }

    public string CurrencyId { get; set; }

    public string DocurmentCode { get; set; }

    public DateTime DateIssued { get; set; }

    public string AgencyIssued { get; set; }

    public string Note { get; set; }

    public bool? Inactive { get; set; }

    public Guid? BranchId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public string Country { get; set; }

    public string ProvinceOrCity { get; set; }

    public string District { get; set; }

    public string WardOrCommune { get; set; }

    public virtual ICollection<BawithdrawDetailImportMultiTax> BawithdrawDetailImportMultiTaxes { get; set; } = new List<BawithdrawDetailImportMultiTax>();

    public virtual ICollection<BawithdrawDetailImportVat> BawithdrawDetailImportVats { get; set; } = new List<BawithdrawDetailImportVat>();

    public virtual ICollection<BawithdrawDetailTax> BawithdrawDetailTaxes { get; set; } = new List<BawithdrawDetailTax>();

    public virtual OrganizationUnit Branch { get; set; }

    public virtual ICollection<CapaymentDetailImportMultiTax> CapaymentDetailImportMultiTaxes { get; set; } = new List<CapaymentDetailImportMultiTax>();

    public virtual ICollection<CapaymentDetailImportVat> CapaymentDetailImportVats { get; set; } = new List<CapaymentDetailImportVat>();

    public virtual ICollection<CapaymentDetailTax> CapaymentDetailTaxes { get; set; } = new List<CapaymentDetailTax>();

    public virtual Ccy Currency { get; set; }

    public virtual ICollection<GlvoucherDetailTax> GlvoucherDetailTaxes { get; set; } = new List<GlvoucherDetailTax>();

    public virtual ICollection<GlvoucherDetail> GlvoucherDetails { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<PudiscountDetail> PudiscountDetails { get; set; } = new List<PudiscountDetail>();

    public virtual ICollection<PuinvoiceDetail> PuinvoiceDetails { get; set; } = new List<PuinvoiceDetail>();

    public virtual ICollection<PureturnDetail> PureturnDetails { get; set; } = new List<PureturnDetail>();

    public virtual ICollection<PuserviceDetail> PuserviceDetails { get; set; } = new List<PuserviceDetail>();

    public virtual ICollection<PuvoucherDetail> PuvoucherDetails { get; set; } = new List<PuvoucherDetail>();

    public virtual ICollection<SareturnDetail> SareturnDetails { get; set; } = new List<SareturnDetail>();
}