// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InvoiceBotCheckingStatus
{
    public Guid InvoiceBotCheckingStatusId { get; set; }

    public string Id { get; set; }

    public string Indicator { get; set; }

    public string Status { get; set; }

    public string StatusCode { get; set; }

    public string StatusInformation { get; set; }

    public virtual InvoiceBot IdNavigation { get; set; }
}