// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InvoiceNotification
{
    public Guid Id { get; set; }

    public DateTime RefDate { get; set; }

    public string TransactionId { get; set; } = null!;

    public string MessageCode { get; set; } = null!;

    public int NotificationType { get; set; }

    public string ContentValue { get; set; } = null!;

    public string? UserHasVisited { get; set; }

    public string? TaxCode { get; set; }
}