// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InvoiceTemplate
{
    public Guid InvoiceTemplateId { get; set; }

    public string InvoiceTemplateName { get; set; }

    public string InvoiceTemplateFileName { get; set; }

    public string InvTypeCode { get; set; }

    public bool IsDefault { get; set; }

    public int? CompanyId { get; set; }

    public bool IsPublic { get; set; }

    public int SortOrder { get; set; }

    public byte[] TemplateContent { get; set; }

    public bool? IsSynced { get; set; }

    public byte[] FilePdfsigned { get; set; }
}