// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class InvoiceErrorAnnouncement
{
    public Guid RefId { get; set; }

    public string RefNo { get; set; }

    public int? RefType { get; set; }

    public DateTime? RefDate { get; set; }

    public int? Status { get; set; }

    public int? CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string CompanyTaxCode { get; set; }

    public string MessageCode { get; set; }

    public DateTime? ReceiveRefDate { get; set; }

    public string ReceiveRefNo { get; set; }

    public Guid? TaxRefId { get; set; }

    public string TaxRefNo { get; set; }

    public DateTime? TaxRefDate { get; set; }

    public string TaxOrganManagementCode { get; set; }

    public string TaxOrganManagement { get; set; }

    public string XmlContent { get; set; }

    public string CreatedPlace { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual ICollection<InvoiceErrorAnnouncementDetail> InvoiceErrorAnnouncementDetails { get; set; } = new List<InvoiceErrorAnnouncementDetail>();
}