// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class IpdeletedAnnouncement
{
    public Guid RefId { get; set; }

    public DateTime RefDate { get; set; }

    public string RefNo { get; set; }

    public int RefType { get; set; }

    public DateTime? MinutesDate { get; set; }

    public string MinutesNo { get; set; }

    public string MinutesReason { get; set; }

    public string MinutesFileName { get; set; }

    public byte[] MinutesFileContent { get; set; }

    public Guid? SainvoiceRefId { get; set; }

    public int? SainvoiceRefType { get; set; }

    public string InvNo { get; set; }

    public DateTime? InvDate { get; set; }

    public string InvTemplateNo { get; set; }

    public string InvSeries { get; set; }

    public string AccountObjectCode { get; set; }

    public string AccountObjectName { get; set; }

    public string AccountObjectAddress { get; set; }

    public decimal? Amount { get; set; }

    public Guid? BranchId { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public byte[] EditVersion { get; set; }

    public int InvTypeId { get; set; }

    public Guid? IpvoucherRefId { get; set; }

    public bool? IncludeInvoice { get; set; }

    public bool? IsSendEmail { get; set; }

    public bool? IsSendDeletedInvoiceEmail { get; set; }

    public string DeletedReason { get; set; }

    public bool? IsSubmittedToTaxAuthories { get; set; }

    public DateTime? MeInvoiceSyncDateTime { get; set; }

    public bool IsOutBot { get; set; }

    public virtual OrganizationUnit Branch { get; set; }
}