// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// (Lost, Burn, Damaged) Mất, cháy, hỏng hóa đơn
/// </summary>
public partial class IplbdannouncementDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mẫu hóa đơn khởi tạo được chọn
    /// </summary>
    public Guid? IptemplateId { get; set; }

    /// <summary>
    /// Loại hóa đơn: 1.Hóa đơn giá trị gia tăng; 2.Hóa đơn bán hàng; 3.Phiếu xuất kho kiêm vận chuyển hàng hóa nội bộ; 4.Phiếu xuất kho gửi bán hàng đại lý; 5.Hóa đơn xuất khấu; 6.Hóa đơn bán hàng (dành cho tổ chức, cá nhân trong khu phi thuế quan)
    /// </summary>
    public int InvTypeId { get; set; }

    /// <summary>
    /// Mẫu số hóa đơn
    /// </summary>
    public string InvTemplateNo { get; set; } = null!;

    /// <summary>
    /// Ký hiệu hóa đơn
    /// </summary>
    public string InvSeries { get; set; } = null!;

    /// <summary>
    /// Từ số
    /// </summary>
    public string FromNo { get; set; } = null!;

    /// <summary>
    /// Đến số
    /// </summary>
    public string ToNo { get; set; } = null!;

    /// <summary>
    /// Số lượng
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// Liên hóa đơn
    /// </summary>
    public string? CopyPart { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string? Description { get; set; }

    public int? SortOrder { get; set; }

    public virtual InvType InvType { get; set; } = null!;

    public virtual Iptemplate? Iptemplate { get; set; }

    public virtual Iplbdannouncement Ref { get; set; } = null!;
}