// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng kê hóa đơn chưa sử dụng chuyển địa điểm kinh doanh khác địa bàn
/// </summary>
public partial class IplistInvoiceAttachment
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Loại hóa đơn: 1.Hóa đơn giá trị gia tăng; 2.Hóa đơn bán hàng; 3.Phiếu xuất kho kiêm vận chuyển hàng hóa nội bộ; 4.Phiếu xuất kho gửi bán hàng đại lý; 5.Hóa đơn xuất khấu; 6.Hóa đơn bán hàng (dành cho tổ chức, cá nhân trong khu phi thuế quan)
    /// </summary>
    public int InvTypeId { get; set; }

    /// <summary>
    /// Mẫu số hóa đơn
    /// </summary>
    public string InvTemplateNo { get; set; }

    /// <summary>
    /// Ký hiệu hóa đơn
    /// </summary>
    public string InvSeries { get; set; }

    /// <summary>
    /// Từ số
    /// </summary>
    public string FromNo { get; set; }

    /// <summary>
    /// Đến số
    /// </summary>
    public string ToNo { get; set; }

    /// <summary>
    /// Số lượng
    /// </summary>
    public int Quantity { get; set; }

    public int? SortOrder { get; set; }

    public virtual IpadjustAnnouncement Ref { get; set; }
}