// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class IpregisterEinvoiceDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Tên tổ chức cơ quan chứng thực, cấp, công nhận chữ ký số, điện tử
    /// </summary>
    public string OrganizationRecognizedSignal { get; set; }

    /// <summary>
    /// Số seri chứng thư số
    /// </summary>
    public string SerialNumberOfDeed { get; set; }

    /// <summary>
    /// Thời gian sử dụng của chứng thư số: Từ ngày
    /// </summary>
    public DateOnly? FromDateOfDeed { get; set; }

    /// <summary>
    /// Thời gian sử dụng của chứng thư số: Đến ngày
    /// </summary>
    public DateOnly? ToDateOfDeed { get; set; }

    /// <summary>
    /// Hình thức đăng ký: 1: Thêm mới, 2: gia hạn, 3: ngừng sử dụng
    /// </summary>
    public string RegistrationForm { get; set; }

    public decimal? SortOrder { get; set; }

    public virtual IpregisterEinvoice Ref { get; set; }
}