// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Phân bổ chi phí bán hàng và chi phí quản lý doanh nghiệp cho công trình
/// </summary>
public partial class JcallocationExpense
{
    public Guid RefId { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid BranchId { get; set; }

    /// <summary>
    /// Loại chứng từ
    /// </summary>
    public int? RefType { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// Số chứng từ
    /// </summary>
    public string RefNo { get; set; } = null!;

    /// <summary>
    /// từ ngày
    /// </summary>
    public DateTime? FromDate { get; set; }

    /// <summary>
    /// Đến ngày
    /// </summary>
    public DateTime? ToDate { get; set; }

    /// <summary>
    /// Kỳ phân bổ
    /// </summary>
    public string? PeriodDescription { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string? JournalMemo { get; set; }

    /// <summary>
    /// Tiêu thức phân bổ: 0=Doanh thu
    /// </summary>
    public int AllocationMethod { get; set; }

    /// <summary>
    /// 0=Sổ tài chinh;1=Sổ quản trị
    /// </summary>
    public int DisplayOnBook { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public int AllocationType { get; set; }

    public virtual OrganizationUnit Branch { get; set; } = null!;

    public virtual ICollection<JcallocationExpenseDetailTable> JcallocationExpenseDetailTables { get; set; } = new List<JcallocationExpenseDetailTable>();

    public virtual ICollection<JcallocationExpenseDetail> JcallocationExpenseDetails { get; set; } = new List<JcallocationExpenseDetail>();
}