// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu trữ kết quả phân bổ chi phí chung
/// </summary>
public partial class JccostAllocationDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// ID của JCPeriodDetail
    /// </summary>
    public Guid JcperiodDetailId { get; set; }

    /// <summary>
    /// FK - ID kỳ tính giá thành
    /// </summary>
    public Guid JcperiodId { get; set; }

    /// <summary>
    /// Đối tượng THCP
    /// </summary>
    public Guid? JobId { get; set; }

    /// <summary>
    /// Công trình/vụ việc
    /// </summary>
    public Guid? ProjectWorkId { get; set; }

    /// <summary>
    /// Đơn đặt hàng
    /// </summary>
    public Guid? OrderId { get; set; }

    /// <summary>
    /// Hợp đồng
    /// </summary>
    public Guid? ContractId { get; set; }

    /// <summary>
    /// TK chi phí (QĐ 15)
    /// </summary>
    public string AccountNumber { get; set; }

    /// <summary>
    /// Khoản mục CP (QĐ 48)
    /// </summary>
    public Guid? ExpenseItemId { get; set; }

    /// <summary>
    /// Tỷ lệ phân bổ (%)
    /// </summary>
    public decimal AllocationRate { get; set; }

    /// <summary>
    /// Số tiền phân bổ
    /// </summary>
    public decimal AllocationAmount { get; set; }

    /// <summary>
    /// 0=Sổ tài chinh;1=Sổ quản trị
    /// </summary>
    public int DisplayOnBook { get; set; }

    public int AllocationMethod { get; set; }

    public bool? IsAllocation { get; set; }

    public bool UnResonableCost { get; set; }

    public virtual Account AccountNumberNavigation { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual ExpenseItem ExpenseItem { get; set; }

    public virtual JcperiodDetail JcperiodDetail { get; set; }

    public virtual Job Job { get; set; }

    public virtual Saorder Order { get; set; }

    public virtual ProjectWork ProjectWork { get; set; }
}