// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Nhập đầu kỳ ĐT THCP, công trình, vụ việc, đơn hàng, hợp đồng
/// </summary>
public partial class Jcopn
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid BranchId { get; set; }

    /// <summary>
    /// Công trình, vụ việc
    /// </summary>
    public Guid? ProjectWorkId { get; set; }

    /// <summary>
    /// Đối tượng THCP
    /// </summary>
    public Guid? JobId { get; set; }

    /// <summary>
    /// Hợp đồng
    /// </summary>
    public Guid? ContractId { get; set; }

    /// <summary>
    /// Đơn hàng
    /// </summary>
    public Guid? OrderId { get; set; }

    /// <summary>
    /// Chi phí nguyên vật liệu trực tiếp đầu kỳ
    /// </summary>
    public decimal DirectMatetialAmount { get; set; }

    /// <summary>
    /// Chi phí nguyên vật liệu gián tiếp đầu kỳ
    /// </summary>
    public decimal IndirectMatetialAmount { get; set; }

    /// <summary>
    /// Chi phí nhân công trực tiếp đầu kỳ
    /// </summary>
    public decimal DirectLaborAmount { get; set; }

    /// <summary>
    /// Chi phí nhân công gián tiếp đầu kỳ
    /// </summary>
    public decimal IndirectLaborAmount { get; set; }

    /// <summary>
    /// Chi phí khấu hao đầu kỳ
    /// </summary>
    public decimal DepreciationAmount { get; set; }

    /// <summary>
    /// Chi phí mua ngoài đầu kỳ
    /// </summary>
    public decimal PurchaseAmount { get; set; }

    /// <summary>
    /// Chi phí khác/Chi phí chung
    /// </summary>
    public decimal OtherAmount { get; set; }

    /// <summary>
    /// Chi phí nguyên vật liệu gián tiếp đầu kỳ (Máy thi công)
    /// </summary>
    public decimal MachineIndirectMatetialAmount { get; set; }

    /// <summary>
    /// Chi phí nhân công gián tiếp đầu kỳ (Máy thi công)
    /// </summary>
    public decimal MachineIndirectLaborAmount { get; set; }

    /// <summary>
    /// Chi phí khấu hao đầu kỳ (Máy thi công)
    /// </summary>
    public decimal MachineDepreciationAmount { get; set; }

    /// <summary>
    /// Chi phí mua ngoài đầu kỳ (Máy thi công)
    /// </summary>
    public decimal MachinePurchaseAmount { get; set; }

    /// <summary>
    /// Chi phí khác (Máy thi công)/Chi phí Máy thi công
    /// </summary>
    public decimal MachineOtherAmount { get; set; }

    /// <summary>
    /// Số đã nghiệm thu
    /// </summary>
    public decimal AcceptedAmount { get; set; }

    /// <summary>
    /// Số chưa nghiệm thu
    /// </summary>
    public decimal NotAcceptedAmount { get; set; }

    /// <summary>
    /// Tổng Chi phí
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Số thứ tự dòng
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// 0=Sổ tài chinh;1=Sổ quản trị
    /// </summary>
    public int DisplayOnBook { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    /// <summary>
    /// TK CPSXKD dở dang
    /// </summary>
    public string? UncompletedAccount { get; set; }

    public bool UnResonableCost { get; set; }

    public virtual OrganizationUnit Branch { get; set; } = null!;

    public virtual Contract? Contract { get; set; }

    public virtual ICollection<Jcopndetail> Jcopndetails { get; set; } = new List<Jcopndetail>();

    public virtual Job? Job { get; set; }

    public virtual Saorder? Order { get; set; }

    public virtual ProjectWork? ProjectWork { get; set; }

    public virtual Account? UncompletedAccountNavigation { get; set; }
}