// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu định mức giá thành thành phẩm
/// </summary>
public partial class JcproductQuantum
{
    /// <summary>
    /// Mã thành phẩm
    /// </summary>
    public Guid InventoryItemId { get; set; }

    /// <summary>
    /// Chi phí nguyên vật liệu trực tiếp trong kỳ
    /// </summary>
    public decimal DirectMatetialAmount { get; set; }

    /// <summary>
    /// Chi phí nguyên vật liệu gián tiếp trong kỳ
    /// </summary>
    public decimal IndirectMatetialAmount { get; set; }

    /// <summary>
    /// Chi phí nhân công trực tiếp trong kỳ
    /// </summary>
    public decimal DirectLaborAmount { get; set; }

    /// <summary>
    /// Chi phí nhân công gián tiếp trong kỳ
    /// </summary>
    public decimal IndirectLaborAmount { get; set; }

    /// <summary>
    /// Chi phí khấu hao trong kỳ
    /// </summary>
    public decimal DepreciationAmount { get; set; }

    /// <summary>
    /// Chi phí mua ngoài trong kỳ
    /// </summary>
    public decimal PurchaseAmount { get; set; }

    /// <summary>
    /// Chi phí khác trong kỳ
    /// </summary>
    public decimal OtherAmount { get; set; }

    /// <summary>
    /// Tổng giá thành
    /// </summary>
    public decimal TotalAmount { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public virtual InventoryItem InventoryItem { get; set; } = null!;
}