// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class LicenseConfig
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid LicenseId { get; set; }

    /// <summary>
    /// Số GPSD
    /// </summary>
    public string LicenseNo { get; set; } = null!;

    /// <summary>
    /// Tên công ty trên GPSD
    /// </summary>
    public string? CompanyName { get; set; }

    /// <summary>
    /// Mã chi nhánh sử dụng
    /// </summary>
    public string? BranchCode { get; set; }

    /// <summary>
    /// Là giấy phép ngầm định
    /// </summary>
    public bool IsDefault { get; set; }

    /// <summary>
    /// Nội dung GPSD
    /// </summary>
    public string? LicenseContent { get; set; }

    /// <summary>
    /// Thời gian kiểm tra License gần nhất
    /// </summary>
    public DateTime? LastCheckingTime { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public bool? IsSystem { get; set; }

    public bool? Inactive { get; set; }

    /// <summary>
    /// Mã chi nhánh sử dụng
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// Tên chi nhánh
    /// </summary>
    public string? BranchName { get; set; }

    public string? IsCandicateEncryption { get; set; }

    public Guid? TokenKey { get; set; }

    public string? PublicKey { get; set; }

    public bool? IsLicenseOnline { get; set; }

    public string? TaxCode { get; set; }

    public string? LicenseOnlineKey { get; set; }

    public string? MessageUpdateLicense { get; set; }

    public bool? InactiveOnline { get; set; }

    public int ProductPackCode { get; set; }

    public int LicenseType { get; set; }

    public int NumberOfUse { get; set; }

    public string? ProductLine { get; set; }
}