// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class LoanProfileDetail
{
    /// <summary>
    /// ID
    /// </summary>
    public Guid LoanProfileDetailId { get; set; }

    /// <summary>
    /// ID
    /// </summary>
    public Guid LoanProfileId { get; set; }

    /// <summary>
    /// Tên file
    /// </summary>
    public string? FileName { get; set; }

    /// <summary>
    /// Tên của báo cáo
    /// </summary>
    public string? ReportFileName { get; set; }

    /// <summary>
    /// Nội dung file
    /// </summary>
    public byte[]? FileContent { get; set; }

    /// <summary>
    /// Số TT
    /// </summary>
    public int? SortOrder { get; set; }

    public string? FilePath { get; set; }

    public decimal? PropotionRate { get; set; }

    public decimal? Amount { get; set; }

    public int? TypeReport { get; set; }

    public Guid? ItemId { get; set; }

    public string? ItemName { get; set; }

    public virtual LoanProfile LoanProfile { get; set; } = null!;
}