// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class LoanProfileSummaryReport
{
    public Guid? BranchId { get; set; }

    public decimal? ClosingDebitAmount { get; set; }

    public decimal? PaymentAmount { get; set; }

    public decimal? PayrollAmount { get; set; }

    public decimal? RevenueLastYear { get; set; }

    public decimal? ShortRatio { get; set; }

    public decimal? QuickRatio { get; set; }

    public decimal? ImmediateRatio { get; set; }

    public decimal? PaymentTurnover { get; set; }

    public decimal? RevenueTurnover { get; set; }

    public decimal? CashFlowOperating { get; set; }

    public decimal? CashFlowInvesting { get; set; }

    public decimal? CashFlowFinancing { get; set; }

    public bool? IsWorkingWithManagementBook { get; set; }
}