// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class LoanProfileDetailTemplate
{
    public Guid ItemId { get; set; }

    public string? ItemName { get; set; }

    public string? FileName { get; set; }

    public string? ReportFileName { get; set; }

    public int? TypeReport { get; set; }

    public bool IsBold { get; set; }

    public bool IsItalic { get; set; }

    public bool AllowAttach { get; set; }

    public int? SortOrder { get; set; }
}