// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class MappingInbotObject
{
    public int MappingId { get; set; }

    public string TableName { get; set; } = null!;

    public string ColumnName { get; set; } = null!;

    public string ValueMapping { get; set; } = null!;

    public Guid ObjectMapping { get; set; }

    public int SortOrder { get; set; }

    public bool? IsAutoMapping { get; set; }

    public string? UserMapping { get; set; }

    public string? MachineMapping { get; set; }

    public DateTime? TimeMapping { get; set; }
}