// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng mapping đối tượng khi lập phiếu thu/chi từ lịch sử giao dịch của ngân hàng
/// </summary>
public partial class MappingEbobject
{
    /// <summary>
    /// ID của bảng
    /// </summary>
    public Guid MappingId { get; set; }

    /// <summary>
    /// ID của đối tượng đã mapping
    /// </summary>
    public Guid ObjectMapping { get; set; }

    /// <summary>
    /// Giá trị cần so sánh
    /// </summary>
    public string ValueMapping { get; set; } = null!;
}