// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class MinutesInvoice
{
    public Guid RefId { get; set; }

    public int? RefType { get; set; }

    public DateTime? RefDate { get; set; }

    public string RefNo { get; set; }

    public Guid? BranchId { get; set; }

    public int? MinutesInvoiceId { get; set; }

    public string TransactionId { get; set; }

    public string JsonData { get; set; }

    public int? MinutesInvoiceType { get; set; }

    public string Reason { get; set; }

    public int? MinutesInvoiceStatus { get; set; }

    public int? SendStatus { get; set; }

    public string MetaDataA { get; set; }

    public string MetaDataB { get; set; }

    public string AdjustTransactionId { get; set; }

    public string InvTemplateNo { get; set; }

    public string InvSeries { get; set; }

    public DateTime? InvDate { get; set; }

    public string InvNo { get; set; }

    public Guid? SainvoiceRefId { get; set; }

    public int? SainvoiceRefType { get; set; }

    public int? InvTypeId { get; set; }

    public string AccountObjectCode { get; set; }

    public string AccountObjectName { get; set; }

    public string AccountObjectAddress { get; set; }

    public decimal? Amount { get; set; }

    public string CompanyTaxCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public byte[] EditVersion { get; set; }

    public Guid? MinutesInvoiceId123 { get; set; }
}