// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class MobileDataChanged
{
    public int ChangedId { get; set; }

    public string TableName { get; set; }

    public int SyncStatus { get; set; }

    public DateTime? PostedDate { get; set; }
}