// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class MobileAccountBalanceDataChanged
{
    public int ChangedId { get; set; }

    public string AccountNumber { get; set; }

    public int SyncStatus { get; set; }
}