// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu trữ nhật ký truy cập
/// </summary>
public partial class MscAudittingLog
{
    public Guid EventId { get; set; }

    /// <summary>
    /// Tên người dùng thao tác Database
    /// </summary>
    public string? LoginName { get; set; }

    /// <summary>
    /// Tên máy thao tác Database
    /// </summary>
    public string? ComputerName { get; set; }

    /// <summary>
    /// Địa chỉ IP
    /// </summary>
    public string? ComputerIp { get; set; }

    /// <summary>
    /// Phân hệ thao tác
    /// </summary>
    public string? ApplicationPartAlias { get; set; }

    /// <summary>
    /// Thao tác
    /// </summary>
    public string? PermissionTypeAlias { get; set; }

    /// <summary>
    /// Thời gian thao tác database
    /// </summary>
    public DateTime? Time { get; set; }

    /// <summary>
    /// Mô tả chi tiết
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Tham chiếu sổ tài chính
    /// </summary>
    public string? Reference { get; set; }

    public Guid? RefId { get; set; }

    public int? RefType { get; set; }

    public Guid? UserId { get; set; }

    public Guid? BranchId { get; set; }

    /// <summary>
    /// Tham chiếu sổ quản trị
    /// </summary>
    public string? ReferenceManagement { get; set; }

    /// <summary>
    /// Làm việc trên sổ: 1 sổ quản trị: 0 sổ tài chính
    /// </summary>
    public string? IsWorkingWithManagementBook { get; set; }

    public string? ApplicationPartCode { get; set; }

    public string? Parameter { get; set; }

    public virtual ICollection<MscAudittingLogDetail> MscAudittingLogDetails { get; set; } = new List<MscAudittingLogDetail>();
}