// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class MscSubSystemMobile
{
    public string SubSystemCode { get; set; } = null!;

    public string? SubSystemName { get; set; }

    public string? Description { get; set; }

    public string? ParentSubSystemCode { get; set; }

    public int? SortOrder { get; set; }

    public int? SystemType { get; set; }

    public string? SubSystemSerial { get; set; }

    public virtual ICollection<MscRegisPermisionMobileForSubSystem> MscRegisPermisionMobileForSubSystems { get; set; } = new List<MscRegisPermisionMobileForSubSystem>();

    public virtual ICollection<MscRolePermissionMapingMobile> MscRolePermissionMapingMobiles { get; set; } = new List<MscRolePermissionMapingMobile>();
}