// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class MscUserMobile
{
    public Guid UserId { get; set; }

    public Guid? EmployeeId { get; set; }

    public string? JobTitle { get; set; }

    public string? FullName { get; set; }

    public string? MobilePhone { get; set; }

    public string? Email { get; set; }

    public string? LastName { get; set; }

    public string? FirstName { get; set; }

    public string? UserName { get; set; }

    public bool? IsViewSalary { get; set; }

    public virtual ICollection<MscUserJoinRoleMobile> MscUserJoinRoleMobiles { get; set; } = new List<MscUserJoinRoleMobile>();
}