// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class PasalarySheetTemplateUser
{
    public Guid LayoutId { get; set; }

    public Guid UserId { get; set; }

    public int State { get; set; }

    public Guid? PasalarySheetId { get; set; }

    public virtual PasalarySheetTemplate Layout { get; set; }
}