// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class PasalaryExpenseAllocationDetail
{
    public Guid RefDetailId { get; set; }

    public Guid RefId { get; set; }

    public Guid? EmployeeId { get; set; }

    public Guid? OrganizationUnitId { get; set; }

    public Guid AllocationObjectId { get; set; }

    public decimal AllocationRate { get; set; }

    public decimal AllocationAmount { get; set; }

    public decimal TotalExpenseAmount { get; set; }

    public decimal? PaidWorkingdayAmount { get; set; }

    public decimal? NonWorkingdayAmount { get; set; }

    public decimal? OverTimeAmount { get; set; }

    public decimal? PayrollFundAllowance { get; set; }

    public decimal? OtherAllowance { get; set; }

    public decimal? CompanySocialInsuranceAmount { get; set; }

    public decimal? CompanyHealthInsurranceAmount { get; set; }

    public decimal? CompanyUnemploymentInsurranceAmount { get; set; }

    public decimal? CompanyLaborUnionContributionAmount { get; set; }

    public int SortOrder { get; set; }

    public string? CostAccount { get; set; }

    public decimal? BasicWage { get; set; }

    public decimal? SalaryCoefficient { get; set; }

    public decimal? WorkingDayUnitPrice { get; set; }

    public decimal? WorkingHourUnitPrice { get; set; }

    public decimal? NumberOfPaidWorkingdayTimeSheet { get; set; }

    public decimal? NumberOfNonWorkingdayTimeSheet { get; set; }

    public decimal? TotalOverTime { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal? AdvancePaymentAmount { get; set; }

    public decimal? AdvancePaymentAmount141 { get; set; }

    public decimal? InsuranceSalaryAmount { get; set; }

    public decimal? SocialInsuranceAmount { get; set; }

    public decimal? HealthInsurranceAmount { get; set; }

    public decimal? UnemploymentInsurranceAmount { get; set; }

    public decimal? LaborUnionContributionAmount { get; set; }

    public decimal? IncomeTaxAmount { get; set; }

    public decimal? SumOfDeductionAmount { get; set; }

    public decimal? FamilyCoditionDeductionAmount { get; set; }

    public decimal? IncomeForTaxCalculation { get; set; }

    public decimal? NetAmount { get; set; }

    public decimal? ColumnNumber1 { get; set; }

    public decimal? ColumnNumber2 { get; set; }

    public decimal? ColumnNumber3 { get; set; }

    public decimal? ColumnNumber4 { get; set; }

    public decimal? ColumnNumber5 { get; set; }

    public decimal? ColumnNumber6 { get; set; }

    public decimal? ColumnNumber7 { get; set; }

    public decimal? ColumnNumber8 { get; set; }

    public decimal? ColumnNumber9 { get; set; }

    public decimal? ColumnNumber10 { get; set; }

    public decimal? ColumnMoney1 { get; set; }

    public decimal? ColumnMoney2 { get; set; }

    public decimal? ColumnMoney3 { get; set; }

    public decimal? ColumnMoney4 { get; set; }

    public decimal? ColumnMoney5 { get; set; }

    public decimal? ColumnMoney6 { get; set; }

    public decimal? ColumnMoney7 { get; set; }

    public decimal? ColumnMoney8 { get; set; }

    public decimal? ColumnMoney9 { get; set; }

    public decimal? ColumnMoney10 { get; set; }

    public string? ColumnString1 { get; set; }

    public string? ColumnString2 { get; set; }

    public string? ColumnString3 { get; set; }

    public string? ColumnString4 { get; set; }

    public string? ColumnString5 { get; set; }

    public decimal? TotalPersonalTaxIncomeAmount { get; set; }

    public virtual AccountObject? Employee { get; set; }

    public virtual OrganizationUnit? OrganizationUnit { get; set; }

    public virtual PasalaryExpenseAllocation Ref { get; set; } = null!;
}