// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng kê sử dụng chứng từ chi tiết
/// </summary>
public partial class PavoucherUsageDetail
{
    public Guid RefDetailId { get; set; }

    public Guid RefId { get; set; }

    /// <summary>
    /// Thứ tự sắp xếp các dòng chi tiết
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Ký hiệu chứng từ
    /// </summary>
    public string? Series { get; set; }

    /// <summary>
    /// ID chứng từ khấu trừ thuế
    /// </summary>
    public Guid? OriginalRefId { get; set; }

    /// <summary>
    /// RefType chứng từ khấu trừ thuế
    /// </summary>
    public int? RefTypeReference { get; set; }

    /// <summary>
    /// Số chứng từ 
    /// </summary>
    public string? RefNo { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime? RefDate { get; set; }

    /// <summary>
    /// Họ và tên người bị khấu trừ thuế
    /// </summary>
    public string? EmployeeName { get; set; }

    /// <summary>
    /// Mã số thuế/CMND/Hộ chiếu
    /// </summary>
    public string? EmployeeTaxNo { get; set; }

    /// <summary>
    /// Số tiền
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string? Note { get; set; }

    public virtual PavoucherUsage Ref { get; set; } = null!;
}