// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng danh mục điều kiện chiết khấu
/// </summary>
public partial class PaymentTerm
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid PaymentTermId { get; set; }

    /// <summary>
    /// Mã điều khoản thanh toán
    /// </summary>
    public string PaymentTermCode { get; set; } = null!;

    /// <summary>
    /// Tên điều khoản thanh toán
    /// </summary>
    public string PaymentTermName { get; set; } = null!;

    /// <summary>
    /// Hạn nợ (Số ngày được nợ)
    /// </summary>
    public int DueTime { get; set; }

    /// <summary>
    /// Thời hạn hưởng chiết khấu
    /// </summary>
    public int DiscountTime { get; set; }

    /// <summary>
    /// Tỷ lệ chiết khấu
    /// </summary>
    public decimal DiscountPercent { get; set; }

    /// <summary>
    /// Ngừng theo dõi
    /// </summary>
    public bool Inactive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public virtual ICollection<AccountObject> AccountObjects { get; set; } = new List<AccountObject>();

    public virtual ICollection<GlvoucherCrossEntryDetail> GlvoucherCrossEntryDetails { get; set; } = new List<GlvoucherCrossEntryDetail>();

    public virtual ICollection<Puservice> Puservices { get; set; } = new List<Puservice>();

    public virtual ICollection<Puvoucher> Puvouchers { get; set; } = new List<Puvoucher>();

    public virtual ICollection<Saorder> Saorders { get; set; } = new List<Saorder>();

    public virtual ICollection<Savoucher> Savouchers { get; set; } = new List<Savoucher>();
}