// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Các khoản chi phí trả trước
/// </summary>
public partial class PrepaidExpense
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid PrepaidExpensesId { get; set; }

    /// <summary>
    /// Mã chi phí trả trước
    /// </summary>
    public string PrepaidExpensesCode { get; set; } = null!;

    /// <summary>
    /// Tên chi phí trả trước
    /// </summary>
    public string? PrepaidExpensesName { get; set; }

    /// <summary>
    /// Ngày ghi nhận
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// Số tiền
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Số kỳ phân bổ
    /// </summary>
    public int AllocationTime { get; set; }

    /// <summary>
    /// Số tiền phân bổ hàng kỳ
    /// </summary>
    public decimal AllocationAmount { get; set; }

    /// <summary>
    /// Tài khoản chờ phân bổ
    /// </summary>
    public string? AllocationAccount { get; set; }

    /// <summary>
    /// 0 = Sổ tài chính; 1 = Sổ quản trị
    /// </summary>
    public int DisplayOnBook { get; set; }

    public Guid? BranchId { get; set; }

    public int? RefType { get; set; }

    public Guid? CopyFromId { get; set; }

    /// <summary>
    /// Số tiền đã phân bổ
    /// </summary>
    public decimal AllocatedAmount { get; set; }

    /// <summary>
    /// Số kỳ đã phân bổ
    /// </summary>
    public int AllocatedPeriod { get; set; }

    public bool Inactive { get; set; }

    public string? ReasonInactive { get; set; }

    public virtual Account? AllocationAccountNavigation { get; set; }

    public virtual ICollection<GlvoucherDetailExpense> GlvoucherDetailExpenses { get; set; } = new List<GlvoucherDetailExpense>();

    public virtual ICollection<GlvoucherDetailExpensesAllocation> GlvoucherDetailExpensesAllocations { get; set; } = new List<GlvoucherDetailExpensesAllocation>();

    public virtual ICollection<PrepaidExpensesDetailSource> PrepaidExpensesDetailSources { get; set; } = new List<PrepaidExpensesDetailSource>();

    public virtual ICollection<PrepaidExpensesDetail> PrepaidExpensesDetails { get; set; } = new List<PrepaidExpensesDetail>();
}