// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class PreReceiptRevenueDetail
{
    public Guid PreReceiptRevenueDetailId { get; set; }

    public Guid PreReceiptRevenueId { get; set; }

    public Guid? AllocationObjectId { get; set; }

    public string AllocationObjectName { get; set; }

    public int? AllocationObjectType { get; set; }

    public decimal AllocationRate { get; set; }

    public string AllocationAccount { get; set; }

    public int SortOrder { get; set; }

    public virtual Account AllocationAccountNavigation { get; set; }

    public virtual PreReceiptRevenue PreReceiptRevenue { get; set; }
}