// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ProjectWorkEstimateDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Giá trị dự toán
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Khoản mục chi phí
    /// </summary>
    public Guid ExpenseItemId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public virtual ExpenseItem ExpenseItem { get; set; } = null!;

    public virtual ProjectWorkEstimate Ref { get; set; } = null!;
}