// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Hợp đồng mua
/// </summary>
public partial class Pucontract
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid PucontractId { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// Số hợp đồng
    /// </summary>
    public string? ContractCode { get; set; }

    /// <summary>
    /// Ngày ký
    /// </summary>
    public DateTime SignDate { get; set; }

    /// <summary>
    /// Trích yếu
    /// </summary>
    public string? Subject { get; set; }

    /// <summary>
    /// Loại tiền
    /// </summary>
    public string? CurrencyId { get; set; }

    /// <summary>
    /// Tỷ giá
    /// </summary>
    public decimal? ExchangeRate { get; set; }

    /// <summary>
    /// Giá trị hợp đồng
    /// </summary>
    public decimal AmountOc { get; set; }

    /// <summary>
    /// Giá trị hợp đồng Quy đổi
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// ID Nhà cung cấp
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Tên nhà cung cấp
    /// </summary>
    public string? AccountObjectName { get; set; }

    /// <summary>
    /// Địa chỉ nhà cung cấp
    /// </summary>
    public string? AccountObjectAddress { get; set; }

    /// <summary>
    /// Mã số thuế NCC
    /// </summary>
    public string? AccountObjectTaxCode { get; set; }

    /// <summary>
    /// Người liên hệ
    /// </summary>
    public string? AccountObjectContactName { get; set; }

    /// <summary>
    /// Tình trạng hợp đồng. 0: Chưa thực hiện; 1: Đang thực hiện; 2: Hoàn thành; 3: Đã thanh lý; 4: Đã hủy bỏ
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// Giá trị thanh lý
    /// </summary>
    public decimal CloseAmountOc { get; set; }

    /// <summary>
    /// Giá trị thanh lý Quy đổi
    /// </summary>
    public decimal CloseAmount { get; set; }

    /// <summary>
    /// Số đã trả
    /// </summary>
    public decimal PaidAmountOc { get; set; }

    /// <summary>
    /// Số đã trả Quy đổi
    /// </summary>
    public decimal PaidAmount { get; set; }

    /// <summary>
    /// Số còn phải trả
    /// </summary>
    public decimal PayableAmountOc { get; set; }

    /// <summary>
    /// Số còn phải trả Quy đổi
    /// </summary>
    public decimal PayableAmount { get; set; }

    /// <summary>
    /// Ngày thanh lý/Hủy bỏ
    /// </summary>
    public DateTime? CloseDate { get; set; }

    /// <summary>
    /// Lý do
    /// </summary>
    public string? CloseReason { get; set; }

    /// <summary>
    /// Hạn giao hàng
    /// </summary>
    public DateTime? DeliverDueDate { get; set; }

    /// <summary>
    /// Địa chỉ giao hàng
    /// </summary>
    public string? DeliverAddress { get; set; }

    /// <summary>
    /// Hạn thanh toán
    /// </summary>
    public DateTime? DueDate { get; set; }

    /// <summary>
    /// ID nhân viên
    /// </summary>
    public Guid? EmployeeId { get; set; }

    /// <summary>
    /// Điều khoản khác
    /// </summary>
    public string? PaymentTerm { get; set; }

    /// <summary>
    /// Loai chung tu
    /// </summary>
    public int RefType { get; set; }

    public bool? IsArisedBeforeUseSoftware { get; set; }

    public decimal? ExecutedAmountFinance { get; set; }

    public decimal? ExecutedAmountManagement { get; set; }

    public decimal? PaidAmountFinance { get; set; }

    public decimal? PaidAmountManagement { get; set; }

    /// <summary>
    /// Mã đơn mua hàng
    /// </summary>
    public Guid? PuorderId { get; set; }

    public string? CustomField1 { get; set; }

    public string? CustomField2 { get; set; }

    public string? CustomField3 { get; set; }

    public string? CustomField4 { get; set; }

    public string? CustomField5 { get; set; }

    public string? CustomField6 { get; set; }

    public string? CustomField7 { get; set; }

    public string? CustomField8 { get; set; }

    public string? CustomField9 { get; set; }

    public string? CustomField10 { get; set; }

    public bool IsOverQuantity { get; set; }

    public virtual AccountObject? AccountObject { get; set; }

    public virtual ICollection<BadepositDetail> BadepositDetails { get; set; } = new List<BadepositDetail>();

    public virtual ICollection<BainternalTransferDetail> BainternalTransferDetails { get; set; } = new List<BainternalTransferDetail>();

    public virtual ICollection<BawithDrawDetail> BawithDrawDetails { get; set; } = new List<BawithDrawDetail>();

    public virtual OrganizationUnit? Branch { get; set; }

    public virtual ICollection<CapaymentDetail> CapaymentDetails { get; set; } = new List<CapaymentDetail>();

    public virtual ICollection<CareceiptDetail> CareceiptDetails { get; set; } = new List<CareceiptDetail>();

    public virtual Ccy? Currency { get; set; }

    public virtual AccountObject? Employee { get; set; }

    public virtual ICollection<GlvoucherDetail> GlvoucherDetails { get; set; } = new List<GlvoucherDetail>();

    public virtual ICollection<IninvoiceHubOutwardDetail> IninvoiceHubOutwardDetails { get; set; } = new List<IninvoiceHubOutwardDetail>();

    public virtual ICollection<IninvoiceHubTransferDetail> IninvoiceHubTransferDetails { get; set; } = new List<IninvoiceHubTransferDetail>();

    public virtual ICollection<IninwardDetail> IninwardDetails { get; set; } = new List<IninwardDetail>();

    public virtual ICollection<InoutwardDetail> InoutwardDetails { get; set; } = new List<InoutwardDetail>();

    public virtual ICollection<IntransferDetail> IntransferDetails { get; set; } = new List<IntransferDetail>();

    public virtual ICollection<Loanagreement> Loanagreements { get; set; } = new List<Loanagreement>();

    public virtual ICollection<OpeningAccountEntryDetail> OpeningAccountEntryDetails { get; set; } = new List<OpeningAccountEntryDetail>();

    public virtual ICollection<PucontractDetailInventoryItem> PucontractDetailInventoryItems { get; set; } = new List<PucontractDetailInventoryItem>();

    public virtual ICollection<PudiscountDetail> PudiscountDetails { get; set; } = new List<PudiscountDetail>();

    public virtual ICollection<PuinvoiceDetail> PuinvoiceDetails { get; set; } = new List<PuinvoiceDetail>();

    public virtual ICollection<PuorderDetail> PuorderDetails { get; set; } = new List<PuorderDetail>();

    public virtual ICollection<PureturnDetail> PureturnDetails { get; set; } = new List<PureturnDetail>();

    public virtual ICollection<PuserviceDetail> PuserviceDetails { get; set; } = new List<PuserviceDetail>();

    public virtual ICollection<PuvoucherDetail> PuvoucherDetails { get; set; } = new List<PuvoucherDetail>();
}