// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class PuinvoiceDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã hàng
    /// </summary>
    public Guid InventoryItemId { get; set; }

    /// <summary>
    /// Tên hàng
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// TK Nợ
    /// </summary>
    public string? DebitAccount { get; set; }

    /// <summary>
    /// TK Có
    /// </summary>
    public string? CreditAccount { get; set; }

    /// <summary>
    /// Giá trị HHDV chưa thuế
    /// </summary>
    public decimal TurnoverAmountOc { get; set; }

    /// <summary>
    /// Giá trị HHDV chưa thuế QĐ
    /// </summary>
    public decimal TurnoverAmount { get; set; }

    /// <summary>
    /// Thuế suất GTGT
    /// </summary>
    public decimal? Vatrate { get; set; }

    public decimal VatamountOc { get; set; }

    /// <summary>
    /// Tiền thuế GTGT quy đổi
    /// </summary>
    public decimal Vatamount { get; set; }

    /// <summary>
    /// Mã nhóm hàng hóa dịch vụ
    /// </summary>
    public Guid? PurchasePurposeId { get; set; }

    /// <summary>
    /// RefID chứng từ Mua hàng
    /// </summary>
    public Guid? PuvoucherRefId { get; set; }

    /// <summary>
    /// RefDetailID chứng từ Mua hàng
    /// </summary>
    public Guid? PuvoucherRefDetailId { get; set; }

    /// <summary>
    /// PK hợp đồng mua
    /// </summary>
    public Guid? PucontractId { get; set; }

    /// <summary>
    /// Mã thống kê
    /// </summary>
    public Guid? ListItemId { get; set; }

    /// <summary>
    /// Khoản mục chi phí
    /// </summary>
    public Guid? ExpenseItemId { get; set; }

    /// <summary>
    /// Đơn vị sử dụng
    /// </summary>
    public Guid? OrganizationUnitId { get; set; }

    /// <summary>
    /// Đối tượng THCP
    /// </summary>
    public Guid? JobId { get; set; }

    /// <summary>
    /// Công trình/Dự án
    /// </summary>
    public Guid? ProjectWorkId { get; set; }

    /// <summary>
    /// Mã đơn đặt hàng
    /// </summary>
    public Guid? OrderId { get; set; }

    /// <summary>
    /// PK  hợp đồng bán
    /// </summary>
    public Guid? ContractId { get; set; }

    /// <summary>
    /// Chi phí không hợp lý
    /// </summary>
    public bool UnResonableCost { get; set; }

    /// <summary>
    /// Thứ tự sắp xếp các dòng chi tiết
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// Số chứng từ Mua hàng
    /// </summary>
    public string? PuvoucherRefNoFinance { get; set; }

    /// <summary>
    /// Số chứng từ Mua hàng
    /// </summary>
    public string? PuvoucherRefNoManagement { get; set; }

    public string? CustomField1 { get; set; }

    public string? CustomField2 { get; set; }

    public string? CustomField3 { get; set; }

    public string? CustomField4 { get; set; }

    public string? CustomField5 { get; set; }

    public string? CustomField6 { get; set; }

    public string? CustomField7 { get; set; }

    public string? CustomField8 { get; set; }

    public string? CustomField9 { get; set; }

    public string? CustomField10 { get; set; }

    public string? Vatdescription { get; set; }

    public Guid? PuorderRefId { get; set; }

    public Guid? PuorderRefDetailId { get; set; }

    public Guid? InvestmentProjectId { get; set; }

    public decimal? VatrateOther { get; set; }

    public virtual Contract? Contract { get; set; }

    public virtual Account? CreditAccountNavigation { get; set; }

    public virtual Account? DebitAccountNavigation { get; set; }

    public virtual ExpenseItem? ExpenseItem { get; set; }

    public virtual InventoryItem InventoryItem { get; set; } = null!;

    public virtual InvestmentProject? InvestmentProject { get; set; }

    public virtual Job? Job { get; set; }

    public virtual ListItem? ListItem { get; set; }

    public virtual Saorder? Order { get; set; }

    public virtual OrganizationUnit? OrganizationUnit { get; set; }

    public virtual ProjectWork? ProjectWork { get; set; }

    public virtual Pucontract? Pucontract { get; set; }

    public virtual Puorder? PuorderRef { get; set; }

    public virtual PuorderDetail? PuorderRefDetail { get; set; }

    public virtual PurchasePurpose? PurchasePurpose { get; set; }

    public virtual Puinvoice Ref { get; set; } = null!;
}