// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Nhóm HHDV mua vào. Dùng để phân loại hóa đơn mua vào phục vụ việc lập bảng kê mua vào.
/// </summary>
public partial class PurchasePurpose
{
    public Guid PurchasePurposeId { get; set; }

    /// <summary>
    /// Mã mục đích mua
    /// </summary>
    public string? PurchasePurposeCode { get; set; }

    /// <summary>
    /// Tên mục đích mua
    /// </summary>
    public string PurchasePurposeName { get; set; } = null!;

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Ngừng theo dõi
    /// </summary>
    public bool Inactive { get; set; }

    /// <summary>
    /// Thuộc hệ thống
    /// </summary>
    public bool IsSystem { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public virtual ICollection<BawithdrawDetailTax> BawithdrawDetailTaxes { get; set; } = new List<BawithdrawDetailTax>();

    public virtual ICollection<CapaymentDetailTax> CapaymentDetailTaxes { get; set; } = new List<CapaymentDetailTax>();

    public virtual ICollection<PudiscountDetail> PudiscountDetails { get; set; } = new List<PudiscountDetail>();

    public virtual ICollection<PuinvoiceDetail> PuinvoiceDetails { get; set; } = new List<PuinvoiceDetail>();

    public virtual ICollection<PureturnDetail> PureturnDetails { get; set; } = new List<PureturnDetail>();

    public virtual ICollection<PuserviceDetail> PuserviceDetails { get; set; } = new List<PuserviceDetail>();

    public virtual ICollection<PuvoucherDetail> PuvoucherDetails { get; set; } = new List<PuvoucherDetail>();

    public virtual ICollection<SareturnDetail> SareturnDetails { get; set; } = new List<SareturnDetail>();
}