// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng Ledger mua hàng
/// </summary>
public partial class PurchaseLedger
{
    /// <summary>
    /// PK-Sổ mua hàng
    /// </summary>
    public int PurchaseLedgerId { get; set; }

    /// <summary>
    /// RefDetailID của chứng từ gốc
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// RefID của chứng từ gốc
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// Ngày hạch toán
    /// </summary>
    public DateTime PostedDate { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// Loại chứng từ (lấy từ bảng RefType)
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Số chứng từ Sổ quản trị
    /// </summary>
    public string RefNo { get; set; }

    /// <summary>
    /// Diễn giải master
    /// </summary>
    public string JournalMemo { get; set; }

    /// <summary>
    /// Mã hàng
    /// </summary>
    public Guid? InventoryItemId { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Kho
    /// </summary>
    public Guid? StockId { get; set; }

    /// <summary>
    /// TK Nợ
    /// </summary>
    public string DebitAccount { get; set; }

    /// <summary>
    /// Tk Có
    /// </summary>
    public string CreditAccount { get; set; }

    /// <summary>
    /// Đơn vị tính
    /// </summary>
    public Guid? UnitId { get; set; }

    /// <summary>
    /// Đơn giá quy đổi
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Số lượng mua
    /// </summary>
    public decimal PurchaseQuantity { get; set; }

    /// <summary>
    /// Giá trị mua
    /// </summary>
    public decimal PurchaseAmountOc { get; set; }

    /// <summary>
    /// Giá trị mua Quy đổi
    /// </summary>
    public decimal PurchaseAmount { get; set; }

    /// <summary>
    /// Tỉ lệ chiết khấu
    /// </summary>
    public decimal? DiscountRate { get; set; }

    /// <summary>
    /// Tiền chiêt khấu
    /// </summary>
    public decimal DiscountAmountOc { get; set; }

    /// <summary>
    /// Tiền chiêt khấu quy đổi
    /// </summary>
    public decimal DiscountAmount { get; set; }

    /// <summary>
    /// Thuế suất GTGT
    /// </summary>
    public decimal? Vatrate { get; set; }

    /// <summary>
    /// Tiền thuế GTGT quy đổi
    /// </summary>
    public decimal Vatamount { get; set; }

    /// <summary>
    /// Tiền thuế nguyên tệ
    /// </summary>
    public decimal VatamountOc { get; set; }

    /// <summary>
    /// TK thuế GTGT
    /// </summary>
    public string Vataccount { get; set; }

    /// <summary>
    /// Số lượng trả lại
    /// </summary>
    public decimal ReturnQuantity { get; set; }

    /// <summary>
    /// Giá trị trả lại
    /// </summary>
    public decimal ReturnAmountOc { get; set; }

    /// <summary>
    /// Giá trị trả lại Quy đổi
    /// </summary>
    public decimal ReturnAmount { get; set; }

    /// <summary>
    /// Giá trị giảm
    /// </summary>
    public decimal ReduceAmountOc { get; set; }

    /// <summary>
    /// Giá trị giảm Quy đổi
    /// </summary>
    public decimal ReduceAmount { get; set; }

    /// <summary>
    /// Ngày hóa đơn
    /// </summary>
    public DateTime? InvDate { get; set; }

    /// <summary>
    /// Ký hiệu hóa đơn
    /// </summary>
    public string InvSeries { get; set; }

    /// <summary>
    /// Số hóa đơn
    /// </summary>
    public string InvNo { get; set; }

    /// <summary>
    /// Loại tiền
    /// </summary>
    public string CurrencyId { get; set; }

    /// <summary>
    /// Tỉ giá hối đoái
    /// </summary>
    public decimal? ExchangeRate { get; set; }

    /// <summary>
    /// Đơn vị chính
    /// </summary>
    public Guid? MainUnitId { get; set; }

    /// <summary>
    /// Đơn giá theo đơn vị chính
    /// </summary>
    public decimal MainUnitPrice { get; set; }

    /// <summary>
    /// Tỷ lệ chuyển đổi ra đơn vị chính
    /// </summary>
    public decimal MainConvertRate { get; set; }

    /// <summary>
    /// Số lượng theo đơn vị chính
    /// </summary>
    public decimal MainQuantity { get; set; }

    /// <summary>
    /// Toán tử quy đổi *=nhân;/=chia
    /// </summary>
    public string ExchangeRateOperator { get; set; }

    /// <summary>
    /// Trạng thái ghi vào vào sổ quản trị
    /// </summary>
    public bool IsPostToManagementBook { get; set; }

    /// <summary>
    /// Đối tượng
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Nhân viên
    /// </summary>
    public Guid? EmployeeId { get; set; }

    /// <summary>
    /// Tên đối tượng
    /// </summary>
    public string AccountObjectName { get; set; }

    /// <summary>
    /// Địa chỉ
    /// </summary>
    public string AccountObjectAddress { get; set; }

    /// <summary>
    /// Mã số thuế
    /// </summary>
    public string AccountObjectTaxCode { get; set; }

    /// <summary>
    /// ID Đơn mua hàng
    /// </summary>
    public Guid? PuorderRefId { get; set; }

    /// <summary>
    /// ID đơn hàng
    /// </summary>
    public Guid? OrderId { get; set; }

    /// <summary>
    /// Công việc
    /// </summary>
    public Guid? JobId { get; set; }

    /// <summary>
    /// Hợp đồng
    /// </summary>
    public Guid? ContractId { get; set; }

    /// <summary>
    /// Mã thống kê
    /// </summary>
    public Guid? ListItemId { get; set; }

    /// <summary>
    /// Khoản mục chi phí
    /// </summary>
    public Guid? ExpenseItemId { get; set; }

    /// <summary>
    /// ID đơn vị
    /// </summary>
    public Guid? OrganizationUnitId { get; set; }

    /// <summary>
    /// Ngày hết hạn
    /// </summary>
    public DateTime? ExpiryDate { get; set; }

    /// <summary>
    /// Số lô
    /// </summary>
    public string LotNo { get; set; }

    /// <summary>
    /// Ngày thanh toán
    /// </summary>
    public DateTime? PaymentDate { get; set; }

    /// <summary>
    /// Hạn thanh toán
    /// </summary>
    public DateTime? DueDate { get; set; }

    /// <summary>
    /// Thứ tự sắp xếp các dòng chi tiết
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// Thứ tự các chứng từ nhập trước, nhập sau
    /// </summary>
    public int? RefOrder { get; set; }

    /// <summary>
    /// Điều khoản chiết khấu
    /// </summary>
    public Guid? PaymentTermId { get; set; }

    /// <summary>
    /// RefID của chứng từ Mua hàng
    /// </summary>
    public Guid? PuvoucherRefId { get; set; }

    /// <summary>
    /// RefDetailID của chứng từ Mua hàng
    /// </summary>
    public Guid? PuvoucherRefDetailId { get; set; }

    /// <summary>
    /// Mã vật tư, hàng hóa
    /// </summary>
    public string InventoryItemCode { get; set; }

    /// <summary>
    /// Tên vật tư, hàng hóa
    /// </summary>
    public string InventoryItemName { get; set; }

    /// <summary>
    /// Mã kho
    /// </summary>
    public string StockCode { get; set; }

    /// <summary>
    /// Tên kho
    /// </summary>
    public string StockName { get; set; }

    /// <summary>
    /// Mã đối tượng
    /// </summary>
    public string AccountObjectCode { get; set; }

    /// <summary>
    /// Mã nhân viên
    /// </summary>
    public string EmployeeCode { get; set; }

    /// <summary>
    /// Tên nhân viên
    /// </summary>
    public string EmployeeName { get; set; }

    /// <summary>
    /// Công trình/Dự án
    /// </summary>
    public Guid? ProjectWorkId { get; set; }

    /// <summary>
    /// Mã hợp đồng
    /// </summary>
    public string ContractCode { get; set; }

    /// <summary>
    /// Tên hợp đồng
    /// </summary>
    public string ContractName { get; set; }

    /// <summary>
    /// Mã điều khoản chiết khấu
    /// </summary>
    public string PaymentTermCode { get; set; }

    /// <summary>
    /// Tên điều khoản chiết khấu
    /// </summary>
    public string PaymentTermName { get; set; }

    /// <summary>
    /// Có cần cập nhật dữ liệu từ các bảng dư thừa sang không, 0: không, 1: có. Sau khi cập nhật xong thì thiết lập thông tin này về =0
    /// </summary>
    public bool? IsUpdateRedundant { get; set; }

    /// <summary>
    /// Tên đối tượng (Lấy từ danh mục)
    /// </summary>
    public string AccountObjectNameDi { get; set; }

    public string RefTypeName { get; set; }

    public decimal ReturnMainQuantity { get; set; }

    public Guid? InvRefId { get; set; }

    public decimal UnitPriceOc { get; set; }

    public decimal MainUnitPriceOc { get; set; }

    public int? IncludeInvoice { get; set; }

    public decimal? ImportChargeAmount { get; set; }

    public decimal? FreightAmount { get; set; }

    public string AccountObjectAddressOther { get; set; }

    public string AccountObjectIdentificationNumberOther { get; set; }

    public decimal? VatrateOther { get; set; }
}