// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chứng từ mua dịch vụ
/// </summary>
public partial class Puservice
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã chi nhánh
    /// </summary>
    public Guid? BranchId { get; set; }

    /// <summary>
    /// Ngày chứng từ (Phiếu chi/Chứng từ ghi nợ)
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// Ngày hạch toán (Phiếu chi/Chứng từ ghi nợ)
    /// </summary>
    public DateTime PostedDate { get; set; }

    /// <summary>
    /// Loại chứng từ (lấy từ bảng RefType)
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Số chứng từ sổ tài chính (Phiếu chi/Chứng từ ghi nợ)
    /// </summary>
    public string RefNoFinance { get; set; }

    /// <summary>
    /// Số chứng từ sổ quản trị (Phiếu chi/Chứng từ ghi nợ)
    /// </summary>
    public string RefNoManagement { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ Sổ tài chính
    /// </summary>
    public bool IsPostedFinance { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ Sổ quản trị
    /// </summary>
    public bool IsPostedManagement { get; set; }

    /// <summary>
    /// Là chi phí mua hàng
    /// </summary>
    public bool IsFreightService { get; set; }

    /// <summary>
    /// Mã nhà cung cấp/khách hàng/cán bộ
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Tên nhà cung cấp/khách hàng/cán bộ
    /// </summary>
    public string AccountObjectName { get; set; }

    /// <summary>
    /// Địa chỉ người nhận
    /// </summary>
    public string AccountObjectAddress { get; set; }

    /// <summary>
    /// Tài khoản của nhà cung cấp
    /// </summary>
    public string AccountObjectBankAccount { get; set; }

    /// <summary>
    /// Tên ngân hàng của nhà cung cấp
    /// </summary>
    public string AccountObjectBankName { get; set; }

    /// <summary>
    /// Người nhận/Người lĩnh tiền
    /// </summary>
    public string AccountObjectContactname { get; set; }

    /// <summary>
    /// Số CMTND của người liên hệ
    /// </summary>
    public string IdentificationNumber { get; set; }

    /// <summary>
    /// Ngày cấp CMTND người liên hệ
    /// </summary>
    public DateTime? IssueDate { get; set; }

    /// <summary>
    /// Nơi cấp CMTND người liên hệ
    /// </summary>
    public string IssueBy { get; set; }

    /// <summary>
    /// Lý do chi/Nội dung thanh toán
    /// </summary>
    public string JournalMemo { get; set; }

    /// <summary>
    /// Nhân viên mua hàng
    /// </summary>
    public Guid? EmployeeId { get; set; }

    /// <summary>
    /// Tài liệu kèm theo
    /// </summary>
    public string DocumentIncluded { get; set; }

    /// <summary>
    /// Tài khoản ngân hàng của đơn vị trả tiền
    /// </summary>
    public Guid? BankAccountId { get; set; }

    /// <summary>
    /// Tên ngân hàng đơn vị trả tiền:  chỉ dùng cho chứng từ chi tiền gửi
    /// </summary>
    public string BankName { get; set; }

    /// <summary>
    /// Điều kiện thanh toán
    /// </summary>
    public Guid? PaymentTermId { get; set; }

    /// <summary>
    /// Hạn thanh toán (bao nhiêu ngày)
    /// </summary>
    public int? DueTime { get; set; }

    /// <summary>
    /// Ngày thanh toán
    /// </summary>
    public DateTime? DueDate { get; set; }

    /// <summary>
    /// Loại tiền
    /// </summary>
    public string CurrencyId { get; set; }

    /// <summary>
    /// Tỉ giá hối đoái
    /// </summary>
    public decimal? ExchangeRate { get; set; }

    /// <summary>
    /// Tổng thành tiền
    /// </summary>
    public decimal TotalAmountOc { get; set; }

    /// <summary>
    /// Tổng thành tiền quy đổi
    /// </summary>
    public decimal TotalAmount { get; set; }

    public decimal TotalVatamountOc { get; set; }

    /// <summary>
    /// Tổng tiền thuế GTGT quy đổi
    /// </summary>
    public decimal TotalVatamount { get; set; }

    /// <summary>
    /// Tổng tiền chiết khấu
    /// </summary>
    public decimal TotalDiscountAmountOc { get; set; }

    /// <summary>
    /// Tổng tiền chiết khấu quy đổi
    /// </summary>
    public decimal TotalDiscountAmount { get; set; }

    /// <summary>
    /// Xác định chứng từ được ghi vào sổ nào (0=Sổ tài chinh;1=Sổ quản trị;2=Cả hai)
    /// </summary>
    public int? DisplayOnBook { get; set; }

    /// <summary>
    /// Đã thanh toán đủ.Với Chưa thanh toán, khi trả hết tiền thì cập nhật = 1
    /// </summary>
    public bool? IsPaid { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ thủ quỹ (Sổ tài chính)
    /// </summary>
    public bool? IsPostedCashBookFinance { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ thủ quỹ (Sổ quản trị)
    /// </summary>
    public bool? IsPostedCashBookManagement { get; set; }

    /// <summary>
    /// Ngày ghi sổ thủ quỹ
    /// </summary>
    public DateTime? CashBookPostedDate { get; set; }

    /// <summary>
    /// EditVersion
    /// </summary>
    public byte[] EditVersion { get; set; }

    /// <summary>
    /// Số thứ tự nhập chứng từ
    /// </summary>
    public int RefOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    public string CustomField5 { get; set; }

    public string CustomField6 { get; set; }

    public string CustomField7 { get; set; }

    public string CustomField8 { get; set; }

    public string CustomField9 { get; set; }

    public string CustomField10 { get; set; }

    public decimal CabaamountOc { get; set; }

    public decimal Cabaamount { get; set; }

    /// <summary>
    /// RefID của hóa đơn mua dịch vụ
    /// </summary>
    public Guid? PuinvoiceRefId { get; set; }

    /// <summary>
    /// 0: Không kèm hóa đơn; 1: Nhận kèm hóa đơn; 2: Không có hóa đơn
    /// </summary>
    public int IncludeInvoice { get; set; }

    public string AccountObjectAddressOther { get; set; }

    public string AccountObjectIdentificationNumberOther { get; set; }

    public string TransactionId { get; set; }

    public string SellerTaxCode { get; set; }

    public int? EinvoiceType { get; set; }

    public bool IsImportEinvoice { get; set; }

    public virtual AccountObject AccountObject { get; set; }

    public virtual BankAccount BankAccount { get; set; }

    public virtual OrganizationUnit Branch { get; set; }

    public virtual Ccy Currency { get; set; }

    public virtual AccountObject Employee { get; set; }

    public virtual PaymentTerm PaymentTerm { get; set; }

    public virtual ICollection<PuserviceDetail> PuserviceDetails { get; set; } = new List<PuserviceDetail>();
}