// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ReportSigner
{
    public string TitleId { get; set; }

    public string ReportId { get; set; }

    public Guid BranchId { get; set; }

    public string Title { get; set; }

    public string SignerTitleVi { get; set; }

    public string SignerTitleEn { get; set; }

    public string SignerTitleZh { get; set; }

    public string SignerTitleKo { get; set; }

    public string SignerName { get; set; }

    public int SortOrder { get; set; }

    public bool IsShowSigner { get; set; }

    public bool IsSystem { get; set; }
}