// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ResourceInfoTempEinvoice
{
    public Guid ResourceInfoTempEinvoiceId { get; set; }

    public string? CompanyTaxCode { get; set; }

    public int? LastestInvoiceQuantity { get; set; }

    public int? TotalInvoiceQuantity { get; set; }

    public int? TotalRemainInvoiceQuantity { get; set; }

    public int? TotalUsedInvoiceQuantity { get; set; }

    public decimal? PercentRemainInvQuantity { get; set; }

    public int? NumberOfCashRegister { get; set; }

    public int? LastestCashRegisterQuantity { get; set; }

    public int? TotalUsedCashRegister { get; set; }

    public int? RemainCashRegisterQuantity { get; set; }

    public decimal? PercentRemainCashQuantity { get; set; }

    public int? NumberOfTicket { get; set; }

    public int? LastestTicketQuantity { get; set; }

    public int? TotalUsedTicket { get; set; }

    public int? RemainTicketQuantity { get; set; }

    public decimal? PercentRemainTicketQuantity { get; set; }
}