// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SainvoicePetroleumReference
{
    public Guid ReferencefId { get; set; }

    public Guid SainvoiceRefId { get; set; }

    public Guid VoucherRefId { get; set; }

    public int? VoucherRefType { get; set; }

    public int? ReferenceType { get; set; }

    public int ReferenceCreatedType { get; set; }

    public virtual SainvoicePetroleum SainvoiceRef { get; set; }
}