// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng chi tiết Hóa đơn xuất
/// </summary>
public partial class SainvoiceDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK - Cúa master Hóa đơn xuất
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã hàng
    /// </summary>
    public Guid? InventoryItemId { get; set; }

    /// <summary>
    /// Tên hàng
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Đơn vị tính
    /// </summary>
    public Guid? UnitId { get; set; }

    /// <summary>
    /// Số lượng
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// Đơn giá
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Đơn giá sau thuế
    /// </summary>
    public decimal UnitPriceAfterTax { get; set; }

    /// <summary>
    /// Thành tiền
    /// </summary>
    public decimal AmountOc { get; set; }

    /// <summary>
    /// Thành tiền QĐ
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Tỷ lệ CK
    /// </summary>
    public decimal? DiscountRate { get; set; }

    /// <summary>
    /// Tiền CK
    /// </summary>
    public decimal DiscountAmountOc { get; set; }

    /// <summary>
    /// Tiền CK QĐ
    /// </summary>
    public decimal DiscountAmount { get; set; }

    /// <summary>
    /// % thuế GTGT
    /// </summary>
    public decimal? Vatrate { get; set; }

    /// <summary>
    /// Tiền thuế GTGT
    /// </summary>
    public decimal VatamountOc { get; set; }

    /// <summary>
    /// Tiền thuế GTGT QĐ
    /// </summary>
    public decimal Vatamount { get; set; }

    /// <summary>
    /// Là hàng khuyến mại
    /// </summary>
    public bool IsPromotion { get; set; }

    /// <summary>
    /// Số thứ tự
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// ID nhóm ngành nghề
    /// </summary>
    public int? TacareerGroupId { get; set; }

    public Guid? MainUnitId { get; set; }

    public decimal MainUnitPrice { get; set; }

    public decimal MainConvertRate { get; set; }

    public decimal MainQuantity { get; set; }

    public string ExchangeRateOperator { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    public string CustomField5 { get; set; }

    public string CustomField6 { get; set; }

    public string CustomField7 { get; set; }

    public string CustomField8 { get; set; }

    public string CustomField9 { get; set; }

    public string CustomField10 { get; set; }

    public Guid? PurchasePurposeId { get; set; }

    public string Vataccount { get; set; }

    public int? TaxType { get; set; }

    public string LotNo { get; set; }

    public DateTime? ExpiryDate { get; set; }

    /// <summary>
    /// HHDV không tổng hợp trên tờ khai GTGT
    /// </summary>
    public bool NotInVatdeclaration { get; set; }

    public decimal? AmountAfterTax { get; set; }

    public Guid? SavoucherRefId { get; set; }

    public Guid? SavoucherRefDetailId { get; set; }

    public Guid? InvestmentProjectId { get; set; }

    public decimal DeductionsTaxAmount { get; set; }

    public decimal DeductionsTaxAmountOc { get; set; }

    public decimal? Vatrate406 { get; set; }

    public decimal? VatrateOther { get; set; }

    public bool IsTradeDiscount { get; set; }

    public virtual InventoryItem InventoryItem { get; set; }

    public virtual Sainvoice Ref { get; set; }

    public virtual TacareerGroup TacareerGroup { get; set; }

    public virtual Unit Unit { get; set; }
}