// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SaorderDetail
{
    public Guid RefDetailId { get; set; }

    public Guid RefId { get; set; }

    public Guid InventoryItemId { get; set; }

    public string? Description { get; set; }

    public Guid? UnitId { get; set; }

    public decimal Quantity { get; set; }

    public decimal QuantityDeliveredSa { get; set; }

    public decimal QuantityDeliveredIn { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal UnitPriceAfterTax { get; set; }

    public decimal AmountOc { get; set; }

    public decimal Amount { get; set; }

    public decimal? DiscountRate { get; set; }

    public decimal DiscountAmountOc { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal? Vatrate { get; set; }

    public decimal VatamountOc { get; set; }

    public decimal Vatamount { get; set; }

    public decimal MainQuantity { get; set; }

    public Guid? MainUnitId { get; set; }

    public decimal MainUnitPrice { get; set; }

    public decimal MainConvertRate { get; set; }

    public string ExchangeRateOperator { get; set; } = null!;

    public int SortOrder { get; set; }

    public string? CustomField1 { get; set; }

    public string? CustomField2 { get; set; }

    public string? CustomField3 { get; set; }

    public string? CustomField4 { get; set; }

    public string? CustomField5 { get; set; }

    public string? CustomField6 { get; set; }

    public string? CustomField7 { get; set; }

    public string? CustomField8 { get; set; }

    public string? CustomField9 { get; set; }

    public string? CustomField10 { get; set; }

    public Guid? SaquoteRefDetailId { get; set; }

    public Guid? ContractId { get; set; }

    public Guid? ProjectWorkId { get; set; }

    public Guid? ExpenseItemId { get; set; }

    public Guid? OrganizationUnitId { get; set; }

    public Guid? JobId { get; set; }

    public Guid? ListItemId { get; set; }

    public Guid? StockId { get; set; }

    public string? LotNo { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string? Specificity { get; set; }

    public bool? IsPromotion { get; set; }

    /// <summary>
    /// Số đã giao năm trước (Tính theo Bán hàng)
    /// </summary>
    public decimal QuantityDeliveredInlastYear { get; set; }

    /// <summary>
    /// Số đã giao năm trước (Tính theo Phiếu xuất)
    /// </summary>
    public decimal QuantityDeliveredSalastYear { get; set; }

    public decimal MainQuantityDeliveredSa { get; set; }

    public decimal MainQuantityDeliveredSalastYear { get; set; }

    public decimal MainQuantityDeliveredIn { get; set; }

    public decimal MainQuantityDeliveredInlastYear { get; set; }

    public string? GuarantyPeriod { get; set; }

    public decimal LastYearDeliveredAmountOc { get; set; }

    public decimal LastYearDeliveredAmount { get; set; }

    public decimal LastYearDeliveredBeforeTaxAmountOc { get; set; }

    public decimal LastYearDeliveredBeforeTaxAmount { get; set; }

    public decimal PanelLengthQuantity { get; set; }

    public decimal PanelWidthQuantity { get; set; }

    public decimal PanelHeightQuantity { get; set; }

    public decimal PanelRadiusQuantity { get; set; }

    public decimal PanelQuantity { get; set; }

    public Guid? ContractDetailId { get; set; }

    public decimal? VatrateOther { get; set; }

    public string? InventoryItemSource { get; set; }

    public decimal CustomFieldQuantity1 { get; set; }

    public decimal CustomFieldQuantity2 { get; set; }

    public decimal CustomFieldQuantity3 { get; set; }

    public decimal CustomFieldUnitPrice1 { get; set; }

    public decimal CustomFieldUnitPrice2 { get; set; }

    public decimal CustomFieldUnitPrice3 { get; set; }

    public decimal CustomFieldUnitPriceOc1 { get; set; }

    public decimal CustomFieldUnitPriceOc2 { get; set; }

    public decimal CustomFieldUnitPriceOc3 { get; set; }

    public decimal CustomFieldAmount1 { get; set; }

    public decimal CustomFieldAmount2 { get; set; }

    public decimal CustomFieldAmount3 { get; set; }

    public decimal CustomFieldAmountOc1 { get; set; }

    public decimal CustomFieldAmountOc2 { get; set; }

    public decimal CustomFieldAmountOc3 { get; set; }

    public DateTime? CustomFieldDateTime1 { get; set; }

    public DateTime? CustomFieldDateTime2 { get; set; }

    public DateTime? CustomFieldDateTime3 { get; set; }

    public virtual Contract? Contract { get; set; }

    public virtual ExpenseItem? ExpenseItem { get; set; }

    public virtual ICollection<IninvoiceHubOutwardDetail> IninvoiceHubOutwardDetails { get; set; } = new List<IninvoiceHubOutwardDetail>();

    public virtual ICollection<IninwardDetail> IninwardDetails { get; set; } = new List<IninwardDetail>();

    public virtual ICollection<InoutwardDetail> InoutwardDetails { get; set; } = new List<InoutwardDetail>();

    public virtual InventoryItem InventoryItem { get; set; } = null!;

    public virtual Unit? MainUnit { get; set; }

    public virtual Saorder Ref { get; set; } = null!;

    public virtual ICollection<SadiscountDetail> SadiscountDetails { get; set; } = new List<SadiscountDetail>();

    public virtual SaquoteDetail? SaquoteRefDetail { get; set; }

    public virtual ICollection<SareturnDetail> SareturnDetails { get; set; } = new List<SareturnDetail>();

    public virtual ICollection<SavoucherDetail> SavoucherDetails { get; set; } = new List<SavoucherDetail>();

    public virtual Unit? Unit { get; set; }
}