// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng chứa danh sách các khách hàng trong từng nhóm của một chính sách giá
/// </summary>
public partial class SapolicySaleCustomer
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid SapolicySaleCustomerId { get; set; }

    /// <summary>
    /// Nhóm giá bán
    /// </summary>
    public Guid SapolicySaleGroupId { get; set; }

    /// <summary>
    /// Đối tượng
    /// </summary>
    public Guid AccountObjectId { get; set; }

    /// <summary>
    /// ID của Chính sách giá. Lưu lại cho dễ dàng query ra các Khách hàng được áp dụng chính sách giá
    /// </summary>
    public Guid? SapolicyId { get; set; }

    public virtual AccountObject AccountObject { get; set; } = null!;

    public virtual SapolicySaleGroup SapolicySaleGroup { get; set; } = null!;
}