// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng Hàng bán trả lại
/// </summary>
public partial class Sareturn
{
    public Guid RefId { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public Guid BranchId { get; set; }

    /// <summary>
    /// Xác định chứng từ được ghi vào sổ nào (0=Sổ tài chinh;1=Sổ quản trị;2=Cả hai)
    /// </summary>
    public int? DisplayOnBook { get; set; }

    /// <summary>
    /// Loại chứng từ
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime RefDate { get; set; }

    /// <summary>
    /// Ngày hạch toán
    /// </summary>
    public DateTime PostedDate { get; set; }

    /// <summary>
    /// Số chứng từ Phiếu chi/Chứng từ ghi giảm công nợ (sổ tài chính)
    /// </summary>
    public string RefNoFinance { get; set; }

    /// <summary>
    /// Số chứng từ  Phiếu chi/Chứng từ ghi giảm công nợ (sổ quản trị)
    /// </summary>
    public string RefNoManagement { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ Sổ tài chính
    /// </summary>
    public bool IsPostedFinance { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ Sổ quản trị
    /// </summary>
    public bool IsPostedManagement { get; set; }

    /// <summary>
    /// ID của hóa đơn nhận
    /// </summary>
    public Guid? PuinvoiceRefId { get; set; }

    /// <summary>
    /// Khách hàng
    /// </summary>
    public Guid? AccountObjectId { get; set; }

    /// <summary>
    /// Tên khách hàng
    /// </summary>
    public string AccountObjectName { get; set; }

    /// <summary>
    /// Địa chỉ khách hàng
    /// </summary>
    public string AccountObjectAddress { get; set; }

    /// <summary>
    /// Người nhận
    /// </summary>
    public string Receiver { get; set; }

    /// <summary>
    /// Diễn giải/Lý do chi
    /// </summary>
    public string JournalMemo { get; set; }

    /// <summary>
    /// Đơn vị giao đại lý/Đơn vị ủy thác
    /// </summary>
    public Guid? SupplierId { get; set; }

    /// <summary>
    /// Tên đơn vị giao đại lý/Đơn vị ủy thác
    /// </summary>
    public string SupplierName { get; set; }

    /// <summary>
    /// Loại tiền
    /// </summary>
    public string CurrencyId { get; set; }

    /// <summary>
    /// Tỉ giá hối đoái
    /// </summary>
    public decimal? ExchangeRate { get; set; }

    /// <summary>
    /// Nhân viên bán hàng
    /// </summary>
    public Guid? EmployeeId { get; set; }

    /// <summary>
    /// Tài liệu kèm theo
    /// </summary>
    public string DocumentIncluded { get; set; }

    /// <summary>
    /// Tổng tiền của hóa đơn chưa có thuế
    /// </summary>
    public decimal TotalSaleAmountOc { get; set; }

    /// <summary>
    /// Tổng tiền quy đổi của hóa đơn chưa có thuế
    /// </summary>
    public decimal TotalSaleAmount { get; set; }

    /// <summary>
    /// Tổng tiền thuế thuế NT
    /// </summary>
    public decimal? TotalVatamountOc { get; set; }

    /// <summary>
    /// Tổng tiền thuế quy đổi
    /// </summary>
    public decimal TotalVatamount { get; set; }

    /// <summary>
    /// Tổng tiền chiết khấu
    /// </summary>
    public decimal TotalDiscountAmountOc { get; set; }

    /// <summary>
    /// Tổng tiền chiết khấu quy đổi
    /// </summary>
    public decimal TotalDiscountAmount { get; set; }

    /// <summary>
    /// Tổng tiền =TotalSaleAmountOC+TotalTaxAmountOC- TotalDiscountAmountOC
    /// </summary>
    public decimal TotalAmountOc { get; set; }

    /// <summary>
    /// Tổng tiền quy đổi=TotalSaleAmount+TotalTaxAmount- TotalDiscountAmount
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ thủ quỹ (Sổ tài chính)
    /// </summary>
    public bool? IsPostedCashBookFinance { get; set; }

    /// <summary>
    /// Trạng thái ghi sổ thủ quỹ (Sổ quản trị)
    /// </summary>
    public bool? IsPostedCashBookManagement { get; set; }

    /// <summary>
    /// Ngày ghi sổ thủ quỹ
    /// </summary>
    public DateTime? CashBookPostedDate { get; set; }

    /// <summary>
    /// EditVersion
    /// </summary>
    public byte[] EditVersion { get; set; }

    /// <summary>
    /// Số thứ tự nhập chứng từ
    /// </summary>
    public int RefOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    public string CustomField5 { get; set; }

    public string CustomField6 { get; set; }

    public string CustomField7 { get; set; }

    public string CustomField8 { get; set; }

    public string CustomField9 { get; set; }

    public string CustomField10 { get; set; }

    public decimal CabaamountOc { get; set; }

    public decimal Cabaamount { get; set; }

    public string InvNo { get; set; }

    public DateTime? InvDate { get; set; }

    public string InvSeries { get; set; }

    public bool IsReturnWithInward { get; set; }

    public Guid? IninwardRefId { get; set; }

    /// <summary>
    /// Đã lập phiếu nhập năm trước
    /// </summary>
    public bool IsCreatedIninwardLastYear { get; set; }

    public string RefIdmshop { get; set; }

    public string RefNoMshop { get; set; }

    public virtual AccountObject AccountObject { get; set; }

    public virtual OrganizationUnit Branch { get; set; }

    public virtual Ccy Currency { get; set; }

    public virtual AccountObject Employee { get; set; }

    public virtual ICollection<Ininward> Ininwards { get; set; } = new List<Ininward>();

    public virtual Puinvoice PuinvoiceRef { get; set; }

    public virtual ICollection<SareturnDetail> SareturnDetails { get; set; } = new List<SareturnDetail>();

    public virtual AccountObject Supplier { get; set; }
}