// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng danh mục Nhóm giá bán
/// </summary>
public partial class SasaleGroup
{
    public Guid SasaleGroupId { get; set; }

    /// <summary>
    /// Mã số nhóm giá bán
    /// </summary>
    public string SaleGroupCode { get; set; }

    /// <summary>
    /// Tên nhóm giá bán
    /// </summary>
    public string SaleGroupName { get; set; }

    /// <summary>
    /// Mô tả các thông tin của nhóm giá bán
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Ngừng theo dõi
    /// </summary>
    public bool Inactive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual ICollection<SasaleGroupDetail> SasaleGroupDetails { get; set; } = new List<SasaleGroupDetail>();
}