// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class ScheduleAppointment
{
    public Guid AppointmentId { get; set; }

    public string Subject { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? AllDayEvent { get; set; }

    public bool? IsReminder { get; set; }

    public int? ReminderBeforeStart { get; set; }

    public byte[]? ReminderSoundFile { get; set; }

    public Guid? OwnerId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public byte[]? AllOtherProperties { get; set; }

    public string? Location { get; set; }

    public string? OwnerLoginName { get; set; }

    public bool? IsRemindAllUser { get; set; }
}