// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SsbussinessUserActived
{
    public Guid SsbussinessUserActivedId { get; set; }

    public Guid SsbussinessId { get; set; }

    public Guid UserId { get; set; }

    public DateTime? CreatedDate { get; set; }
}