// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SsbussinessDetail
{
    public Guid SsbussinessDetailId { get; set; }

    public Guid SsbussinessId { get; set; }

    /// <summary>
    /// Từ khóa tìm kiếm
    /// </summary>
    public Guid SskeywordId { get; set; }

    public virtual Ssbussiness Ssbussiness { get; set; }

    public virtual Sskeyword Sskeyword { get; set; }
}