// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Sskeyword
{
    public Guid SskeywordId { get; set; }

    /// <summary>
    /// Từ khóa nghiệp vụ
    /// </summary>
    public string Value { get; set; }

    public string UnsignValue { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<SsbussinessDetail> SsbussinessDetails { get; set; } = new List<SsbussinessDetail>();
}