// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SslastedAction
{
    public Guid SslastedActionId { get; set; }

    /// <summary>
    /// Nghiệp vụ gần nhất
    /// </summary>
    public Guid? SsbussinessId { get; set; }

    public DateTime? Time { get; set; }

    /// <summary>
    /// Người dùng tìm kiếm
    /// </summary>
    public Guid? UserId { get; set; }
}