// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết điều chỉnh CCDC
/// </summary>
public partial class SuadjustmentDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã CCCDC
    /// </summary>
    public Guid SupplyId { get; set; }

    /// <summary>
    /// Số lượng
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// Tài khoản chờ phân bổ
    /// </summary>
    public string? AllocationAccount { get; set; }

    /// <summary>
    /// Giá trị còn lại TRƯỚC điều chỉnh
    /// </summary>
    public decimal CurrentRemainingAmount { get; set; }

    /// <summary>
    /// Giá trị còn lại SAU điều chỉnh
    /// </summary>
    public decimal NewRemainingAmount { get; set; }

    /// <summary>
    /// Số kỳ phân bổ còn lại TRƯỚC điều chỉnh
    /// </summary>
    public int CurrentRemainingAllocationTime { get; set; }

    /// <summary>
    /// Số kỳ phân bổ còn lại SAU điều chỉnh
    /// </summary>
    public int NewRemainingAllocationTime { get; set; }

    /// <summary>
    /// Số tiền phân bổ hàng kỳ
    /// </summary>
    public decimal TermlyAllocationAmount { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string? Note { get; set; }

    /// <summary>
    /// Thứ tự sắp xếp các dòng chi tiết
    /// </summary>
    public int? SortOrder { get; set; }

    /// <summary>
    /// Chênh lệch giá trị còn lại
    /// </summary>
    public decimal DiffRemainingAmount { get; set; }

    /// <summary>
    /// Chênh lệch số kỳ phân bổ
    /// </summary>
    public decimal DiffAllocationTime { get; set; }

    public virtual Account? AllocationAccountNavigation { get; set; }

    public virtual Suadjustment Ref { get; set; } = null!;

    public virtual Suincrement Supply { get; set; } = null!;
}