// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng Master: Phân bổ công cụ dụng cụ
/// </summary>
public partial class Suallocation
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Loại chứng từ
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Ngày chứng từ
    /// </summary>
    public DateTime? RefDate { get; set; }

    /// <summary>
    /// Ngày hạch toán
    /// </summary>
    public DateTime? PostedDate { get; set; }

    /// <summary>
    /// Số chứng từ
    /// </summary>
    public string RefNo { get; set; } = null!;

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string? JournalMemo { get; set; }

    /// <summary>
    /// Tháng
    /// </summary>
    public int Month { get; set; }

    /// <summary>
    /// Năm
    /// </summary>
    public int Year { get; set; }

    /// <summary>
    /// Tổng tiền phân bổ quy đổi
    /// </summary>
    public decimal TotalAmount { get; set; }

    public Guid? BranchId { get; set; }

    /// <summary>
    /// Ghi vào sổ quản trị
    /// </summary>
    public bool IsPostedManagement { get; set; }

    /// <summary>
    /// 0=Sổ tài chinh;1=Sổ quản trị
    /// </summary>
    public int DisplayOnBook { get; set; }

    /// <summary>
    /// EditVersion
    /// </summary>
    public byte[]? EditVersion { get; set; }

    /// <summary>
    /// Số thứ tự nhập chứng từ
    /// </summary>
    public int RefOrder { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    /// <summary>
    /// Ghi vào sổ tài chính
    /// </summary>
    public bool IsPostedFinance { get; set; }

    public bool? IsGetSupplyAllocated { get; set; }

    public virtual OrganizationUnit? Branch { get; set; }

    public virtual ICollection<SuallocationDetailExpense> SuallocationDetailExpenses { get; set; } = new List<SuallocationDetailExpense>();

    public virtual ICollection<SuallocationDetailPost> SuallocationDetailPosts { get; set; } = new List<SuallocationDetailPost>();

    public virtual ICollection<SuallocationDetailTable> SuallocationDetailTables { get; set; } = new List<SuallocationDetailTable>();
}