// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết kiểm kê
/// </summary>
public partial class SuauditDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã CCDC
    /// </summary>
    public Guid SupplyId { get; set; }

    /// <summary>
    /// Đơn vị sử dụng
    /// </summary>
    public Guid OrganizationUnitId { get; set; }

    /// <summary>
    /// Số lượng trên số kế toán
    /// </summary>
    public decimal QuantityOnBook { get; set; }

    /// <summary>
    /// Số lượng kiểm kê
    /// </summary>
    public decimal QuantityInventory { get; set; }

    /// <summary>
    /// Số lượng chênh lệch
    /// </summary>
    public decimal DiffQuantity { get; set; }

    /// <summary>
    /// Số lượng còn tốt
    /// </summary>
    public decimal GoodQuantity { get; set; }

    /// <summary>
    /// Số lượng bị hỏng
    /// </summary>
    public decimal DamageQuantity { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string? Note { get; set; }

    /// <summary>
    /// Số thứ tự dòng
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Số lượng xử lý
    /// </summary>
    public decimal ExecuteQuantity { get; set; }

    /// <summary>
    /// Hành động: 0 = Ghi tăng; 1 = Ghi giảm; 2: Không xử lý
    /// </summary>
    public int Action { get; set; }

    public virtual OrganizationUnit OrganizationUnit { get; set; } = null!;

    public virtual Suaudit Ref { get; set; } = null!;

    public virtual Suincrement Supply { get; set; } = null!;
}