// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết ghi giảm CCDC
/// </summary>
public partial class SudecrementDetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// Mã CCDC
    /// </summary>
    public Guid? SupplyId { get; set; }

    /// <summary>
    /// Đơn vị sử dụng
    /// </summary>
    public Guid? OrganizationUnitId { get; set; }

    /// <summary>
    /// Số lượng đang dùng
    /// </summary>
    public decimal UseQuantity { get; set; }

    /// <summary>
    /// Số lượng ghi giảm
    /// </summary>
    public decimal DecrementQuantity { get; set; }

    /// <summary>
    /// giá trị ghi giảm
    /// </summary>
    public decimal DecrementAmount { get; set; }

    /// <summary>
    /// Giá trị còn lại của CCDC giảm
    /// </summary>
    public decimal RemainingDecrementAmount { get; set; }

    /// <summary>
    /// Lý do ghi giảm
    /// </summary>
    public string Reason { get; set; }

    /// <summary>
    /// Số thứ tự dòng
    /// </summary>
    public int? SortOrder { get; set; }

    public Guid? SuallocationId { get; set; }

    public Guid? SuauditRefId { get; set; }

    public virtual OrganizationUnit OrganizationUnit { get; set; }

    public virtual Sudecrement Ref { get; set; }

    public virtual Suincrement Supply { get; set; }
}