// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết đơn vị sử dụng
/// </summary>
public partial class SuincrementDetailDepartment
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid SupplyDetailId { get; set; }

    /// <summary>
    /// FK
    /// </summary>
    public Guid SupplyId { get; set; }

    /// <summary>
    /// Đơn vị sử dụng
    /// </summary>
    public Guid OrganizationUnitId { get; set; }

    public int SortOrder { get; set; }

    /// <summary>
    /// Số lượng
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// Đơn giá
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Thành tiền/Giá trị CCDC
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Mẹo: lấy AllocationTime trên master vào dòng đầu tiên (Phục vụ ghi sổ)
    /// </summary>
    public int AllocationTime { get; set; }

    /// <summary>
    /// Mẹo: lấy RemainingAllocationTime trên master vào dòng đầu tiên (Phục vụ ghi sổ)
    /// </summary>
    public int RemainingAllocationTime { get; set; }

    public decimal AllocatedAmount { get; set; }

    public virtual OrganizationUnit OrganizationUnit { get; set; } = null!;

    public virtual Suincrement Supply { get; set; } = null!;
}