// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysaddNewDefaultValue
{
    public Guid DefaultId { get; set; }

    public string DefaultCode { get; set; }

    public string RefTypeList { get; set; }

    public string KeyList { get; set; }

    public string DefaultValue { get; set; }

    public Guid? UserId { get; set; }

    public int? DisplayOnBook { get; set; }
}