// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysbusinessScaleHiden
{
    public int SysbusinessScaleVisibleId { get; set; }

    public string OptionVisibleBusiness { get; set; }

    public int BussinessScaleId { get; set; }
}