// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysconvertMappingValidate
{
    public Guid SysconvertMappingValidateId { get; set; }

    public int ValidateType { get; set; }

    public string? TargetTableName { get; set; }

    public string? ExceptionMessage { get; set; }

    public string Description { get; set; } = null!;

    public int SortOrder { get; set; }

    public string? Example { get; set; }
}