// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysconvertMappingTable
{
    public Guid SysconvertMappingTableId { get; set; }

    public string TargetTableName { get; set; } = null!;

    public int ConvertOrder { get; set; }

    public int TableConfigType { get; set; }

    public string? Value { get; set; }

    public string? SourceCondition { get; set; }

    public string? Description { get; set; }

    public string? SourceOtherTableName { get; set; }

    public string? JoinCondition { get; set; }

    public string? TargetCodeColumnName { get; set; }

    public string? SourceCodeColumnDescription { get; set; }

    public string? JoinConditionTemp { get; set; }

    public int JoinType { get; set; }

    public string? DeleteTargetCondition { get; set; }

    public int ConfigType { get; set; }
}