// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysconvertMappingColumn
{
    public Guid SysconvertMappingColumnId { get; set; }

    public string TargetTableName { get; set; } = null!;

    public string TargetColumnName { get; set; } = null!;

    public int ColumnConfigType { get; set; }

    public string? Value { get; set; }

    public int ConvertOrder { get; set; }

    public string? DefaultValue { get; set; }

    public string? SourceCondition { get; set; }

    public string SourceTableName { get; set; } = null!;

    public string? Description { get; set; }

    public string? TargetColumnDescription { get; set; }

    public int GetValueFromSourceOtherTable { get; set; }

    public int ConfigType { get; set; }
}