// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysgroupMultiLog
{
    public Guid Id { get; set; }

    public Guid? OldObjectId { get; set; }

    public Guid? NewObjectId { get; set; }

    public DateTime? LogTime { get; set; }

    public int? LogType { get; set; }
}