// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SyslayoutLanguage
{
    public Guid SyslayoutLanguageId { get; set; }

    public Guid? FkeyId { get; set; }

    public string LanguageId { get; set; }

    public string TemplateConfigLanguage { get; set; }
}