// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SyslayoutMemorized
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid SyslayoutMemorizedId { get; set; }

    /// <summary>
    /// ID on SYSLayoutTemplate
    /// </summary>
    public Guid? LayoutId { get; set; }

    /// <summary>
    /// ID on MSCUser
    /// </summary>
    public Guid? UserId { get; set; }

    public virtual SyslistLayoutTemplate? Layout { get; set; }
}