// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysNewPostedVoucher
{
    public Guid? PostId { get; set; }

    public int? PostType { get; set; }

    public bool? IsPostToManagementBook { get; set; }

    public Guid? RefId { get; set; }

    public int? RefType { get; set; }

    public DateTime? PostedDate { get; set; }

    public string RefNoFinance { get; set; }

    public string RefNoManagement { get; set; }

    public DateTime? CreatedDate { get; set; }
}