// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng này phục vụ định nghĩa sự khác nhau giữa các dòng trong trường hợp có &gt;1 dòng được thiết lập trên bảng SYSPostMappingRow. Chú ý: quan hệ với SYSPostMappingRow k phải quan hệ master-detail
/// </summary>
public partial class SyspostMappingRowDetail
{
    /// <summary>
    /// Khóa
    /// </summary>
    public Guid SyspostMappingRowDetailId { get; set; }

    /// <summary>
    /// Thứ tự dòng
    /// </summary>
    public int IndexRow { get; set; }

    /// <summary>
    /// Tên sổ
    /// </summary>
    public string LedgerTableName { get; set; } = null!;

    /// <summary>
    /// Tên cột Trên sổ
    /// </summary>
    public string ColumnNameInLedger { get; set; } = null!;

    /// <summary>
    /// Thông tin được config trên bảng SYSPostMappingRow
    /// </summary>
    public string? ValueInSyspostMappingRow { get; set; }

    /// <summary>
    /// Kiểu config, định nghĩa trên EnumPostConfigType của chương trình
    /// </summary>
    public int ConfigType { get; set; }

    public int PostToBookType { get; set; }

    public bool? IsCheckCondition { get; set; }

    public string? MasterAllCondition { get; set; }

    public string? MasterCondition { get; set; }

    public string? DetailCondition { get; set; }
}