// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysquickEditPostConfig
{
    public Guid ConfigId { get; set; }

    public string LedgerTableName { get; set; }

    public string MasterTableName { get; set; }

    public string DetailTableName { get; set; }

    public string FilterCondition { get; set; }

    public string ColumnNameInLedger { get; set; }

    public string Value { get; set; }

    public bool? IsMaster { get; set; }

    public int? ConfigType { get; set; }
}