// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysquickEditTableConfig
{
    public Guid ConfigId { get; set; }

    public string? RefTypeList { get; set; }

    public string? TableName { get; set; }

    public bool IsMaster { get; set; }

    public string? ColumnId { get; set; }

    public string? ColumnCode { get; set; }

    public string? FilterCondition { get; set; }

    public string? Description { get; set; }
}