// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysreportOrder
{
    public string OrderId { get; set; }

    public string ReportId { get; set; }

    public int RefType { get; set; }

    public int SortOrder { get; set; }

    public virtual SysreportList Report { get; set; }
}