// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class SysvoucherTemplate
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid LayoutId { get; set; }

    /// <summary>
    /// Tên của mẫu
    /// </summary>
    public string LayoutName { get; set; } = null!;

    /// <summary>
    /// Loại chứng từ
    /// </summary>
    public int RefType { get; set; }

    /// <summary>
    /// Với mỗi RefType sẽ có các loại khác để hiển thị giao diện. Ví dụ trên phân hệ Quỹ, Ngân hàng là Lý do thu,chi
    /// </summary>
    public byte? VoucherType { get; set; }

    /// <summary>
    /// ID của người dùng. Nếu NULL thì là mẫu ngầm định
    /// </summary>
    public Guid? UserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    /// <summary>
    /// Tên loại chứng từ
    /// </summary>
    public string? RefTypeName { get; set; }

    public bool? IsPublic { get; set; }

    public bool? IsSystem { get; set; }

    public virtual ICollection<SysvoucherTemplateDetail> SysvoucherTemplateDetails { get; set; } = new List<SysvoucherTemplateDetail>();
}