// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Ta011ttdbDetailTt195
{
    public Guid RefDetailId { get; set; }

    public Guid RefId { get; set; }

    public Guid AppendixId { get; set; }

    public string InvSeries { get; set; }

    public string InvNo { get; set; }

    public DateTime? InvDate { get; set; }

    public string InventoryItemName { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? SpecialTaxAmount { get; set; }

    public decimal? SpecialTaxAmountOnUnit { get; set; }

    public decimal? DeductTaxAmount { get; set; }

    public decimal? RemainingTaxAmount { get; set; }

    public string ProductName { get; set; }

    public decimal? QuantityOnUnit { get; set; }

    public string GroupName { get; set; }

    public int? SortOrder { get; set; }

    public decimal? TotalDeductSpecialTaxAmount { get; set; }

    public virtual TadeclarationAppendix Appendix { get; set; }
}