// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng giải trình khai bổ sung điều chỉnh
/// </summary>
public partial class TaadjustmentDetail
{
    /// <summary>
    /// Khóa chính
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// ID tờ khai
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// ID phụ lục
    /// </summary>
    public Guid AppendixId { get; set; }

    /// <summary>
    /// Tên chỉ tiêu
    /// </summary>
    public string? DescriptionName { get; set; }

    /// <summary>
    /// Mã số chỉ tiêu
    /// </summary>
    public string? Code { get; set; }

    /// <summary>
    /// Số đã kê khai
    /// </summary>
    public decimal OrgAmount { get; set; }

    /// <summary>
    /// Số điều chỉnh
    /// </summary>
    public decimal AdjustAmount { get; set; }

    /// <summary>
    /// Chênh lệch
    /// </summary>
    public decimal? DiffAmount { get; set; }

    /// <summary>
    /// Phần : Phần I, phần II, Phần III của  bản giải trình
    /// </summary>
    public string? GroupName { get; set; }

    public int SortOrder { get; set; }

    public string? SubsectionName { get; set; }

    public decimal? DitaxAmount { get; set; }

    public decimal? AdjustTaxLiability { get; set; }

    public string? Reason { get; set; }

    public string? SortOrderText { get; set; }

    public string? SubsectionCode { get; set; }

    public string? OrgValue { get; set; }

    public string? AdjustValue { get; set; }

    public int? SortOrderCode { get; set; }

    public string? CustomField1 { get; set; }

    public virtual Tadeclaration Ref { get; set; } = null!;
}