// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class TaadjustmentDetail01
{
    public Guid RefDetailId { get; set; }

    public Guid RefId { get; set; }

    public Guid AppendixId { get; set; }

    public int SortOrder { get; set; }

    public string PlaceName { get; set; }

    public string PlaceTaxCode { get; set; }

    public string ProvinceOrCityId { get; set; }

    public string ProvinceOrCity { get; set; }

    public string DistrictId { get; set; }

    public string District { get; set; }

    public string TaxCompanyId { get; set; }

    public string TaxCompanyName { get; set; }

    public string TaxCompanyDecisionId { get; set; }

    public string TaxCompanyDecisionName { get; set; }

    public decimal? TaxAmount { get; set; }

    public string GroupName { get; set; }

    public virtual Tadeclaration Ref { get; set; }
}