// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class TaadditionalDeclarationItem
{
    public int? RefType { get; set; }

    public string? ItemCodeKey { get; set; }

    public string? ItemCodeValue { get; set; }

    public string? ItemNameValue { get; set; }
}