// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết Báo cáo tình hình sử dung hóa đơn
/// </summary>
public partial class TaBc26acInvoiceStatementDetail
{
    /// <summary>
    /// Khóa chính
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// Khóa ngoại
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// ID của loại hóa đơn từ 1 -&gt; 6
    /// </summary>
    public int? InvTypeId { get; set; }

    /// <summary>
    /// Tên loại hóa đơn
    /// </summary>
    public string InvTypeName { get; set; }

    /// <summary>
    /// Mẫu số
    /// </summary>
    public string InvoiceTemplate { get; set; }

    /// <summary>
    /// Ký hiệu
    /// </summary>
    public string InvSeries { get; set; }

    /// <summary>
    /// Tổng số tồn đầu kỳ, mua, phát hành trong kỳ
    /// </summary>
    public decimal? TotalOpenQuantity { get; set; }

    /// <summary>
    /// Tồn đầu kỳ - Từ số
    /// </summary>
    public string OpeningFromInvNo { get; set; }

    /// <summary>
    /// Tồn đầu kỳ - Đến số
    /// </summary>
    public string OpeningToInvNo { get; set; }

    /// <summary>
    /// Mua, phát hành trong kỳ - Từ số
    /// </summary>
    public string IssueFromInvNo { get; set; }

    /// <summary>
    /// Mua, phát hành trong kỳ - Đến số
    /// </summary>
    public string IssueToInvNo { get; set; }

    /// <summary>
    /// Tổng số sử dụng, xóa bỏ, mất, hủy - Từ số
    /// </summary>
    public string TotalUsedFromInvNo { get; set; }

    /// <summary>
    /// Tổng số sử dụng, xóa bỏ, mất, hủy - Đến số
    /// </summary>
    public string TotalUsedToInvNo { get; set; }

    /// <summary>
    /// Tổng số sử dụng, xóa bỏ, mất, hủy - Cộng
    /// </summary>
    public decimal? TotalUsedQuantity { get; set; }

    /// <summary>
    /// Số sử dụng trong kỳ
    /// </summary>
    public decimal? UsedQuantity { get; set; }

    /// <summary>
    /// Tổng số lượng hóa đơn xóa
    /// </summary>
    public decimal? DeletedQuantity { get; set; }

    /// <summary>
    /// Số hóa đơn xóa
    /// </summary>
    public string DeletedInvNo { get; set; }

    /// <summary>
    /// Tổng số lượng hóa đơn Mất, cháy, hỏng
    /// </summary>
    public decimal? LostQuantity { get; set; }

    /// <summary>
    /// Số hóa đơn Mất, cháy, hỏng
    /// </summary>
    public string LostInvNo { get; set; }

    /// <summary>
    /// Tổng số lượng hóa đơn Hủy
    /// </summary>
    public decimal? CancelQuantity { get; set; }

    /// <summary>
    /// Số hóa đơn Hủy
    /// </summary>
    public string CancelInvNo { get; set; }

    /// <summary>
    /// Tồn cuối kỳ - Từ số
    /// </summary>
    public string ClosingFromInvNo { get; set; }

    /// <summary>
    /// Tồn cuối kỳ - Đến số
    /// </summary>
    public string ClosingToInvNo { get; set; }

    /// <summary>
    /// Tồn cuối kỳ - Số lượng
    /// </summary>
    public decimal? TotalClosingQuantity { get; set; }

    /// <summary>
    /// Số thứ tự
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Mã loại hóa đơn
    /// </summary>
    public string InvTypeCode { get; set; }

    public virtual TaBc26acInvoiceStatement Ref { get; set; }
}