// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class TachangedateLunarAndSolar
{
    public string? DateLunar { get; set; }

    public DateTime? DateSolar { get; set; }

    public int SortOrder { get; set; }

    public int Type { get; set; }

    public int? Year { get; set; }
}