// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu trữ các phụ lục được kê khai
/// </summary>
public partial class TadeclarationAppendix
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid AppendixId { get; set; }

    /// <summary>
    /// ID tờ  khai
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// ID loại phụ lục
    /// </summary>
    public Guid? AppendixTypeId { get; set; }

    public virtual TaappendixType? AppendixType { get; set; }

    public virtual Tadeclaration Ref { get; set; } = null!;

    public virtual ICollection<Ta011gtgtDetail> Ta011gtgtDetails { get; set; } = new List<Ta011gtgtDetail>();

    public virtual ICollection<Ta011tndnDetail> Ta011tndnDetails { get; set; } = new List<Ta011tndnDetail>();

    public virtual ICollection<Ta011ttdbDetailTt195> Ta011ttdbDetailTt195s { get; set; } = new List<Ta011ttdbDetailTt195>();

    public virtual ICollection<Ta011ttdbDetail> Ta011ttdbDetails { get; set; } = new List<Ta011ttdbDetail>();

    public virtual ICollection<Ta012gtgtDetail> Ta012gtgtDetails { get; set; } = new List<Ta012gtgtDetail>();

    public virtual ICollection<Ta012ttdbDetailTt80> Ta012ttdbDetailTt80s { get; set; } = new List<Ta012ttdbDetailTt80>();

    public virtual ICollection<Ta012ttdbDetail> Ta012ttdbDetails { get; set; } = new List<Ta012ttdbDetail>();

    public virtual ICollection<Ta015gtgtDetail> Ta015gtgtDetails { get; set; } = new List<Ta015gtgtDetail>();

    public virtual ICollection<Ta016gtgtDetail> Ta016gtgtDetails { get; set; } = new List<Ta016gtgtDetail>();

    public virtual ICollection<Ta017gtgtDetail> Ta017gtgtDetails { get; set; } = new List<Ta017gtgtDetail>();

    public virtual ICollection<Ta01ttdbDetail> Ta01ttdbDetails { get; set; } = new List<Ta01ttdbDetail>();

    public virtual ICollection<Ta02gtgtAppendixDetail> Ta02gtgtAppendixDetails { get; set; } = new List<Ta02gtgtAppendixDetail>();

    public virtual ICollection<Ta03tndn114detail> Ta03tndn114details { get; set; } = new List<Ta03tndn114detail>();

    public virtual ICollection<Ta03tndn1adetail> Ta03tndn1adetails { get; set; } = new List<Ta03tndn1adetail>();

    public virtual ICollection<Ta03tndn2adetail> Ta03tndn2adetails { get; set; } = new List<Ta03tndn2adetail>();

    public virtual ICollection<Ta03tndn5detail> Ta03tndn5details { get; set; } = new List<Ta03tndn5detail>();

    public virtual ICollection<Ta03tndn8detail> Ta03tndn8details { get; set; } = new List<Ta03tndn8detail>();

    public virtual ICollection<Ta03tndn92detail> Ta03tndn92details { get; set; } = new List<Ta03tndn92detail>();

    public virtual ICollection<Ta041gtgtDetail> Ta041gtgtDetails { get; set; } = new List<Ta041gtgtDetail>();

    public virtual ICollection<Ta05qttncn01DetailTt80> Ta05qttncn01DetailTt80s { get; set; } = new List<Ta05qttncn01DetailTt80>();

    public virtual ICollection<Ta05qttncn01Detail> Ta05qttncn01Details { get; set; } = new List<Ta05qttncn01Detail>();

    public virtual ICollection<Ta05qttncn02DetailTt80> Ta05qttncn02DetailTt80s { get; set; } = new List<Ta05qttncn02DetailTt80>();

    public virtual ICollection<Ta05qttncn02Detail> Ta05qttncn02Details { get; set; } = new List<Ta05qttncn02Detail>();

    public virtual ICollection<Ta05qttncn03DetailTt80> Ta05qttncn03DetailTt80s { get; set; } = new List<Ta05qttncn03DetailTt80>();

    public virtual ICollection<Ta05qttncn03Detail> Ta05qttncn03Details { get; set; } = new List<Ta05qttncn03Detail>();

    public virtual ICollection<TaPlii922021ndcpDetail> TaPlii922021ndcpDetails { get; set; } = new List<TaPlii922021ndcpDetail>();

    public virtual ICollection<TaTncn051bkdetail> TaTncn051bkdetails { get; set; } = new List<TaTncn051bkdetail>();

    public virtual ICollection<TaTncn052bkdetail> TaTncn052bkdetails { get; set; } = new List<TaTncn052bkdetail>();
}