// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Tanotification
{
    public string Id { get; set; }

    public string SubmissionId { get; set; }

    public string SubmissionCode { get; set; }

    public string TaxCode { get; set; }

    public string Reason { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? Status { get; set; }

    public string FilePath { get; set; }

    public string FileContent { get; set; }
}