// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class TapaymentSlip
{
    public string SubmissionId { get; set; }

    public string TaxCode { get; set; }

    public string BankPaymentCode { get; set; }

    public string ContentPayStateBudger { get; set; }

    public string AuthorizingTaxCode { get; set; }

    public string TypeMoney { get; set; }

    public decimal? TotalMoney { get; set; }

    public string PayerBankName { get; set; }

    public string OrgCollectTaxAgentName { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }
}