// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Chi tiết tờ khai thuế tài nguyên, mẫu 01/TAIN và 02/TAIN
/// </summary>
public partial class TaTaindetail
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid RefDetailId { get; set; }

    /// <summary>
    /// FK - ID của tờ khai thuế
    /// </summary>
    public Guid RefId { get; set; }

    /// <summary>
    /// ID phụ lục
    /// </summary>
    public Guid AppendixId { get; set; }

    /// <summary>
    /// Số thứ tự
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Tên loại tài nguyên
    /// </summary>
    public string ResourcesCategoryName { get; set; }

    /// <summary>
    /// Đon vị tính
    /// </summary>
    public string Unit { get; set; }

    /// <summary>
    /// Sản lượng
    /// </summary>
    public decimal Output { get; set; }

    /// <summary>
    /// Giá tính thuế đơn vị tài nguyên
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Thuế suất
    /// </summary>
    public decimal TaxRate { get; set; }

    /// <summary>
    /// Mức thuế tài nguyên ấn định/1 đơn vị tài nguyên
    /// </summary>
    public decimal UnitTaxAmountLevel { get; set; }

    /// <summary>
    /// Thuế tài nguyên phát sinh trong kỳ
    /// </summary>
    public decimal TaxAmountMovement { get; set; }

    /// <summary>
    /// Thuế tài nguyên dự kiến được miễn giảm trong kỳ
    /// </summary>
    public decimal TaxAmountDeductionExpectation { get; set; }

    /// <summary>
    /// Thuế tài nguyên phát sinh phải nộp trong kỳ
    /// </summary>
    public decimal TaxAmount { get; set; }

    /// <summary>
    /// Thuế tài nguyên đã kê khai trong kỳ
    /// </summary>
    public decimal? PaidTaxAmount { get; set; }

    /// <summary>
    /// Chênh lệch giữa số quyết toán với kê khai
    /// </summary>
    public decimal? DiffAmount { get; set; }

    /// <summary>
    /// Nhóm I, II, III
    /// </summary>
    public string GroupName { get; set; }

    public string ResourcesTaxTableCode { get; set; }

    public string SortOrderText { get; set; }

    public virtual Tadeclaration Ref { get; set; }
}