// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

public partial class Tatemplate
{
    public Guid TemplateId { get; set; }

    public string DecisionId { get; set; }

    public string Description { get; set; }

    public int RefType { get; set; }

    public byte[] Template { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<Tadeclaration> Tadeclarations { get; set; } = new List<Tadeclaration>();
}