// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Bảng lưu các giá trị thuế suất GTGT
/// </summary>
public partial class TaxRate
{
    public decimal TaxRateValue { get; set; }

    public string TaxRateName { get; set; }
}