// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.MisaDbContext;

/// <summary>
/// Loại chứng từ
/// </summary>
public partial class VoucherType
{
    /// <summary>
    /// PK của bảng
    /// </summary>
    public Guid VoucherTypeId { get; set; }

    /// <summary>
    /// Phát sinh theo. 0: Phát sinh theo TK; 1: Phát sinh theo nhóm chứng từ
    /// </summary>
    public byte MovementBy { get; set; }

    /// <summary>
    /// Mã loại chứng từ
    /// </summary>
    public string VoucherTypeCode { get; set; } = null!;

    /// <summary>
    /// Tên loại chứng từ
    /// </summary>
    public string VoucherTypeName { get; set; } = null!;

    /// <summary>
    /// Tài khoản nợ
    /// </summary>
    public string? DebitAccount { get; set; }

    /// <summary>
    /// Tài khoản có
    /// </summary>
    public string? CreditAccount { get; set; }

    /// <summary>
    /// Là dữ liệu hệ thống 
    /// </summary>
    public bool IsSystem { get; set; }

    /// <summary>
    /// Diễn giải
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Nhóm loại chứng từ
    /// </summary>
    public string? VoucherTypeCategory { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public bool Inactive { get; set; }

    public string? PrintedCreditAccount { get; set; }

    public string? PrintedDebitAccount { get; set; }

    public int? CorrespondingSummary { get; set; }
}