// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class AccountingBusinessGetHrSalarySheetDetailsResult
    {
        public Guid SalaryDetailID { get; set; }
        public string SalarySheetID { get; set; } = default!;
        public string? TransDate { get; set; }
        public string CustomerID { get; set; } = default!;
        public string? CustomerName { get; set; }
        public int? NoOfDependentPeople { get; set; }
        public int? NumOfWorkingDays { get; set; }
        public int? NumOfDayOfSalary { get; set; }
        [Column("NumOfOtherWorkingDays", TypeName = "decimal(22,8)")]
        public decimal? NumOfOtherWorkingDays { get; set; }
        public int? NumOfTardinessLeaveEarlyOrg { get; set; }
        public int? NumOfTardinessLeaveEarly { get; set; }
        public int? NumOfOverTime { get; set; }
        [Column("NumOfOverTimeDay", TypeName = "decimal(27,13)")]
        public decimal? NumOfOverTimeDay { get; set; }
        [Column("BaseSalary", TypeName = "decimal(22,8)")]
        public decimal? BaseSalary { get; set; }
        [Column("SalaryInsurance", TypeName = "decimal(22,8)")]
        public decimal? SalaryInsurance { get; set; }
        [Column("SaleSalary", TypeName = "decimal(22,8)")]
        public decimal? SaleSalary { get; set; }
        [Column("CriteriaSalary", TypeName = "decimal(22,8)")]
        public decimal? CriteriaSalary { get; set; }
        [Column("ResponsibilitySalary", TypeName = "decimal(22,8)")]
        public decimal? ResponsibilitySalary { get; set; }
        [Column("LostGoodsSalary", TypeName = "decimal(22,8)")]
        public decimal? LostGoodsSalary { get; set; }
        [Column("BaseSalaryOrg", TypeName = "decimal(1,1)")]
        public decimal BaseSalaryOrg { get; set; }
        [Column("SaleSalaryOrg", TypeName = "decimal(1,1)")]
        public decimal SaleSalaryOrg { get; set; }
        [Column("CriteriaSalaryOrg", TypeName = "decimal(1,1)")]
        public decimal CriteriaSalaryOrg { get; set; }
        [Column("ResponsibilitySalaryOrg", TypeName = "decimal(1,1)")]
        public decimal ResponsibilitySalaryOrg { get; set; }
        [Column("LostGoodsSalaryOrg", TypeName = "decimal(1,1)")]
        public decimal LostGoodsSalaryOrg { get; set; }
        [Column("OverTimeSalary", TypeName = "decimal(22,8)")]
        public decimal? OverTimeSalary { get; set; }
        [Column("PrizeMoney", TypeName = "decimal(22,8)")]
        public decimal? PrizeMoney { get; set; }
        [Column("OtherIncome", TypeName = "decimal(22,8)")]
        public decimal? OtherIncome { get; set; }
        [Column("SalaryProfit", TypeName = "decimal(22,8)")]
        public decimal? SalaryProfit { get; set; }
        [Column("MortgageProfit", TypeName = "decimal(22,8)")]
        public decimal? MortgageProfit { get; set; }
        [Column("TotalBenefit", TypeName = "decimal(22,8)")]
        public decimal? TotalBenefit { get; set; }
        [Column("SocialInsuranceEmp", TypeName = "decimal(22,8)")]
        public decimal? SocialInsuranceEmp { get; set; }
        [Column("UnemploymentInsuranceEmp", TypeName = "decimal(22,8)")]
        public decimal? UnemploymentInsuranceEmp { get; set; }
        [Column("HealthInsuranceEmp", TypeName = "decimal(22,8)")]
        public decimal? HealthInsuranceEmp { get; set; }
        [Column("LostGoodsKeeping", TypeName = "decimal(22,8)")]
        public decimal? LostGoodsKeeping { get; set; }
        [Column("ResponsibilityKeeping", TypeName = "decimal(22,8)")]
        public decimal? ResponsibilityKeeping { get; set; }
        [Column("CashShortOfCashier", TypeName = "decimal(22,8)")]
        public decimal? CashShortOfCashier { get; set; }
        [Column("RuleViolation", TypeName = "decimal(22,8)")]
        public decimal? RuleViolation { get; set; }
        [Column("ShortOfMortgage", TypeName = "decimal(22,8)")]
        public decimal? ShortOfMortgage { get; set; }
        [Column("TardinessLeaveEarlyPenalty", TypeName = "decimal(22,8)")]
        public decimal? TardinessLeaveEarlyPenalty { get; set; }
        [Column("ActuallyReceived", TypeName = "decimal(22,8)")]
        public decimal? ActuallyReceived { get; set; }
        [Column("The13thMonthSalary", TypeName = "decimal(22,8)")]
        public decimal? The13thMonthSalary { get; set; }
        [Column("SocialInsuranceCom", TypeName = "decimal(22,8)")]
        public decimal? SocialInsuranceCom { get; set; }
        [Column("UnemploymentInsuranceCom", TypeName = "decimal(22,8)")]
        public decimal? UnemploymentInsuranceCom { get; set; }
        [Column("HealthInsuranceCom", TypeName = "decimal(22,8)")]
        public decimal? HealthInsuranceCom { get; set; }
        [Column("PersonalIncomeTax", TypeName = "decimal(22,8)")]
        public decimal? PersonalIncomeTax { get; set; }
        [Column("TotalCostOfSalary", TypeName = "decimal(22,8)")]
        public decimal? TotalCostOfSalary { get; set; }
        [Column("UnionExpenses", TypeName = "decimal(22,8)")]
        public decimal? UnionExpenses { get; set; }
        [Column("UnionExpensesEmp", TypeName = "decimal(22,8)")]
        public decimal? UnionExpensesEmp { get; set; }
        public string? Description { get; set; }
        public int? Sort { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public string? Status { get; set; }
        public string? SynStatus { get; set; }
        public string? Time { get; set; }
        public string? SyncTime { get; set; }
    }
}
