// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class AccountingBusinessGetTransactionFeeDetailsResult
    {
        public Guid TransDetailID { get; set; }
        public string TransactionID { get; set; } = default!;
        public string FullGoodID { get; set; } = default!;
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public string? Status { get; set; }
        public string? SynStatus { get; set; }
        public string? SyncTime { get; set; }
        [Column("FeeAmount", TypeName = "decimal(22,8)")]
        public decimal FeeAmount { get; set; }
        [Column("FeeAmountOC", TypeName = "decimal(38,16)")]
        public decimal? FeeAmountOC { get; set; }
        [Column("FeeAmountVAT", TypeName = "decimal(22,8)")]
        public decimal FeeAmountVAT { get; set; }
        [Column("FeeAmountVATOC", TypeName = "decimal(38,16)")]
        public decimal? FeeAmountVATOC { get; set; }
        public string? FeeID { get; set; }
        public string? FeeNote { get; set; }
        public string DebitAccount { get; set; } = default!;
        public string CreditAccount { get; set; } = default!;
        public string? CustomerID { get; set; }
        public string? FeeVatID { get; set; }
        [Column("FeeTaxVatRate", TypeName = "decimal(22,8)")]
        public decimal? FeeTaxVatRate { get; set; }
        [Column("FeeTaxVatAmount", TypeName = "decimal(22,8)")]
        public decimal FeeTaxVatAmount { get; set; }
        [Column("FeeTaxVatAmountOC", TypeName = "decimal(38,16)")]
        public decimal? FeeTaxVatAmountOC { get; set; }
        public string? DebitFeeTaxVATAccount { get; set; }
        public string? CreditFeeTaxVATAccount { get; set; }
        public Guid FeeGroupID { get; set; }
        public string? FeeName { get; set; }
        public string? FeeSign { get; set; }
        public string? Description { get; set; }
    }
}
