// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class AccRptCircular
{
    public string CircularsNumber { get; set; } = null!;

    public string? Issuedby { get; set; }

    public string? IssuedDate { get; set; }

    public string? SignerBy { get; set; }

    public string? Status { get; set; }
}