// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class GoodFlg
{
    public string GoodId { get; set; }

    public string FlagOnDate { get; set; }

    public string FlagOffDate { get; set; }

    public string Status { get; set; }

    public string FlagOnBy { get; set; }
}