// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class HisExpPrice
{
    public string ZoneId { get; set; }

    public string GoodId { get; set; }

    public decimal? ExpWholePrice { get; set; }

    public decimal? ExpWholePriceVat { get; set; }

    public decimal? ExpRetailPrice { get; set; }

    public decimal? ExpRetailPriceVat { get; set; }

    public string CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string SyncTime { get; set; }

    public virtual Good Good { get; set; }

    public virtual Zone Zone { get; set; }
}