// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class HrDepartmentSaleSalary
{
    public string DepartmentId { get; set; } = null!;

    public string SaleSalaryId { get; set; } = null!;
}