// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class HrDepartmentCriteriaSalary
{
    public string DepartmentId { get; set; }

    public string CriteriaSalaryId { get; set; }

    public decimal? CriteriaSalaryValue { get; set; }
}