// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class ListVat
{
    public string VatId { get; set; }

    public int VatValue { get; set; }

    public string VatName { get; set; }

    public string SyncTime { get; set; }

    public virtual ICollection<Good> Goods { get; set; } = new List<Good>();
}