// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class ListShelf
{
    public string ShelfId { get; set; } = null!;

    public string StockId { get; set; } = null!;

    public string GoodId { get; set; } = null!;

    public string ZoneId { get; set; } = null!;

    public string? SyncTime { get; set; }

    public virtual Stock Stock { get; set; } = null!;
}