// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class OuterTran
{
    public string ExpTranId { get; set; } = null!;

    public string ImpTranId { get; set; } = null!;

    public string? ImportId { get; set; }

    public string? ExportId { get; set; }

    /// <summary>
    /// Trạng thái điều chuyển ngoài vùng (sang kho trung chuyển) 0: chưa nhận hàng; 1: đã nhận hàng
    /// </summary>
    public string? TranStatus { get; set; }

    public string? SyncTime { get; set; }
}