// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class PromotionByZone
{
    public string PromotionId { get; set; } = null!;

    public string ZoneId { get; set; } = null!;
}