// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class PromotionByZone
{
    public string PromotionId { get; set; }

    public string ZoneId { get; set; }
}