// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class ReportsExportRetailSummaryNotPayResult
    {
        public string? MainID { get; set; }
        public string? Name { get; set; }
        public string? TransCode { get; set; }
        public string? TransName { get; set; }
        public int SaleQuantity { get; set; }
        [Column("TotalImpPrice", TypeName = "decimal(38,8)")]
        public decimal TotalImpPrice { get; set; }
        [Column("TotalImpPriceVAT", TypeName = "decimal(38,8)")]
        public decimal TotalImpPriceVAT { get; set; }
        [Column("TotalExpPrice", TypeName = "decimal(38,8)")]
        public decimal TotalExpPrice { get; set; }
        [Column("TotalExpPriceVAT", TypeName = "decimal(38,8)")]
        public decimal TotalExpPriceVAT { get; set; }
        [Column("ProfitSale", TypeName = "decimal(38,8)")]
        public decimal ProfitSale { get; set; }
        [Column("Discount", TypeName = "decimal(38,8)")]
        public decimal Discount { get; set; }
        public string TransCodeReturn { get; set; } = default!;
        public string TransNameReturn { get; set; } = default!;
        public int returnQuantity { get; set; }
        [Column("TotalImpPriceReturn", TypeName = "decimal(38,8)")]
        public decimal TotalImpPriceReturn { get; set; }
        [Column("TotalImpPriceVATReturn", TypeName = "decimal(38,8)")]
        public decimal TotalImpPriceVATReturn { get; set; }
        [Column("TotalExpPriceReturn", TypeName = "decimal(38,8)")]
        public decimal TotalExpPriceReturn { get; set; }
        [Column("TotalExpPriceVATReturn", TypeName = "decimal(38,8)")]
        public decimal TotalExpPriceVATReturn { get; set; }
        [Column("ProfitReturn", TypeName = "decimal(38,8)")]
        public decimal ProfitReturn { get; set; }
        [Column("DiscountReturn", TypeName = "decimal(38,8)")]
        public decimal DiscountReturn { get; set; }
    }
}
