// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class StockBranch
{
    public string StockId { get; set; }

    public string BranchId { get; set; }

    public string SyncTime { get; set; }
}