// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class StockBranch
{
    public string StockId { get; set; } = null!;

    public string BranchId { get; set; } = null!;

    public string? SyncTime { get; set; }
}