// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class SystemCommonListContractByCustomersResult
    {
        public Guid ContractID { get; set; }
        public string? ContractName { get; set; }
        public string? ContractNumber { get; set; }
        public Guid AppendixContractID { get; set; }
        public string? AppendixNumber { get; set; }
        public string? AppendixName { get; set; }
        public string? ContractSignDate { get; set; }
        public string? ContractExpiredDate { get; set; }
        [Column("TotalContractAmount", TypeName = "decimal(22,8)")]
        public decimal? TotalContractAmount { get; set; }
    }
}
