// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class SystemCommonBarcoderotate_PacketResult
    {
        public string PacketID { get; set; } = default!;
        public string? PacketName { get; set; }
        public string? GoodID { get; set; }
        public int? Quantity { get; set; }
        public string BigUnitID { get; set; } = default!;
        public string UnitID { get; set; } = default!;
        [Column("ExchangeRate", TypeName = "decimal(22,8)")]
        public decimal? ExchangeRate { get; set; }
        public string Barcode { get; set; } = default!;
    }
}
