// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class SystemStockSummaryXNT_testResult
    {
        public string? StockID { get; set; }
        public string? Trancode { get; set; }
        public string? Transname { get; set; }
        public int QtyExport { get; set; }
        [Column("ExpAmount", TypeName = "decimal(38,8)")]
        public decimal ExpAmount { get; set; }
        [Column("ExpAmountVat", TypeName = "decimal(38,8)")]
        public decimal ExpAmountVat { get; set; }
        public int QtyImport { get; set; }
        [Column("ImpAmount", TypeName = "decimal(38,8)")]
        public decimal ImpAmount { get; set; }
        [Column("ImpAmountVat", TypeName = "decimal(38,8)")]
        public decimal ImpAmountVat { get; set; }
    }
}
