// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class SystemCommonBarcoderotate_Packet_printstampResult
    {
        public string PacketID { get; set; } = default!;
        public string ZoneID { get; set; } = default!;
        public string? PacketName { get; set; }
        [Column("TotalRetailPrice", TypeName = "decimal(38,8)")]
        public decimal? TotalRetailPrice { get; set; }
        [Column("TotalRetailPriceVat", TypeName = "decimal(38,8)")]
        public decimal? TotalRetailPriceVat { get; set; }
        [Column("TotalRetailDiscount", TypeName = "decimal(38,8)")]
        public decimal? TotalRetailDiscount { get; set; }
        public string? Description { get; set; }
        public string? Status { get; set; }
        public string? SyncTime { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public string? SynStatus { get; set; }
        public string Barcode { get; set; } = default!;
    }
}
