// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatPhatAcc.AccountingDbContext
{
    public partial class SystemCommonBarcoderotateResult
    {
        public string GoodID { get; set; } = default!;
        public string? ShortName { get; set; }
        public string? FullName { get; set; }
        public string? SupplierID { get; set; }
        public string? GoodSupID { get; set; }
        public string? BranchID { get; set; }
        public string? GroupID { get; set; }
        public string? UnitID { get; set; }
        public string? BigUnitID { get; set; }
        public string? ManufactureID { get; set; }
        public int? ConvertUnit { get; set; }
        public string? ImpVat { get; set; }
        public string? ExpVat { get; set; }
        [Column("ImpPrice", TypeName = "decimal(22,8)")]
        public decimal? ImpPrice { get; set; }
        [Column("ExpWholePrice", TypeName = "decimal(22,8)")]
        public decimal? ExpWholePrice { get; set; }
        [Column("ExpRetailPrice", TypeName = "decimal(22,8)")]
        public decimal? ExpRetailPrice { get; set; }
        [Column("AverImpPrice", TypeName = "decimal(22,8)")]
        public decimal? AverImpPrice { get; set; }
        [Column("ImpPriceVat", TypeName = "decimal(22,8)")]
        public decimal? ImpPriceVat { get; set; }
        [Column("ExpWholePriceVat", TypeName = "decimal(22,8)")]
        public decimal? ExpWholePriceVat { get; set; }
        [Column("ExpRetailPriceVat", TypeName = "decimal(22,8)")]
        public decimal? ExpRetailPriceVat { get; set; }
        [Column("AverImpPriceVat", TypeName = "decimal(22,8)")]
        public decimal? AverImpPriceVat { get; set; }
        [Column("LastImpPrice", TypeName = "decimal(22,8)")]
        public decimal LastImpPrice { get; set; }
        [Column("LastImpPriceVat", TypeName = "decimal(38,12)")]
        public decimal LastImpPriceVat { get; set; }
        public string? ImagePath { get; set; }
        public string? ImageName { get; set; }
        public string? Note { get; set; }
        public bool? Warranty { get; set; }
        public int? NumberWarrantyDay { get; set; }
        public bool? HasExpireDate { get; set; }
        public int? NumberExpireDay { get; set; }
        public bool? HasSerial { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
        public string? Status { get; set; }
        public string? SynStatus { get; set; }
        public string? SyncTime { get; set; }
        public bool? Enable { get; set; }
        public string Barcode { get; set; } = default!;
    }
}
