// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.AccountingDbContext;

public partial class VoucherMark20190601
{
    public int Orders { get; set; }

    public Guid VoucherDetailId { get; set; }

    public string ZoneId { get; set; }

    public string DebitAccount { get; set; }

    public string CreditAccount { get; set; }

    public decimal AmountOc { get; set; }

    public decimal Amount { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string Time { get; set; }

    public string SyncTime { get; set; }
}