// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class CheckStatisticsDetail
{
    public int ItemId { get; set; }

    public string TranId { get; set; }

    public string GoodId { get; set; }

    public string FullGoodId { get; set; }

    public decimal? AverPrice { get; set; }

    public decimal? AverPriceVat { get; set; }

    public int? StockQty { get; set; }

    public int? InvenQty { get; set; }

    public string Status { get; set; }

    public string SynStatus { get; set; }

    public string SyncTime { get; set; }

    public virtual Good Good { get; set; }

    public virtual CheckStatistic Tran { get; set; }
}