// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class ExtPrice
{
    public string GoodId { get; set; }

    public string TypeId { get; set; }

    public decimal ExtPrice1 { get; set; }

    public decimal ExtPriceVat { get; set; }

    public string SynStatus { get; set; }

    public string SyncTime { get; set; }

    public virtual Good Good { get; set; }
}