// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class HrDepartment
{
    public string DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    /// <summary>
    /// Số tiền nguyên tệ
    /// </summary>
    public decimal? SalaryBase { get; set; }

    /// <summary>
    /// Số tiền nguyên tệ
    /// </summary>
    public decimal? SalaryInsurance { get; set; }

    public decimal? SalaryProfitRate { get; set; }

    public decimal? MortgageProfitRate { get; set; }

    public decimal? SaleForOvertime { get; set; }

    public int? SalaryPayDay { get; set; }

    public bool? SalarySaleByWorkday { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string Status { get; set; }

    public string SynStatus { get; set; }

    public string SyncTime { get; set; }
}