// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class HrDepartmentLostGoodsSalary
{
    public string DepartmentId { get; set; }

    public string LostGoodsSalaryId { get; set; }

    public decimal? LostGoodsSalaryValue { get; set; }
}