// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class HrOverTime
{
    public string IdAuto { get; set; }

    public string CustomerId { get; set; }

    /// <summary>
    /// Ngày trong tháng
    /// </summary>
    public string OverTimeDay { get; set; }

    public string OverTimeBegin { get; set; }

    public string OverTimeEnd { get; set; }

    public string DepartmentIdApply { get; set; }

    public decimal? SalaryRateApply { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string Status { get; set; }

    public string SynStatus { get; set; }

    public string SyncTime { get; set; }
}