// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class OrderConditionSchedule
{
    public string CustomerId { get; set; }

    public string ScheduleType { get; set; }

    public string ScheduleValue { get; set; }

    public bool? EnableSchedule { get; set; }

    public string OrderConditionType { get; set; }

    public string OrderValues { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string SyncTime { get; set; }
}