// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class OriginalTransaction
{
    public string TransactionId { get; set; }

    public string CustomerId { get; set; }

    public string OrgTransType { get; set; }

    public decimal? Debt { get; set; }

    public decimal? Have { get; set; }

    public string TransDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string SyncTime { get; set; }
}