// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class Systranscutdate
{
    public string ZoneId { get; set; }

    public string TransCut { get; set; }

    public string CreatedBy { get; set; }

    public string FromDate { get; set; }

    public string ToDate { get; set; }

    public string SyncTime { get; set; }
}