// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class TransactionLotNumberDetail
{
    public string ZoneId { get; set; }

    public Guid TransDetailId { get; set; }

    public string TransactionId { get; set; }

    public string FullGoodId { get; set; }

    /// <summary>
    /// Hạn Sử dụng
    /// </summary>
    public string LotNumber { get; set; }

    public string SyncTime { get; set; }
}