// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatPhatAcc.Accounting_LTTDbContext;

public partial class ZzHrmschedule
{
    public Guid ScheduleId { get; set; }

    /// <summary>
    /// mã lịch
    /// </summary>
    public string SchCode { get; set; }

    /// <summary>
    /// Tên lịch
    /// </summary>
    public string Schname { get; set; }

    /// <summary>
    /// chọn kiểu lịch chấm công, weekly: theo tuần, monthly: theo tháng, yearly: theo năm
    /// </summary>
    public string CycleMode { get; set; }

    /// <summary>
    /// Không tính vắng khi có xếp ca vào ngày lễ mà không đi làm 0 không xét vắng, 1 có xét vắng
    /// </summary>
    public bool? IsAbsentHol { get; set; }
}